### ISSUE TITLE
load data error when length of column  exceeds 65535 even the field type is mediumtext

### ISSUE THREAD

**Issue by yexiaoli88** [actiontech/dble#1000]
* **dble version：5.6.29-dble-9.9.9.9-67ef8f8ac06964c52abd4c15f903fb74b8752f88-20190218024823**  
* **configs：** 
```
create table t1(id int,aa mediumtext);
```
**schema.xml**  

```
        <schema name="mytest" sqlMaxLimit="100" dataNode="dn1">
       		<table name="test_global" dataNode="dn1,dn2,dn3,dn4" type="global"/>
	</schema>
```

* **steps：**    
step1.  generate a  text.txt that size more than 64KB,then edit text.txt adding the value for id
```
s = "abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyz"
with open('text.txt', 'w') as f:
   for _ in xrange(20000):
      f.write(s)
```
step2. execute load data in dble
```
mysql> load data infile "/opt/mysql/data/text.txt" into table t1 fields terminated by ',' lines terminated by '|';
ERROR 3009 (HY000): Length of parsed input (65536) exceeds the maximum number of characters defined in your parser settings (65535). 
Parser Configuration: CsvParserSettings:
	Auto configuration enabled=true
	Autodetect column delimiter=false
	Autodetect quotes=false
	Column reordering enabled=true
	Empty value=null
	Escape unquoted values=false
	Header extraction enabled=null
	Headers=null
	Ignore leading whitespaces=false
	Ignore trailing whitespaces=false
	Input buffer size=1048576
	Input reading on separate thread=true
	K

```
step3:execute load data in mysql
```
mysql>  load data infile "/opt/mysql/data/text.txt" into table t1 fields terminated by ',' lines terminated by '|';
Query OK, 1 row affected (0.05 sec)
Records: 1  Deleted: 0  Skipped: 0  Warnings: 0
```

step4: less dble.log
```
abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmno
        at com.univocity.parsers.common.AbstractParser.handleException(AbstractParser.java:339) ~[univocity-parsers-2.2.1.jar:2.2.1]
        at com.univocity.parsers.common.AbstractParser.parseNext(AbstractParser.java:475) ~[univocity-parsers-2.2.1.jar:2.2.1]
        at com.actiontech.dble.server.handler.ServerLoadDataInfileHandler.parseFileByLine(ServerLoadDataInfileHandler.java:649) ~[dble-9.9.9.9.jar:?]
        at com.actiontech.dble.server.handler.ServerLoadDataInfileHandler.start(ServerLoadDataInfileHandler.java:194) ~[dble-9.9.9.9.jar:?]
        at com.actiontech.dble.net.FrontendConnection.loadDataInfileStart(FrontendConnection.java:265) [dble-9.9.9.9.jar:?]
        at com.actiontech.dble.server.ServerQueryHandler.query(ServerQueryHandler.java:134) [dble-9.9.9.9.jar:?]
        at com.actiontech.dble.net.FrontendConnection.query(FrontendConnection.java:330) [dble-9.9.9.9.jar:?]
        at com.actiontech.dble.net.FrontendConnection.query(FrontendConnection.java:346) [dble-9.9.9.9.jar:?]
        at com.actiontech.dble.net.handler.FrontendCommandHandler.handleData(FrontendCommandHandler.java:88) [dble-9.9.9.9.jar:?]
        at com.actiontech.dble.net.handler.FrontendCommandHandler.handle(FrontendCommandHandler.java:66) [dble-9.9.9.9.jar:?]
        at com.actiontech.dble.net.handler.FrontEndHandlerRunnable.run(FrontEndHandlerRunnable.java:44) [dble-9.9.9.9.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_111]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_111]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
Caused by: java.lang.ArrayIndexOutOfBoundsException

```
* **expect result：**  
    1.step 2 should execute success
* **real result：**  
    1.step2 error
* **supplements：**  
    1.

/label ~BUG

**Comment by sunsun314** [comment]
load data limit set by
```
            settings.setMaxColumns(65535);
            settings.setMaxCharsPerColumn(65535);
```

**Comment by Baofengqi** [comment]
add maxCharsPerColumn parameter in server.xml when data size per column is over 65535.
doc update - https://github.com/actiontech/dble-docs-cn/blob/develop/1.config_file/1.3_server.xml.md

**Comment by yexiaoli88** [comment]
verified on version: 5.6.29-dble-2.19.01.0-303221e9e77e00d7741629e15f8053e4fa196de3-20190228085303

**Comment by yexiaoli88** [comment]
auto_test position:features/sql_cover/special/loaddata.feature
