### ISSUE TITLE
Error，when use mysqldb execute `show @@processlist`

### ISSUE THREAD

**Issue by FlyingMao** [actiontech/dble#1041]
* **dble version：**  
5.6.29-dble-2.19.01.0-303221e9e77e00d7741629e15f8053e4fa196de3-20190228085303
* **preconditions ：**  
no
* **configs：** 

**schema.xml**  

```


```

**rule.xml**  

```


```

**server.xml**  

```


```

* **steps：**    
    step1.  
```
import MySQLdb
conn=MySQLdb.connect('10.186.65.63','root','123456','',9066,autocommit=True)
cur=conn.cursor()
cur.execute("show @@processlist")
```
* **expect result：**  
    1. execute successful
* **real result：**  
    1.
```
>>> cur.execute("show @@processlist")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib64/python2.7/site-packages/MySQLdb/cursors.py", line 205, in execute
    self.errorhandler(self, exc, value)
  File "/usr/lib64/python2.7/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
ValueError: invalid literal for long() with base 10: 'NULL'
```
* **supplements：**  
    1.

/label ~BUG

**Comment by FlyingMao** [comment]
verified version：5.6.29-dble-9.9.9.9-3f3f64fa0c2733adccaa52b5bc652e1ea8725b56-20190311022855
