### ISSUE TITLE
Need to optimize, when starting dble, the configuration does not include the tables involved in the view

### ISSUE THREAD

**Issue by FlyingMao** [actiontech/dble#1100]
* **dble version：**  
5.6.29-dble-9.9.9.9-804834f13996ceb825b95c647692dce650d14bea-20190403054824
* **preconditions ：**  
no
* **configs：** 

**schema.xml**  

```
<schema name="mytest" sqlMaxLimit="100">
 <table name="test1" dataNode="dn1,dn2" rule="hash-two" primaryKey="id"/>
</schema>
```

**rule.xml**  

```


```

**server.xml**  

```


```

* **steps：**    
    step1. create view on dble
```
use mytest;
create table test1(id int,age int);
create view view_test as select * from test1;
``` 
  step2. change schema.xml such as:
```
<schema name="schema1" sqlMaxLimit="100">
 <table name="test2" dataNode="dn1,dn2" rule="hash-two" primaryKey="id"/>
</schema>
```
  step3. restart dble
* **expect result：**  
    1. restart dble successed 
* **real result：**  
    1.restart dble failed and NPE in dble.log
```
INFO   | jvm 1    | 2019/04/08 05:24:18 | java.io.IOException: java.lang.NullPointerException
INFO   | jvm 1    | 2019/04/08 05:24:18 | 	at com.actiontech.dble.DbleServer.pullVarAndMeta(DbleServer.java:269)
INFO   | jvm 1    | 2019/04/08 05:24:18 | 	at com.actiontech.dble.DbleServer.startup(DbleServer.java:428)
INFO   | jvm 1    | 2019/04/08 05:24:18 | 	at com.actiontech.dble.DbleStartup.main(DbleStartup.java:30)
INFO   | jvm 1    | 2019/04/08 05:24:18 | 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
INFO   | jvm 1    | 2019/04/08 05:24:18 | 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
INFO   | jvm 1    | 2019/04/08 05:24:18 | 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
INFO   | jvm 1    | 2019/04/08 05:24:18 | 	at java.lang.reflect.Method.invoke(Method.java:498)
INFO   | jvm 1    | 2019/04/08 05:24:18 | 	at org.tanukisoftware.wrapper.WrapperSimpleApp.run(WrapperSimpleApp.java:240)
INFO   | jvm 1    | 2019/04/08 05:24:18 | 	at java.lang.Thread.run(Thread.java:748)
INFO   | jvm 1    | 2019/04/08 05:24:18 | Caused by: java.lang.NullPointerException
INFO   | jvm 1    | 2019/04/08 05:24:18 | 	at com.actiontech.dble.meta.ProxyMetaManager.loadViewMeta(ProxyMetaManager.java:387)
INFO   | jvm 1    | 2019/04/08 05:24:18 | 	at com.actiontech.dble.meta.ProxyMetaManager.loadViewFromFile(ProxyMetaManager.java:360)
INFO   | jvm 1    | 2019/04/08 05:24:18 | 	at com.actiontech.dble.meta.ProxyMetaManager.initMeta(ProxyMetaManager.java:415)
INFO   | jvm 1    | 2019/04/08 05:24:18 | 	at com.actiontech.dble.meta.ProxyMetaManager.init(ProxyMetaManager.java:297)
INFO   | jvm 1    | 2019/04/08 05:24:18 | 	at com.actiontech.dble.DbleServer.pullVarAndMeta(DbleServer.java:267)
INFO   | jvm 1    | 2019/04/08 05:24:18 | 	... 8 more
```
* **supplements：**  
    1.

/label ~BUG

**Comment by FlyingMao** [comment]
**verified version：** dble-9.9.9.9-2d18ed6c8dae540e4becc2ba03472b2284238f58-20190429070246
