### ISSUE TITLE
Dble has an error message 'ClosedChannelException' when the client set useServerPrepStmts=true

### ISSUE THREAD

**Issue by yinyanghuafa** [actiontech/dble#1122]
* dble version：
  dble-9.9.9.9-884fc6b612d64cc22101226536f8fd1d24580857-20190221182143
* preconditions ： 
```
create table if not exists company (id bigint not null auto_increment,name varchar(20) not null,address varchar(250) not null,create_time timestamp not null,owner varchar(20) not null,employees integer not null default 50,primary key(id))engine=innodb charset=utf8;
insert into company values(2,'lisi','2','2011-01-01 00:00:00','4','5');
```
* configs：

schema.xml
```
<table name="company" primaryKey="ID" type="global" dataNode="dn1"/>

```

rule.xml

```


```

server.xml 

```


```

* steps： 
    step1.  
```
  public static void main(String[] args) throws Exception  {
        String sql = "SELECT * FROM company where id = ?";
        CountDownLatch latch = new CountDownLatch(1);
        for(int i= 0 ; i  < 1 ; i++){
            Connection con = getConnection();
            con.setAutoCommit(false);
            new Thread(new Runnable(){
                @Override
                public void run() {
                    PreparedStatement statement = null;
                    ResultSet rs = null;
                    try{
                        for(int i= 0 ; i < 500; i++ ){
                            statement = con.prepareStatement(sql);
                            statement.setInt(1,2);
                            rs = statement.executeQuery();
                            while (rs.next()) {
                                String title = rs.getString("id");
                                String author = rs.getString("name");
                                System.out.println("title:  "+title+"author: "+author);
                            }
                            statement.close();
                            System.out.println("finished:"+i);
                        }
                        con.commit();
                    }catch(Exception e){
                        e.printStackTrace();
                    }
                    finally {
                    }
                }
            }).start();
        }
    }
    public static Connection getConnection(){
        Connection connection = null;
        final String JDBC_DRIVER = "com.mysql.jdbc.Driver";
        final String DB_URL = "jdbc:mysql://ip:port/testdb?useServerPrepStmts=true";
        final String USER = "root";
        final String PASS = "password";
		try {
			Class.forName(JDBC_DRIVER);
		} catch (ClassNotFoundException e) {
			e.printStackTrace();
		}
		try {
			connection = DriverManager.getConnection(DB_URL, USER, PASS);
		}catch(Exception e){
			e.printStackTrace();
		}
        return connection ;
    }
```
* expect result：
    1.Client:
```
       title:  2author: lisi
       finished:0
       ...
       title:  2author: lisi
       finished:499
```
* real result：
```
    1.Client:

       title:  2author: lisi
       finished:0
       ...
       java.sql.SQLException: Unknown pStmtId when executing.
       at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:965)

    2.Server:

       [DEBUG][complexQueryExecutor6] caught err: java.nio.channels.ClosedChannelException
       at sun.nio.ch.SocketChannelImpl.ensureWriteOpen(SocketChannelImpl.java:270)
```
* supplements：
    1.

/label ~BUG

**Comment by FlyingMao** [comment]
**verified version：** dble-9.9.9.9-b41e73f2227d8f476eeb3dc3ed877612a77c889f-20190418142730

**Comment by Baofengqi** [comment]
@yinyanghuafa modify test code, ClosedChannelException is abnormal.
