### ISSUE TITLE
sysbench prepare returns error

### ISSUE THREAD

**Issue by yexiaoli88** [actiontech/dble#1129]
* **dble version：5.6.29-dble-9.9.9.9-8d0d0fb1d6a9e92fa567b3e5ed2a88ce2bcef4b3-20190410091627**  
* **preconditions ：**  
1.edit wrapper.conf as follows:
```
wrapper.java.additional.12=-XX:MaxDirectMemorySize=2G
wrapper.java.additional.17=-XX:+PrintGCDetails
```
2. sysbench version: sysbench 1.0.17

* **configs：** 

**schema.xml**  

```
 <schema name="testdb" sqlMaxLimit="100" dataNode="dn4">
        <table name="test" dataNode="dn1,dn2,dn3,dn4" type="global"/>
    </schema>

```

* **steps：**    
1. sysbench prepare on dble:
```
sysbench --mysql-host=10.186.65.94 --mysql-port=8066 --mysql-user=test --mysql-password=123 --mysql-db=testdb --tables=100 --table-size=100000 --report-interval=5 --skip-trx=on --threads=100 oltp_read_write.lua prepare;
```
error messages return:
```
FATAL: mysql_drv_query() returned error 1105 (GC overhead limit exceeded) for query 'INSERT INTO sbtest27(k, c, pad) VALUES(49779, '66355432856-69647260153-80333516340-90019812569-91524940584-67722368036-46943456288-47450884309-43709878910-39320974970', '05269825162-76858276915-27258255679-42499382709-62459225108'),...,(40888, '17722218078-85437122262-77194429937-54435986823-01272612939-77820163728-50599873720-318352FATAL: `sysbench.cmdline.call_command' function failed: ./oltp_common.lua:230: db_bulk_insert_next() failed
```
gc.log details : [gc.log](https://github.com/actiontech/dble/files/3082861/gc.log)

2. edit wrapper.conf as follows:
```
# Initial Java Heap Size (in MB),default=3
wrapper.java.initmemory=100

# Maximum Java Heap Size (in MB),default=64
wrapper.java.maxmemory=2048

```

3.clean all the tables and sysbench prepare on dble again:
```
sysbench --mysql-host=10.186.65.94 --mysql-port=8066 --mysql-user=test --mysql-password=123 --mysql-db=testdb --tables=100 --table-size=100000 --report-interval=5 --skip-trx=on --threads=100 oltp_read_write.lua prepare;
```
 error messages return:
```
FATAL: mysql_drv_query() returned error 1105 (Java heap space) for query 'INSERT INTO sbtest91(k, c, pad) VALUES(49790, '22106010567-92358839279-89427673355-14036524669-75328969689-84642957574-26309584771-40980152254-72467136730-63347203007', '11546284418-26156593299-24753723645-12281457581-01308830255'),...,(50201, '59070677233-85792253697-68482179274-68196360913-69753506748-50209489865-31530718396-95923275317-90877FATAL: `sysbench.cmdline.call_command' function failed: ./oltp_common.lua:230: db_bulk_insert_next() failed
```
gc log details:  [gc_2.log](https://github.com/actiontech/dble/files/3082893/gc_2.log)

4. edit wrapper.conf as follows:
```
wrapper.java.additional.12=-XX:MaxDirectMemorySize=4G
```

5.clean all the tables and sysbench prepare on dble again:
```
sysbench --mysql-host=10.186.65.94 --mysql-port=8066 --mysql-user=test --mysql-password=123 --mysql-db=testdb --tables=100 --table-size=100000 --report-interval=5 --skip-trx=on --threads=100 oltp_read_write.lua prepare;
```
 error messages return:
```
FATAL: mysql_drv_query() returned error 1105 (Java heap space) for query 'INSERT INTO sbtest83(k, c, pad) VALUES(49790, '22106010567-92358839279-89427673355-14036524669-75328969689-84642957574-26309584771-40980152254-72467136730-63347203007', '11546284418-26156593299-24753723645-12281457581-01308830255'),...,(50201, '59070677233-85792253697-68482179274-68196360913-69753506748-50209489865-31530718396-95923275317-90877FATAL: `sysbench.cmdline.call_command' function failed: ./oltp_common.lua:230: db_bulk_insert_next() failed
```
gc log details:  [gc_3.log](https://github.com/actiontech/dble/files/3082904/gc_3.log)

wrapper.log
```
INFO   | jvm 1    | 2019/04/16 03:26:03 | java.lang.OutOfMemoryError: Java heap space
INFO   | jvm 1    | 2019/04/16 03:26:03 | 	at java.util.Arrays.copyOf(Arrays.java:3332)
INFO   | jvm 1    | 2019/04/16 03:26:03 | 	at java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:124)
INFO   | jvm 1    | 2019/04/16 03:26:03 | 	at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:448)
INFO   | jvm 1    | 2019/04/16 03:26:03 | 	at java.lang.StringBuilder.append(StringBuilder.java:136)
INFO   | jvm 1    | 2019/04/16 03:26:03 | 	at org.apache.logging.log4j.core.pattern.LineSeparatorPatternConverter.format(LineSeparatorPatternConverter.java:64)
INFO   | jvm 1    | 2019/04/16 03:26:03 | 	at org.apache.logging.log4j.core.pattern.PatternFormatter.format(PatternFormatter.java:38)
INFO   | jvm 1    | 2019/04/16 03:26:03 | 	at org.apache.logging.log4j.core.layout.PatternLayout$PatternSerializer.toSerializable(PatternLayout.java:294)
INFO   | jvm 1    | 2019/04/16 03:26:03 | 	at org.apache.logging.log4j.core.layout.PatternLayout.toText(PatternLayout.java:195)
INFO   | jvm 1    | 2019/04/16 03:26:03 | 	at org.apache.logging.log4j.core.layout.PatternLayout.encode(PatternLayout.java:180)
INFO   | jvm 1    | 2019/04/16 03:26:03 | 	at org.apache.logging.log4j.core.layout.PatternLayout.encode(PatternLayout.java:57)
INFO   | jvm 1    | 2019/04/16 03:26:03 | 	at org.apache.logging.log4j.core.appender.AbstractOutputStreamAppender.directEncodeEvent(AbstractOutputStreamAppender.java:176)
INFO   | jvm 1    | 2019/04/16 03:26:03 | 	at org.apache.logging.log4j.core.appender.AbstractOutputStreamAppender.tryAppend(AbstractOutputStreamAppender.java:169)
INFO   | jvm 1    | 2019/04/16 03:26:03 | 	at org.apache.logging.log4j.core.appender.AbstractOutputStreamAppender.append(AbstractOutputStreamAppender.java:160)
INFO   | jvm 1    | 2019/04/16 03:26:03 | 	at org.apache.logging.log4j.core.appender.RollingRandomAccessFileAppender.append(RollingRandomAccessFileAppender.java:104)
INFO   | jvm 1    | 2019/04/16 03:26:03 | 	at org.apache.logging.log4j.core.config.AppenderControl.tryCallAppender(AppenderControl.java:156)
INFO   | jvm 1    | 2019/04/16 03:26:03 | 	at org.apache.logging.log4j.core.config.AppenderControl.callAppender0(AppenderControl.java:129)
INFO   | jvm 1    | 2019/04/16 03:26:03 | 	at org.apache.logging.log4j.core.config.AppenderControl.callAppenderPreventRecursion(AppenderControl.java:120)
INFO   | jvm 1    | 2019/04/16 03:26:03 | 	at org.apache.logging.log4j.core.config.AppenderControl.callAppender(AppenderControl.java:84)
INFO   | jvm 1    | 2019/04/16 03:26:03 | 	at org.apache.logging.log4j.core.config.LoggerConfig.callAppenders(LoggerConfig.java:447)
INFO   | jvm 1    | 2019/04/16 03:26:03 | 	at org.apache.logging.log4j.core.async.AsyncLoggerConfig.asyncCallAppenders(AsyncLoggerConfig.java:114)
INFO   | jvm 1    | 2019/04/16 03:26:03 | 	at org.apache.logging.log4j.core.async.AsyncLoggerConfigDisruptor$Log4jEventWrapperHandler.onEvent(AsyncLoggerConfigDisruptor.java:112)
INFO   | jvm 1    | 2019/04/16 03:26:03 | 	at org.apache.logging.log4j.core.async.AsyncLoggerConfigDisruptor$Log4jEventWrapperHandler.onEvent(AsyncLoggerConfigDisruptor.java:98)
INFO   | jvm 1    | 2019/04/16 03:26:03 | 	at com.lmax.disruptor.BatchEventProcessor.run(BatchEventProcessor.java:129)
INFO   | jvm 1    | 2019/04/16 03:26:03 | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
INFO   | jvm 1    | 2019/04/16 03:26:03 | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
INFO   | jvm 1    | 2019/04/16 03:26:03 | 	at java.lang.Thread.run(Thread.java:745)

```
* **expect result：**  
  1. sysbench prepare success

/label ~BUG

**Comment by wjl1619** [comment]
This issue is occur because the configuration in wrapper.conf for stack is insufficient, so we can increase the value for "-Xmx"  to resolve this problem.

**Comment by sunsun314** [comment]
Inner confluence report  http://10.186.18.11/confluence/pages/viewpage.action?pageId=15277030
