### ISSUE TITLE
NonBlockingSession#freshConn will leak the old connection when using XA Transaction

### ISSUE THREAD

**Issue by tankilo** [actiontech/dble#1158]
* **dble version：**  
* **preconditions ：**  
no
* **configs：** 

**schema.xml**  

```
<table name="xa_test" dataNode="dn1,dn2" rule="sharding-by-mod2" primaryKey="ID"/>
```

**rule.xml**  

```
<tableRule name="sharding-by-mod2">
        <rule>
            <columns>id</columns>
            <algorithm>hashmod2</algorithm>
        </rule>
    </tableRule>
    <function name="hashmod2" class="Hash">
        <property name="partitionCount">2</property>
        <property name="partitionLength">1</property>
    </function>
```

**server.xml**  

```


```

* **steps：**    
step1.  edit com.actiontech.dble.backend.mysql.nio.MySQLConnection#execCmd
```
private static boolean MOCK = true;
public void execCmd(String cmd) {
	if (MySQLConnection.MOCK && cmd.startsWith("XA COMMIT")) {
		cmd = cmd.replace("'", "\\'");
		cmd = "'MOCK ERROR\\'" + cmd + "'";
	}
	this.sendQueryCmd(cmd, this.charsetName);
}
```
step2. execute the following sql. 
```
mysql> set xa=1;
Query OK, 0 rows affected (0.01 sec)

mysql> delete from xa_test;
ERROR 2013 (HY000): Lost connection to MySQL server during query
```
This is as exepected, i replace `XA COMMIT XXX` with sql containing syntax error. In method `XACommitNodesHandler#cleanAndFeedback`, when `XA COMMIT XXX` failed more than `XACommitNodesHandler#COMMIT_TIMES`, front connection will be closed and dble will  endlessly retry commtting in in the background.

step3. observe backend connection size via executing `show @@backend;`

Backend connection size will keep growing due to connection leaking.
![image](https://user-images.githubusercontent.com/10413284/57187113-da13aa00-6f1c-11e9-94b6-050a4bce4149.png)

step4. stop the program at break point `MySQLConnection#execCmd`, set value of `MySQLConnection.MOCK` to `false`.

![image](https://user-images.githubusercontent.com/10413284/57186902-a2573300-6f19-11e9-89a3-028b136c0e4f.png)

step5. whether `XA COMMIT` is  successfully executed in the background or not ,backend connection leaking happen. 

* **expect result：**  
    1. backend connection will be released
* **real result：**  
    1. connection leaking happen.
* **supplements：**  
    1.

/label ~BUG

**Comment by tankilo** [comment]
Because only the connections in `com.actiontech.dble.server.NonBlockingSession#target` will be released, i think before binding the new connection to `NonBlockingSession#target`, the old connection should be manually closed. 
![image](https://user-images.githubusercontent.com/10413284/57187337-6626d100-6f1f-11e9-9900-efbf2d7ec29f.png)
And due to those judge condition `if (decrementCountBy(1)) {` , i think old connection's respHandler should be cleared before closing to avoid nodeCount decreased to negative number.
```
2019-05-01 11:03:32,039 [ERROR][Timer0] GPGP reset initCount:1, session:{dn1{INSERT INTO xa_test (id)
VALUES (2)}.0=MySQLConnection [id=19, lastTime=1556679811046, lastSql='MOCK ERROR\'XA COMMIT \'Dble_Server.1.31.db1\'', user=root, schema=db1, old schema=null, borrowed=true, fromSlaveDB=false, threadId=2917,character_set_client=utf8,character_set_results=utf8,collation_connection=utf8_general_ci, txIsolation=-1, autocommit=true, attachment=dn1{INSERT INTO xa_test (id)
VALUES (2)}.0, respHandler=com.actiontech.dble.backend.mysql.nio.handler.transaction.xa.XACommitNodesHandler@124b4fb9, host=localhost, port=3306, statusSync=null, writeQueue=0, modifiedSQLExecuted=false]} java.lang.Throwable
  at com.actiontech.dble.backend.mysql.nio.handler.transaction.xa.XACommitNodesHandler.commit(XACommitNodesHandler.java:57)
  at com.actiontech.dble.server.NonBlockingSession.commit(NonBlockingSession.java:629)
  at com.actiontech.dble.backend.mysql.xa.XASessionCheck.checkCommitSession(XASessionCheck.java:45)
  at com.actiontech.dble.backend.mysql.xa.XASessionCheck.checkSessions(XASessionCheck.java:37)
  at com.actiontech.dble.DbleServer$6$1.run(DbleServer.java:836)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
  at java.lang.Thread.run(Thread.java:748)
2019-05-01 11:03:32,041 [ERROR][Timer0] GPGP quit conn:,MySQLConnection [id=19, lastTime=1556679811046, lastSql='MOCK ERROR\'XA COMMIT \'Dble_Server.1.31.db1\'', user=root, schema=db1, old schema=null, borrowed=true, fromSlaveDB=false, threadId=2917,character_set_client=utf8,character_set_results=utf8,collation_connection=utf8_general_ci, txIsolation=-1, autocommit=true, attachment=dn1{INSERT INTO xa_test (id)
2019-05-01 11:03:32,042 [ERROR][complexQueryExecutor3] GPGP reset decrementCountBy:1, nodeCount after:0, connection:MySQLConnection [id=19, lastTime=1556679811046, lastSql=QuitPacket.QUIT, user=root, schema=db1, old schema=null, borrowed=true, fromSlaveDB=false, threadId=2917,character_set_client=utf8,character_set_results=utf8,collation_connection=utf8_general_ci, txIsolation=-1, autocommit=true, attachment=dn1{INSERT INTO xa_test (id)
VALUES (2)}.0, respHandler=com.actiontech.dble.backend.mysql.nio.handler.transaction.xa.XACommitNodesHandler@124b4fb9, host=localhost, port=3306, statusSync=null, writeQueue=0, modifiedSQLExecuted=false] java.lang.Throwable
  at com.actiontech.dble.backend.mysql.nio.handler.MultiNodeHandler.decrementCountBy(MultiNodeHandler.java:108)
  at com.actiontech.dble.backend.mysql.nio.handler.transaction.xa.XACommitNodesHandler.innerConnectError(XACommitNodesHandler.java:367)
  at com.actiontech.dble.backend.mysql.nio.handler.transaction.xa.XACommitNodesHandler.connectionClose(XACommitNodesHandler.java:340)
  at com.actiontech.dble.backend.mysql.nio.MySQLConnection$1.run(MySQLConnection.java:699)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
  at java.lang.Thread.run(Thread.java:748)
2019-05-01 11:03:32,043 [ERROR][backendBusinessExecutor0] GPGP reset decrementCountBy:1, nodeCount after:-1, connection:MySQLConnection [id=20, lastTime=1556679812025, lastSql='MOCK ERROR\'XA COMMIT \'Dble_Server.1.31.db1\'', user=root, schema=db1, old schema=null, borrowed=true, fromSlaveDB=false, threadId=2918,character_set_client=utf8,character_set_results=utf8,collation_connection=utf8_general_ci, txIsolation=-1, autocommit=true, attachment=dn1{INSERT INTO xa_test (id)
VALUES (2)}.0, respHandler=com.actiontech.dble.backend.mysql.nio.handler.transaction.xa.XACommitNodesHandler@124b4fb9, host=localhost, port=3306, statusSync=null, writeQueue=0, modifiedSQLExecuted=false] java.lang.Throwable
  at com.actiontech.dble.backend.mysql.nio.handler.MultiNodeHandler.decrementCountBy(MultiNodeHandler.java:108)
  at com.actiontech.dble.backend.mysql.nio.handler.transaction.xa.XACommitNodesHandler.errorResponse(XACommitNodesHandler.java:314)
  at com.actiontech.dble.backend.mysql.nio.MySQLConnectionHandler.handleErrorPacket(MySQLConnectionHandler.java:198)
  at com.actiontech.dble.backend.mysql.nio.MySQLConnectionHandler.handleData(MySQLConnectionHandler.java:126)
  at com.actiontech.dble.net.handler.BackendAsyncHandler.handleInnerData(BackendAsyncHandler.java:102)
  at com.actiontech.dble.net.handler.BackendAsyncHandler.access$000(BackendAsyncHandler.java:19)
  at com.actiontech.dble.net.handler.BackendAsyncHandler$1.run(BackendAsyncHandler.java:51)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
  at java.lang.Thread.run(Thread.java:748)
```

**Comment by tankilo** [comment]
You should test this issue after merging code from https://github.com/actiontech/dble/issues/1156.

**Comment by Baofengqi** [comment]
@tankilo I will test

**Comment by tankilo** [comment]
Because i mock the `XA COMMIT` with syntax error and 
NonBlockingSession#freshConn don't close the old connection, so after i shut down the mock logic, the XA Transaction still can't be commited successfully.

XACommitNodesHandler#xaOldThreadIds is not the original connection ids anymore.
This problem also results from `NonBlockingSession#freshConn`'s connection leaking problem.
![image](https://user-images.githubusercontent.com/10413284/57187538-1e09ad80-6f23-11e9-857e-571e53dc9f79.png)
![image](https://user-images.githubusercontent.com/10413284/57187539-2366f800-6f23-11e9-8f66-90044785d49e.png)

**Comment by Baofengqi** [comment]
There is no way for tester to reproduce the problem, but we approve first. Check it by auto test environment.

**Comment by wjl1619** [comment]
will observe on the later version continuously
