### ISSUE TITLE
It is recommended that `zk` allow both uppercase and lowercase in the file of sequence_distributed_conf.properties

### ISSUE THREAD

**Issue by FlyingMao** [actiontech/dble#1162]
* **dble version：**  
dble-9.9.9.9-2d18ed6c8dae540e4becc2ba03472b2284238f58-20190429070246
* **preconditions ：**  
no
* **configs：** 

**schema.xml**  

```


```

**rule.xml**  

```


```

**server.xml**  

```


```
**sequence_distributed_conf.properties**
```
INSTANCEID=zk
CLUSTERID=01
```

* **steps：**    
    step1.   start dble
* **expect result：**  
    1. start dble success
* **real result：**  
    1. start dble failed
```
INFO   | jvm 1    | 2019/05/06 06:22:58 | java.lang.NumberFormatException: For input string: "zk"
INFO   | jvm 1    | 2019/05/06 06:22:58 | 	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
INFO   | jvm 1    | 2019/05/06 06:22:58 | 	at java.lang.Long.parseLong(Long.java:589)
INFO   | jvm 1    | 2019/05/06 06:22:58 | 	at java.lang.Long.parseLong(Long.java:631)
INFO   | jvm 1    | 2019/05/06 06:22:58 | 	at com.actiontech.dble.route.sequence.handler.DistributedSequenceHandler.load(DistributedSequenceHandler.java:115)
INFO   | jvm 1    | 2019/05/06 06:22:58 | 	at com.actiontech.dble.config.ServerConfig.loadSequence(ServerConfig.java:554)
INFO   | jvm 1    | 2019/05/06 06:22:58 | 	at com.actiontech.dble.config.ServerConfig.reviseLowerCase(ServerConfig.java:538)
INFO   | jvm 1    | 2019/05/06 06:22:58 | 	at com.actiontech.dble.DbleServer.reviseSchemas(DbleServer.java:242)
INFO   | jvm 1    | 2019/05/06 06:22:58 | 	at com.actiontech.dble.DbleServer.pullVarAndMeta(DbleServer.java:262)
INFO   | jvm 1    | 2019/05/06 06:22:58 | 	at com.actiontech.dble.DbleServer.startup(DbleServer.java:428)
INFO   | jvm 1    | 2019/05/06 06:22:58 | 	at com.actiontech.dble.DbleStartup.main(DbleStartup.java:30)
INFO   | jvm 1    | 2019/05/06 06:22:58 | 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
INFO   | jvm 1    | 2019/05/06 06:22:58 | 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
INFO   | jvm 1    | 2019/05/06 06:22:58 | 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
INFO   | jvm 1    | 2019/05/06 06:22:58 | 	at java.lang.reflect.Method.invoke(Method.java:498)
INFO   | jvm 1    | 2019/05/06 06:22:58 | 	at org.tanukisoftware.wrapper.WrapperSimpleApp.run(WrapperSimpleApp.java:240)
INFO   | jvm 1    | 2019/05/06 06:22:58 | 	at java.lang.Thread.run(Thread.java:748)
STATUS | wrapper  | 2019/05/06 06:23:00 | <-- Wrapper Stopped

```
* **supplements：**  
    1.

/label ~BUG

**Comment by FlyingMao** [comment]
**verified version:** dble-9.9.9.9-d839d393e515ff8cd75a3fa4926d1c0f81ed0534-20190507004646
