### ISSUE TITLE
 An error occurred while using Alibaba Cloud slb load balancing

### ISSUE THREAD

**Issue by banlilin** [actiontech/dble#1172]
* **dble version：**  
     2.19.01.0
* **preconditions ：**  
no
* **configs：** 

**schema.xml**  

```


```

**rule.xml**  

```


```

**server.xml**  

```


```

* **steps：**    
    step1.  Add SLB for load balancing and configure SLB health check
* **expect result：**  
    1.
* **real result：**  
    1.  The following error always appears in the log：
WARN [$_NIO_REACTOR_FRONT-2-RW] (com.actiontech.dble.net.NIOReactor$RW.register(NIOReactor.java:171)) - register err
java.nio.channels.ClosedChannelException: null
        at sun.nio.ch.SocketChannelImpl.ensureReadOpen(SocketChannelImpl.java:257) ~[?:1.8.0_112]
        at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:300) ~[?:1.8.0_112]
        at com.actiontech.dble.net.NIOSocketWR.asyncRead(NIOSocketWR.java:170) ~[dble-2.19.01.0.jar:?]
        at com.actiontech.dble.net.AbstractConnection.asyncRead(AbstractConnection.java:272) ~[dble-2.19.01.0.jar:?]
        at com.actiontech.dble.net.FrontendConnection.register(FrontendConnection.java:454) ~[dble-2.19.01.0.jar:?]
        at com.actiontech.dble.net.NIOReactor$RW.register(NIOReactor.java:164) [dble-2.19.01.0.jar:?]
        at com.actiontech.dble.net.NIOReactor$RW.run(NIOReactor.java:85) [dble-2.19.01.0.jar:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_112]
* **supplements：**  
    1.

/label ~BUG

**Comment by banlilin** [comment]
like this:
https://github.com/MyCATApache/Mycat-Server/issues/1616

**Comment by FlyingMao** [comment]
**verified version：**dble-9.9.9.9-67d04aa94d912fb01583096c6d8cba52f513996e-20190619021040
