### ISSUE TITLE
 Some mysql nodes can't connect, dble fails to start

### ISSUE THREAD

**Issue by FlyingMao** [actiontech/dble#1187]
* **dble version：**  
dble-9.9.9.9-96e76d680afe8eed2f618e28cea390b37dde9ffe-20190517071604
* **preconditions ：**  
no
* **configs：** 

**schema.xml**  

```
<schema dataNode="dn5" name="schema1" sqlMaxLimit="100">
		<table dataNode="dn1,dn2,dn3,dn4" name="test" type="global" />
	</schema>

	<dataNode dataHost="172.100.9.5" database="db1" name="dn1" />
	<dataNode dataHost="172.100.9.6" database="db1" name="dn2" />
	<dataNode dataHost="172.100.9.5" database="db2" name="dn3" />
	<dataNode dataHost="172.100.9.6" database="db2" name="dn4" />
	<dataNode dataHost="172.100.9.5" database="db3" name="dn5" />

	<dataHost balance="0" maxCon="1000" minCon="10" name="172.100.9.5" slaveThreshold="100" switchType="1">
		<heartbeat>select user()</heartbeat>
		<writeHost host="hostM1" password="111111" url="172.100.9.5:3306" user="test">
		</writeHost>
	</dataHost>

	<dataHost balance="0" maxCon="1000" minCon="10" name="172.100.9.6" slaveThreshold="100" switchType="1">
		<heartbeat>select user()</heartbeat>
		<writeHost host="hostM2" password="111111" url="172.100.9.6:3306" user="test">
		</writeHost>
	</dataHost>
```

**rule.xml**  

```


```

**server.xml**  

```


```

* **steps：**    
    step1.  stop one of mysql nodes:172.100.9.5
   step2.  restart dble
* **expect result：**  
    1. restart dble successfully
* **real result：**  
    1. restart dble failed
* **supplements：**  
    1. wrapper.log
```
INFO   | jvm 1    | 2019/05/17 18:51:11 | java.io.IOException: Can't get variables from data node
INFO   | jvm 1    | 2019/05/17 18:51:11 | 	at com.actiontech.dble.DbleServer.pullVarAndMeta(DbleServer.java:258)
INFO   | jvm 1    | 2019/05/17 18:51:11 | 	at com.actiontech.dble.DbleServer.startup(DbleServer.java:428)
INFO   | jvm 1    | 2019/05/17 18:51:11 | 	at com.actiontech.dble.DbleStartup.main(DbleStartup.java:30)
INFO   | jvm 1    | 2019/05/17 18:51:11 | 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
INFO   | jvm 1    | 2019/05/17 18:51:11 | 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
INFO   | jvm 1    | 2019/05/17 18:51:11 | 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
INFO   | jvm 1    | 2019/05/17 18:51:11 | 	at java.lang.reflect.Method.invoke(Method.java:498)
INFO   | jvm 1    | 2019/05/17 18:51:11 | 	at org.tanukisoftware.wrapper.WrapperSimpleApp.run(WrapperSimpleApp.java:240)
INFO   | jvm 1    | 2019/05/17 18:51:11 | 	at java.lang.Thread.run(Thread.java:745)
STATUS | wrapper  | 2019/05/17 18:51:13 | <-- Wrapper Stopped
```

[target.cap.log](https://github.com/actiontech/dble/files/3196225/target.cap.log)
((remove the postfix .log by yourself))

/label ~BUG

**Comment by FlyingMao** [comment]
**verified version：** dble-9.9.9.9-f550057c9db53b039a9620b4bce0f98b81febc23-20190520065617
