### ISSUE TITLE
 Restart dble may fail in zk cluster

### ISSUE THREAD

**Issue by FlyingMao** [actiontech/dble#1212]
* **dble version：**  
dble-9.9.9.9-6bcf8ae52078c320efc8e02798a3e3bb4ddcf1b7-20190528052124
* **preconditions ：**  
The zk cluster contains 3 dbles and both are running normally
* **configs：** 

**schema.xml**  

```


```

**rule.xml**  

```


```

**server.xml**  

```


```

* **steps：**    
    step1.  restart one of dbles(may need to use python script to reproduce)
* **expect result：**  
    1. restart successful
* **real result：**  
    1. restart failed
* **supplements：**  
    1. dble.log
```
INFO   | jvm 1    | 2019/05/28 16:59:45 | java.io.IOException: org.apache.zookeeper.KeeperException$NodeExistsException: KeeperErrorCode = NodeExists for /dble/cluster-1/online/1
INFO   | jvm 1    | 2019/05/28 16:59:45 | 	at com.actiontech.dble.DbleServer.pullVarAndMeta(DbleServer.java:267)
INFO   | jvm 1    | 2019/05/28 16:59:45 | 	at com.actiontech.dble.DbleServer.startup(DbleServer.java:427)
INFO   | jvm 1    | 2019/05/28 16:59:45 | 	at com.actiontech.dble.DbleStartup.main(DbleStartup.java:30)
INFO   | jvm 1    | 2019/05/28 16:59:45 | 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
INFO   | jvm 1    | 2019/05/28 16:59:45 | 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
INFO   | jvm 1    | 2019/05/28 16:59:45 | 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
INFO   | jvm 1    | 2019/05/28 16:59:45 | 	at java.lang.reflect.Method.invoke(Method.java:498)
INFO   | jvm 1    | 2019/05/28 16:59:45 | 	at org.tanukisoftware.wrapper.WrapperSimpleApp.run(WrapperSimpleApp.java:240)
INFO   | jvm 1    | 2019/05/28 16:59:45 | 	at java.lang.Thread.run(Thread.java:745)
INFO   | jvm 1    | 2019/05/28 16:59:45 | Caused by: org.apache.zookeeper.KeeperException$NodeExistsException: KeeperErrorCode = NodeExists for /dble/cluster-1/online/1
INFO   | jvm 1    | 2019/05/28 16:59:45 | 	at org.apache.zookeeper.KeeperException.create(KeeperException.java:119)
INFO   | jvm 1    | 2019/05/28 16:59:45 | 	at org.apache.zookeeper.KeeperException.create(KeeperException.java:51)
INFO   | jvm 1    | 2019/05/28 16:59:45 | 	at org.apache.zookeeper.ZooKeeper.create(ZooKeeper.java:783)
INFO   | jvm 1    | 2019/05/28 16:59:45 | 	at org.apache.curator.framework.imps.CreateBuilderImpl$11.call(CreateBuilderImpl.java:735)
INFO   | jvm 1    | 2019/05/28 16:59:45 | 	at org.apache.curator.framework.imps.CreateBuilderImpl$11.call(CreateBuilderImpl.java:718)
INFO   | jvm 1    | 2019/05/28 16:59:45 | 	at org.apache.curator.RetryLoop.callWithRetry(RetryLoop.java:108)
INFO   | jvm 1    | 2019/05/28 16:59:45 | 	at org.apache.curator.framework.imps.CreateBuilderImpl.pathInForeground(CreateBuilderImpl.java:714)
INFO   | jvm 1    | 2019/05/28 16:59:45 | 	at org.apache.curator.framework.imps.CreateBuilderImpl.protectedPathInForeground(CreateBuilderImpl.java:484)
INFO   | jvm 1    | 2019/05/28 16:59:45 | 	at org.apache.curator.framework.imps.CreateBuilderImpl.forPath(CreateBuilderImpl.java:474)
INFO   | jvm 1    | 2019/05/28 16:59:45 | 	at org.apache.curator.framework.imps.CreateBuilderImpl.forPath(CreateBuilderImpl.java:454)
INFO   | jvm 1    | 2019/05/28 16:59:45 | 	at org.apache.curator.framework.imps.CreateBuilderImpl.forPath(CreateBuilderImpl.java:44)
INFO   | jvm 1    | 2019/05/28 16:59:45 | 	at com.actiontech.dble.util.ZKUtils.createTempNode(ZKUtils.java:103)
INFO   | jvm 1    | 2019/05/28 16:59:45 | 	at com.actiontech.dble.util.ZKUtils.createTempNode(ZKUtils.java:94)
INFO   | jvm 1    | 2019/05/28 16:59:45 | 	at com.actiontech.dble.meta.ProxyMetaManager.metaZKinit(ProxyMetaManager.java:332)
INFO   | jvm 1    | 2019/05/28 16:59:45 | 	at com.actiontech.dble.meta.ProxyMetaManager.init(ProxyMetaManager.java:292)
INFO   | jvm 1    | 2019/05/28 16:59:45 | 	at com.actiontech.dble.DbleServer.pullVarAndMeta(DbleServer.java:265)
INFO   | jvm 1    | 2019/05/28 16:59:45 | 	... 8 more
STATUS | wrapper  | 2019/05/28 16:59:47 | <-- Wrapper Stopped

```

**Comment by FlyingMao** [comment]
**verified version：** dble-9.9.9.9-d8a5c79cc4efda58659d7990340fde23777a1558-20190903023556
