### ISSUE TITLE
Even if the transaction is successfully restored, the state of the xa transaction in xalog will always fail

### ISSUE THREAD

**Issue by FlyingMao** [actiontech/dble#1213]
* **dble version：**  
dble-9.9.9.9-d315da93cfb4d4520b189e0cb7878d22555192d1-20190528071502
* **preconditions ：**  
```
create table sharding_4_t1(id int,name char);
```
* **configs：** 

**schema.xml**  

```
<schema name="schema1" sqlMaxLimit="100">
<table name="sharding_4_t1" dataNode="dn1,dn2,dn3,dn4" rule="hash-four" />
</schema>
    <dataNode name="dn1" dataHost="10.186.65.64" database="db1"/>
    <dataNode name="dn2" dataHost="10.186.65.65" database="db1"/>
    <dataNode name="dn3" dataHost="10.186.65.64" database="db2"/>
    <dataNode name="dn4" dataHost="10.186.65.65" database="db2"/>
```

**rule.xml**  

```


```

**server.xml**  

```


```

* **steps：**    
    step1.  use btrace to hang 20s at "delayBeforeXaCommit" and "beforeAddXaToQueue"
```
package com.actiontech.dble.btrace.script;

import com.sun.btrace.BTraceUtils;
import com.sun.btrace.annotations.BTrace;
import com.sun.btrace.annotations.OnMethod;

@BTrace(unsafe = true)
public final class BtraceXaDelay {

    private BtraceXaDelay() {

    }
    @OnMethod(
            clazz = "com.actiontech.dble.btrace.provider.XaDelayProvider",
            method = "delayBeforeXaCommit"
    )
    public static void delayBeforeXaCommit(String rrnName, String xaId) throws Exception {
        BTraceUtils.println("before xa commit " + xaId + " in " + rrnName);
        Thread.sleep(20000L);
    }
    @OnMethod(
            clazz = "com.actiontech.dble.btrace.provider.XaDelayProvider",
            method = "beforeAddXaToQueue"
    )
    public static void beforeAddXaToQueue(int count, String xaId) throws Exception {
        BTraceUtils.println("before add xa " + xaId + " to queue in " + count + " time.");
        Thread.sleep(20000L);
    }
}
```
step2. execute xa in dble
```
mysql> set autocommit=0;
mysql> set xa=on;
mysql> insert into sharding_4_t1 values(1,1),(2,2),(3,3),(4,4);
mysql> commit;
```
step3. stop one of the mysql node when btrace prints "before xa commit ..."
step4. stop dble when btrace prints "before add xa..."
step5. Restart the stopped mysql
step6. restart dble
* **expect result：**  
    1.  restart dble successfully
* **real result：**  
    1. restart dble failed
* **supplements：**  
    1. wrapper.log
```
INFO   | jvm 1    | 2019/05/29 07:02:07 | Wrapper (Version 3.2.3) http://wrapper.tanukisoftware.org
INFO   | jvm 1    | 2019/05/29 07:02:07 |   Copyright 1999-2006 Tanuki Software, Inc.  All Rights Reserved.
INFO   | jvm 1    | 2019/05/29 07:02:07 | 
INFO   | jvm 1    | 2019/05/29 07:02:09 | java.lang.RuntimeException: Fail to recover xa when dble start, please check backend mysql.
INFO   | jvm 1    | 2019/05/29 07:02:09 | 	at com.actiontech.dble.DbleServer.tryRecovery(DbleServer.java:1041)
INFO   | jvm 1    | 2019/05/29 07:02:09 | 	at com.actiontech.dble.DbleServer.performXARecoveryLog(DbleServer.java:999)
INFO   | jvm 1    | 2019/05/29 07:02:09 | 	at com.actiontech.dble.DbleServer.startup(DbleServer.java:447)
INFO   | jvm 1    | 2019/05/29 07:02:09 | 	at com.actiontech.dble.DbleStartup.main(DbleStartup.java:30)
INFO   | jvm 1    | 2019/05/29 07:02:09 | 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
INFO   | jvm 1    | 2019/05/29 07:02:09 | 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
INFO   | jvm 1    | 2019/05/29 07:02:09 | 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
INFO   | jvm 1    | 2019/05/29 07:02:09 | 	at java.lang.reflect.Method.invoke(Method.java:498)
INFO   | jvm 1    | 2019/05/29 07:02:09 | 	at org.tanukisoftware.wrapper.WrapperSimpleApp.run(WrapperSimpleApp.java:240)
INFO   | jvm 1    | 2019/05/29 07:02:09 | 	at java.lang.Thread.run(Thread.java:748)
STATUS | wrapper  | 2019/05/29 07:02:11 | <-- Wrapper Stopped
```

2. xalog
```
{"id":"'Dble_Server.1.2'","state":"5","participants":[{"host":"10.186.65.64","port":"3306","p_state":"5","expires":0,"schema":"db2"},{"host":"10.186.65.65","port":"3306","p_state":"8","expires":0,"schema":"db1"},{"host":"10.186.65.65","port":"3306","p_state":"8","expires":0,"schema":"db2"},{"host":"10.186.65.64","port":"3306","p_state":"8","expires":0,"schema":"db1"}]}

```

**Comment by FlyingMao** [comment]
#1113

**Comment by FlyingMao** [comment]
**verified version：** dble-9.9.9.9-dd8915f83140702436f40ace4fd2a9de258d2a38-20190530071236
