### ISSUE TITLE
SqlJob may finish more than once,and cause other problem

### ISSUE THREAD

**Issue by sunsun314** [actiontech/dble#1231]
* **dble version：**  2.19.01.0/rel
* **configs：** 

**schema.xml**  
```
 <schema name="testdb" dataNode="dn1"/>
```
**server.xml**
```
        <property name="checkTableConsistency">0</property>
        <!-- check periodt, he default period is 60000 milliseconds -->
        <property name="checkTableConsistencyPeriod">600000000</property>
        <!-- 1 check the consistency of global table, 0 is not -->
        <property name="useGlobleTableCheck">0</property>
        <property name="glableTableCheckPeriod">86400000</property>

        <!-- heartbeat check period -->
        <property name="dataNodeIdleCheckPeriod">300000000</property>
        <property name="dataNodeHeartbeatPeriod">10000000</property>

```
* **steps：**    
  step1.  stop dble all timed tasks use server.xml
  step2. Add Btrace script delay in com.actiontech.dble.sqlengine.OneRawSQLQueryResultHandler#finished 30s
    Add Btrace script delay in com.actiontech.dble.backend.mysql.nio.MySQLConnection.release 60s
  step3. create table test1(id int,name varchar(20))
  step4. close backconnection in 30s
  step5. wait for the log in Btrace
* **expect result：**  
    SqlJob.finish function sould only be called once
* **real result：**  
    SqlJob.finish can be called more than once
* **supplements：**  
    This issue of SqlJob can cause more problem,such as the tableMeta hang,with exception as below
```
2019-06-11 10:35:08.693  INFO [complexQueryExecutor95] (com.actiontech.dble.backend.mysql.nio.MySQLConnectionHandler.handleDataError(MySQLConnectionHandler.java:233)) - MySQLConnection [id=30, lastTime=1560249308616, user=root, schema=db2, old schema=db2, borrowed=false, fromSlaveDB=false, threadId=3339,character_set_client=utf8,character_set_results=utf8,collation_connection=utf8_general_ci, txIsolation=-1, autocommit=true, attachment=null, respHandler=null, host=172.20.134.2, port=3308, statusSync=null, writeQueue=0, modifiedSQLExecuted=false] handle data error:
java.lang.NullPointerException: null
	at java.util.LinkedList$ListItr.next(LinkedList.java:893) ~[?:1.8.0_121]
	at com.actiontech.dble.meta.table.old.AbstractTableMetaHandler$MySQLTableStructureListener.consistentWarning(AbstractTableMetaHandler.java:177) ~[dble-2.19.01.0.jar:?]
	at com.actiontech.dble.meta.table.old.AbstractTableMetaHandler$MySQLTableStructureListener.genTableMeta(AbstractTableMetaHandler.java:152) ~[dble-2.19.01.0.jar:?]
	at com.actiontech.dble.meta.table.old.AbstractTableMetaHandler$MySQLTableStructureListener.onResult(AbstractTableMetaHandler.java:134) ~[dble-2.19.01.0.jar:?]
	at com.actiontech.dble.meta.table.old.AbstractTableMetaHandler$MySQLTableStructureListener.onResult(AbstractTableMetaHandler.java:81) ~[dble-2.19.01.0.jar:?]
	at com.actiontech.dble.sqlengine.OneRawSQLQueryResultHandler.finished(OneRawSQLQueryResultHandler.java:88) ~[dble-2.19.01.0.jar:?]
	at com.actiontech.dble.sqlengine.SQLJob.doFinished(SQLJob.java:107) ~[dble-2.19.01.0.jar:?]
	at com.actiontech.dble.sqlengine.SQLJob.rowEofResponse(SQLJob.java:172) ~[dble-2.19.01.0.jar:?]
	at com.actiontech.dble.backend.mysql.nio.MySQLConnectionHandler.handleRowEofPacket(MySQLConnectionHandler.java:225) ~[dble-2.19.01.0.jar:?]
	at com.actiontech.dble.backend.mysql.nio.MySQLConnectionHandler.handleData(MySQLConnectionHandler.java:127) [dble-2.19.01.0.jar:?]
	at com.actiontech.dble.net.handler.BackendAsyncHandler.handleInnerData(BackendAsyncHandler.java:102) ~[dble-2.19.01.0.jar:?]
	at com.actiontech.dble.net.handler.BackendAsyncHandler.access$000(BackendAsyncHandler.java:19) ~[dble-2.19.01.0.jar:?]
	at com.actiontech.dble.net.handler.BackendAsyncHandler$1.run(BackendAsyncHandler.java:51) [dble-2.19.01.0.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_121]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
```
https://github.com/actiontech/dble/pull/1223 fix this in 2.19.05.0

**Comment by sunsun314** [comment]
need be verified in 2.19.03.1/rel

**Comment by wjl1619** [comment]
verified on version: 5.6.29-dble-2.19.03.1-fcf9eb808ec1821ce315a73dce327157d5f92b2c-20190613093124
