### ISSUE TITLE
Error,use mysql node authentication instead of user-level authentication when authenticating users

### ISSUE THREAD

**Issue by FlyingMao** [actiontech/dble#1235]
* **dble version：**  
dble-9.9.9.9-42aeaab7fc3d719a8e918dce18176909ed35b340-20190610120741
* **preconditions ：**  
mysql version:8.0 (
If you use a version below 8.0, there will be differences in the commands for creating users.)
* **configs：** 

**schema.xml**  

```
        <schema name="schema1" sqlMaxLimit="100">
		<table dataNode="dn1,dn2" name="test" type="global" />
	</schema>

	<dataNode dataHost="172.100.9.5" database="db1" name="dn1" />
	<dataNode dataHost="172.100.9.5" database="db2" name="dn2" />

	<dataHost balance="0" maxCon="1000" minCon="10" name="172.100.9.5" slaveThreshold="100" switchType="1">
		<heartbeat>select user()</heartbeat>
		<writeHost host="hostM1" password="test" url="172.100.9.5:8001" user="test2">
		</writeHost>
	</dataHost>

```

**rule.xml**  

```


```

**server.xml**  

```


```

* **steps：**    
    step1.  create user `test2` in mysql node when  default_authentication_plugin= `mysql_native_password`
```
mysql> CREATE USER `test2`@`%` IDENTIFIED BY 'test';
Query OK, 0 rows affected (0.03 sec)

mysql> GRANT ALL ON *.* TO `test2`@`%` WITH GRANT OPTION; 
Query OK, 0 rows affected (0.10 sec)

mysql> SELECT user,host,plugin from mysql.user where user='test2';
+-------+------+-----------------------+
| user  | host | plugin                |
+-------+------+-----------------------+
| test2 | %    | mysql_native_password |
+-------+------+-----------------------+
1 row in set (0.00 sec)
```
step2. change default_authentication_plugin= `sha256_password` in my.cnf and restart mysql node
```
[mysqld]
default_authentication_plugin=sha256_password
```
step3. start dble
* **expect result：**  
    1. start dble successful
* **real result：**  
    1. start dble failed
```
INFO   | jvm 1    | 2019/06/12 10:08:37 | java.io.IOException: Can't get variables from data node
INFO   | jvm 1    | 2019/06/12 10:08:37 | 	at com.actiontech.dble.DbleServer.pullVarAndMeta(DbleServer.java:256)
INFO   | jvm 1    | 2019/06/12 10:08:37 | 	at com.actiontech.dble.DbleServer.startup(DbleServer.java:427)
INFO   | jvm 1    | 2019/06/12 10:08:37 | 	at com.actiontech.dble.DbleStartup.main(DbleStartup.java:30)
INFO   | jvm 1    | 2019/06/12 10:08:37 | 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
INFO   | jvm 1    | 2019/06/12 10:08:37 | 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
INFO   | jvm 1    | 2019/06/12 10:08:37 | 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
INFO   | jvm 1    | 2019/06/12 10:08:37 | 	at java.lang.reflect.Method.invoke(Method.java:498)
INFO   | jvm 1    | 2019/06/12 10:08:37 | 	at org.tanukisoftware.wrapper.WrapperSimpleApp.run(WrapperSimpleApp.java:240)
INFO   | jvm 1    | 2019/06/12 10:08:37 | 	at java.lang.Thread.run(Thread.java:748)
STATUS | wrapper  | 2019/06/12 10:08:40 | <-- Wrapper Stopped
```
* **supplements：**  
    1. If you have other mysql nodes that can be connected, dble will start successfully, but executing sql will result in an error
```
mysql> use schema1;
Database changed
mysql> drop table test;
ERROR 1152 (HY000): java.lang.RuntimeException: Client don't support the password plugin sha256_password,please check the default auth Plugin
```

**Comment by FlyingMao** [comment]
#1134

**Comment by yanhuqing666** [comment]
not a bug
