### ISSUE TITLE
manager cmd "create database" error when connect to dble with JDBC

### ISSUE THREAD

**Issue by yexiaoli88** [actiontech/dble#1245]
* **dble version：5.6.29-dble-9.9.9.9-67d04aa94d912fb01583096c6d8cba52f513996e-20190619021040**  

**schema.xml**  
set minCon=the num of dataNodes, see follows
```
<dble:schema xmlns:dble="http://dble.cloud/">
    <schema name="testdb" sqlMaxLimit="100" dataNode="dn4">
        <table name="a_test" dataNode="dn1,dn2,dn3,dn4" rule="hash-four"/>
    </schema>
    <dataNode name="dn1" dataHost="localhost1" database="db1"/>
    <dataNode name="dn2" dataHost="localhost1" database="db2"/>
    <dataNode name="dn3" dataHost="localhost1" database="db3"/>
    <dataNode name="dn4" dataHost="localhost1" database="db4"/>
    <dataHost balance="0" maxCon="1000" minCon="4" name="localhost1" switchType="1" slaveThreshold="100">
        <heartbeat>select user()</heartbeat>
        <writeHost host="hostM1" url="10.186.61.87:3306" password="123" user="root"/>
    </dataHost>
</dble:schema>
```
* **steps：**    
1. restart dble

2.execute java code immediatly after restarting dble
```
public class JDBCTest {

    static final String JDBC_DRIVER = "com.mysql.jdbc.Driver";  
    static final String DB_URL = "jdbc:mysql://10.186.61.87:9066/testdb";
 
    static final String USER = "root";
    static final String PASS = "123";
 
    public static void main(String[] args) {
        Connection conn = null;
        Statement stmt = null;
        try{
            Class.forName("com.mysql.jdbc.Driver");
        
            System.out.println("connecting...");
            conn = DriverManager.getConnection(DB_URL,USER,PASS);
      
            stmt =  conn.createStatement();
            String sql = "create database @@dataNode='dn1,dn2,dn3,dn4'";
            stmt.execute(sql);
            stmt.close();
            conn.close();
        }catch(SQLException se){
            se.printStackTrace();
        }catch(Exception e){
            e.printStackTrace();
        }finally{
            try{
                if(stmt!=null) stmt.close();
            }catch(SQLException se2){
            }
            try{
                if(conn!=null) conn.close();
            }catch(SQLException se){
                se.printStackTrace();
            }
        }
        System.out.println("close!");
    }

}

```
* **expect result：**  
 1.step 2 execute succuessful
 2.databases be created successful
* **real result：**  
1.step2 return err:
```
java.sql.SQLException: create database error in [dn1]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1094)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4226)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4158)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2615)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2776)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2834)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2783)
	at com.mysql.jdbc.StatementImpl.execute(StatementImpl.java:908)
	at com.mysql.jdbc.StatementImpl.execute(StatementImpl.java:788)
	at JDBCTest.main(JDBCTest.java:25)

```
2.related dble.log:
```
2019-06-26 17:45:17.863  INFO [$_NIO_REACTOR_BACKEND-1-RW] (com.actiontech.dble.backend.mysql.nio.handler.GetConnectionHandler.connectionError(GetConnectionHandler.java:60)) - connect error
 MySQLConnection [id=5, lastTime=1561542317552, user=root, schema=db2, old schema=null, borrowed=false, fromSlaveDB=false, threadId=2982,character_set_client=utf8mb4,character_set_results=u
tf8mb4,collation_connection=utf8mb4_general_ci, txIsolation=-1, autocommit=true, attachment=null, respHandler=null, host=10.186.61.87, port=3306, statusSync=null, writeQueue=0, modifiedSQLE
xecuted=false]ConnectionException [code=1049, msg=Unknown database 'db2']
2019-06-26 17:45:17.863  INFO [$_NIO_REACTOR_BACKEND-0-RW] (com.actiontech.dble.backend.mysql.nio.handler.GetConnectionHandler.connectionError(GetConnectionHandler.java:60)) - connect error
 MySQLConnection [id=4, lastTime=1561542317552, user=root, schema=db4, old schema=null, borrowed=false, fromSlaveDB=false, threadId=2984,character_set_client=utf8mb4,character_set_results=u
tf8mb4,collation_connection=utf8mb4_general_ci, txIsolation=-1, autocommit=true, attachment=null, respHandler=null, host=10.186.61.87, port=3306, statusSync=null, writeQueue=0, modifiedSQLE
xecuted=false]ConnectionException [code=1049, msg=Unknown database 'db4']
2019-06-26 17:45:17.863  INFO [$_NIO_REACTOR_BACKEND-2-RW] (com.actiontech.dble.backend.mysql.nio.handler.GetConnectionHandler.connectionError(GetConnectionHandler.java:60)) - connect error
 MySQLConnection [id=2, lastTime=1561542317552, user=root, schema=db1, old schema=null, borrowed=false, fromSlaveDB=false, threadId=2983,character_set_client=utf8mb4,character_set_results=u
tf8mb4,collation_connection=utf8mb4_general_ci, txIsolation=-1, autocommit=true, attachment=null, respHandler=null, host=10.186.61.87, port=3306, statusSync=null, writeQueue=0, modifiedSQLE
xecuted=false]ConnectionException [code=1049, msg=Unknown database 'db1']
2019-06-26 17:45:17.864  INFO [$_NIO_REACTOR_BACKEND-3-RW] (com.actiontech.dble.backend.mysql.nio.handler.GetConnectionHandler.connectionError(GetConnectionHandler.java:60)) - connect error
 MySQLConnection [id=3, lastTime=1561542317552, user=root, schema=db3, old schema=null, borrowed=false, fromSlaveDB=false, threadId=2981,character_set_client=utf8mb4,character_set_results=u
tf8mb4,collation_connection=utf8mb4_general_ci, txIsolation=-1, autocommit=true, attachment=null, respHandler=null, host=10.186.61.87, port=3306, statusSync=null, writeQueue=0, modifiedSQLE
xecuted=false]ConnectionException [code=1049, msg=Unknown database 'db3']
2019-06-26 17:45:17.952  INFO [WrapperSimpleAppMain] (com.actiontech.dble.backend.datasource.PhysicalDBPool.initSource(PhysicalDBPool.java:414)) - init result :finished 5 success 0 target c
ount:5
2019-06-26 17:45:17.952  INFO [WrapperSimpleAppMain] (com.actiontech.dble.backend.datasource.PhysicalDBPool.init(PhysicalDBPool.java:327)) - localhost1 index:0 init success
2019-06-26 17:45:17.952  INFO [WrapperSimpleAppMain] (com.actiontech.dble.DbleServer.pullVarAndMeta(DbleServer.java:262)) - get variables Data end
2019-06-26 17:45:17.952  INFO [WrapperSimpleAppMain] (com.actiontech.dble.meta.ProxyMetaManager.init(ProxyMetaManager.java:290)) - init metaData start
2019-06-26 17:45:17.960  INFO [complexQueryExecutor2] (com.actiontech.dble.sqlengine.SQLJob.errorResponse(SQLJob.java:127)) - error response errNo:1049, Unknown database 'db4' from of sql :
show full tables where Table_type ='BASE TABLE'  at con:MySQLConnection [id=1, lastTime=1561542317552, user=root, schema=db4, old schema=null, borrowed=true, fromSlaveDB=false, threadId=298
0,character_set_client=utf8mb4,character_set_results=utf8mb4,collation_connection=utf8mb4_general_ci, txIsolation=-1, autocommit=true, attachment=null, respHandler=SQLJob [dataNode=null,sch
ema=db4,sql=show full tables where Table_type ='BASE TABLE' ,  jobHandler=com.actiontech.dble.sqlengine.MultiRowSQLQueryResultHandler@4e6c9f95], host=10.186.61.87, port=3306, statusSync=com
.actiontech.dble.backend.mysql.nio.MySQLConnection$StatusSync@40ab7828, writeQueue=0, modifiedSQLExecuted=false]
2019-06-26 17:45:17.961  WARN [complexQueryExecutor2] (com.actiontech.dble.meta.table.GetNodeTablesHandler$MySQLShowTablesListener.onResult(GetNodeTablesHandler.java:76)) - Can't show table
s from DataNode:dn4! Maybe the data node is not initialized!
2019-06-26 17:45:17.963  INFO [WrapperSimpleAppMain] (com.actiontech.dble.backend.datasource.PhysicalDatasource.getConnection(PhysicalDatasource.java:386)) - no idle connection in pool,crea
te new connection for hostM1 of schema db1
2019-06-26 17:45:17.966  WARN [$_NIO_REACTOR_BACKEND-2-RW] (com.actiontech.dble.backend.mysql.nio.MySQLConnectionAuthenticator.handle(MySQLConnectionAuthenticator.java:86)) - can't connect 
to mysql server ,errMsg:Unknown database 'db1' MySQLConnection [id=6, lastTime=1561542317552, user=root, schema=db1, old schema=null, borrowed=false, fromSlaveDB=false, threadId=2985,charac
ter_set_client=utf8mb4,character_set_results=utf8mb4,collation_connection=utf8mb4_general_ci, txIsolation=-1, autocommit=true, attachment=null, respHandler=null, host=10.186.61.87, port=330
6, statusSync=null, writeQueue=0, modifiedSQLExecuted=false]
2019-06-26 17:45:17.966  WARN [$_NIO_REACTOR_BACKEND-2-RW] (com.actiontech.dble.backend.mysql.nio.MySQLConnectionAuthenticator.handle(MySQLConnectionAuthenticator.java:126)) - null
2019-06-26 17:45:17.966  WARN [$_NIO_REACTOR_BACKEND-2-RW] (com.actiontech.dble.sqlengine.SQLJob.connectionError(SQLJob.java:115)) - can't get connection for sql :show full tables where Tab
le_type ='BASE TABLE' 
com.actiontech.dble.net.ConnectionException: null
        at com.actiontech.dble.backend.mysql.nio.MySQLConnectionAuthenticator.handle(MySQLConnectionAuthenticator.java:88) [dble-9.9.9.9.jar:?]
        at com.actiontech.dble.net.AbstractConnection.handle(AbstractConnection.java:259) [dble-9.9.9.9.jar:?]
        at com.actiontech.dble.net.AbstractConnection.onReadData(AbstractConnection.java:318) [dble-9.9.9.9.jar:?]
        at com.actiontech.dble.net.NIOSocketWR.asyncRead(NIOSocketWR.java:230) [dble-9.9.9.9.jar:?]
        at com.actiontech.dble.net.AbstractConnection.asyncRead(AbstractConnection.java:269) [dble-9.9.9.9.jar:?]
        at com.actiontech.dble.net.NIOReactor$RW.executeKeys(NIOReactor.java:120) [dble-9.9.9.9.jar:?]
        at com.actiontech.dble.net.NIOReactor$RW.run(NIOReactor.java:91) [dble-9.9.9.9.jar:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]

```
* **supplements：**  
    1. step2 success while waiting a moment to execute after restarting dble

**Comment by FlyingMao** [comment]
**verified version：** dble-9.9.9.9-16ae8083a9edeb67ab102cded51446e27d7ee2f5-20190627073912
