### ISSUE TITLE
Error when execute ’select a.id,b.* from test2 a inner join test1 b on a.id =b.id+1;‘

### ISSUE THREAD

**Issue by newskyddm** [actiontech/dble#1255]
* **dble version：2.19.05.0
* **preconditions ：**  
no
* **configs：** 

**schema.xml**  
    <schema name="TESTDB" dataNode="dn1">

        <table name="test1" dataNode="dn1,dn2,dn3,dn4" rule="sharding-by-mod4"/>
        <table name="test2" dataNode="dn1,dn2" rule="sharding-by-mod2"/>
```


```

**rule.xml**  

```
    <tableRule name="sharding-by-mod4">
        <rule>
            <columns>id</columns>
            <algorithm>hashmod4</algorithm>
        </rule>
    </tableRule>

	<tableRule name="sharding-by-mod2">
        <rule>
            <columns>id</columns>
            <algorithm>hashmod2</algorithm>
        </rule>
    </tableRule>

  <function name="hashmod4" class="Hash">
        <property name="partitionCount">4</property>
        <property name="partitionLength">1</property>
    </function>
    <function name="hashmod2" class="Hash">
        <property name="partitionCount">2</property>
        <property name="partitionLength">1</property>
    </function>
```

**server.xml**  

```


```

* **steps：**    
    step1.  execute sql using mysql client
select a.id,b.* from test2 a inner join test1 b on a.id =b.id+1;

* **expect result：**  
    1. execute successfully

* **real result：**  
    1.
mysql> select a.id,b.* from test2 a inner join test1 b on a.id =b.id+1;
ERROR 1003 (HY000): field not found:b.id + 1

* **supplements：**  
    1. explain result

mysql> explain select a.id,b.* from test2 a inner join test1 b on a.id =b.id+1;
+-------------------+-----------------+---------------------------------------------------------------------------------------+
| DATA_NODE         | TYPE            | SQL/REF                                                                               |
+-------------------+-----------------+---------------------------------------------------------------------------------------+
| dn1_0             | BASE SQL        | select `a`.`id` from  `test2` `a` ORDER BY `a`.`id` ASC                               |
| dn2_0             | BASE SQL        | select `a`.`id` from  `test2` `a` ORDER BY `a`.`id` ASC                               |
| merge_and_order_1 | MERGE_AND_ORDER | dn1_0; dn2_0                                                                          |
| shuffle_field_1   | SHUFFLE_FIELD   | merge_and_order_1                                                                     |
| dn1_1             | BASE SQL        | select `b`.`id`,`b`.`name`,b.id + 1 as `rpda_0` from  `test1` `b` ORDER BY rpda_0 ASC |
| dn2_1             | BASE SQL        | select `b`.`id`,`b`.`name`,b.id + 1 as `rpda_0` from  `test1` `b` ORDER BY rpda_0 ASC |
| dn3_0             | BASE SQL        | select `b`.`id`,`b`.`name`,b.id + 1 as `rpda_0` from  `test1` `b` ORDER BY rpda_0 ASC |
| dn4_0             | BASE SQL        | select `b`.`id`,`b`.`name`,b.id + 1 as `rpda_0` from  `test1` `b` ORDER BY rpda_0 ASC |
| merge_and_order_2 | MERGE_AND_ORDER | dn1_1; dn2_1; dn3_0; dn4_0                                                            |
| shuffle_field_3   | SHUFFLE_FIELD   | merge_and_order_2                                                                     |
| join_1            | JOIN            | shuffle_field_1; shuffle_field_3                                                      |
| shuffle_field_2   | SHUFFLE_FIELD   | join_1                                                                                |
+-------------------+-----------------+---------------------------------------------------------------------------------------+
12 rows in set (0.03 sec)

2、dble log

2019-07-08 23:03:44,371 [INFO ][complexQueryExecutor55] MySQLConnection [id=13, lastTime=1562598224364, user=root, schema=dble2, old schema=dble2, borrowed=true, fromSlaveDB=false, threadId=20525,character_set_client=utf8,character_set_results=utf8,collation_connection=utf8_general_ci, txIsolation=3, autocommit=true, attachment=dn2{select `b`.`id`,`b`.`name`,b.id + 1 as `rpda_0` from  `test1` `b` ORDER BY rpda_0 ASC}.1, respHandler=com.actiontech.dble.backend.mysql.nio.handler.query.impl.BaseSelectHandler@3ae20d2a, host=localhost, port=3306, statusSync=null, writeQueue=0, modifiedSQLExecuted=false] handle data error: com.actiontech.dble.plan.common.exception.MySQLOutPutException: field not found:b.id + 1
	at com.actiontech.dble.backend.mysql.nio.handler.util.HandlerTool.createFieldItem(HandlerTool.java:266)
	at com.actiontech.dble.backend.mysql.nio.handler.util.HandlerTool.createItem(HandlerTool.java:98)
	at com.actiontech.dble.backend.mysql.nio.handler.util.RowDataComparator.createOrderItem(RowDataComparator.java:91)
	at com.actiontech.dble.backend.mysql.nio.handler.util.RowDataComparator.<init>(RowDataComparator.java:45)
	at com.actiontech.dble.backend.mysql.nio.handler.query.impl.join.JoinHandler.fieldEofResponse(JoinHandler.java:99)
	at com.actiontech.dble.backend.mysql.nio.handler.query.impl.SendMakeHandler.fieldEofResponse(SendMakeHandler.java:85)
	at com.actiontech.dble.backend.mysql.nio.handler.query.impl.MultiNodeMergeAndOrderHandler.fieldEofResponse(MultiNodeMergeAndOrderHandler.java:85)
	at com.actiontech.dble.backend.mysql.nio.handler.query.impl.BaseSelectHandler.fieldEofResponse(BaseSelectHandler.java:109)
	at com.actiontech.dble.backend.mysql.nio.MySQLConnectionHandler.handleFieldEofPacket(MySQLConnectionHandler.java:193)
	at com.actiontech.dble.backend.mysql.nio.MySQLConnectionHandler.handleData(MySQLConnectionHandler.java:115)
	at com.actiontech.dble.net.handler.BackendAsyncHandler.handleInnerData(BackendAsyncHandler.java:102)
	at com.actiontech.dble.net.handler.BackendAsyncHandler.access$000(BackendAsyncHandler.java:19)
	at com.actiontech.dble.net.handler.BackendAsyncHandler$1.run(BackendAsyncHandler.java:51)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
 (com.actiontech.dble.backend.mysql.nio.MySQLConnectionHandler:MySQLConnectionHandler.java:237)

**Comment by wjl1619** [comment]
verified on version:  5.6.29-dble-9.9.9.9-3973be7c76d1c0fc2f285a75c4218c27e57febe2-20190725053413
