### ISSUE TITLE
reload @@config gets NPE when appendding a table with datanode useless before

### ISSUE THREAD

**Issue by irene-coming** [actiontech/dble#1267]
* **dble version：**  
5.6.29-dble-9.9.9.9-8fb726b120caf25a44f7c9d8d2b7cd0dab249dc0-20190717054448
* **preconditions ：**  

* **configs：** 

**schema.xml**  

```
        <schema name="schema1" sqlMaxLimit="100">
                <table dataNode="dn1" name="test" type="global" />
        </schema>
        <dataNode dataHost="172.100.9.5" database="db1" name="dn1" />
        <dataNode dataHost="172.100.9.5" database="db2" name="dn2" />
```

**rule.xml**  

```
     <tableRule name="hash-two">
        <rule>
            <columns>id</columns>
            <algorithm>two-long</algorithm>
        </rule>
    </tableRule>
    <function class="Hash" name="two-long">
        <property name="partitionCount">2</property>
        <property name="partitionLength">1</property>
    </function>
```

**server.xml**  

```


```

* **steps：**    
    step1. start dble without error
    step2.  update schema.xml appendding:
```xml
<table name="sharding_2_t1" dataNode="dn1,dn2" rule="hash-two" />  
``` 
    step3. loggin dble manager port, and execute :
```mysql
mysql> reload @@config;
ERROR 1003 (HY000): Reload config failure.The reason is java.lang.NullPointerException
```
* **expect result：**  
    1.step3 reload @@config success
* **real result：**  
    1.step3 reload @@config gets NPE
* **supplements：**  
    1.dble.log related error:
```log4j
2019-07-18 03:07:49.899  INFO [BusinessExecutor0] (com.actiontech.dble.manager.response.ReloadConfig.execute(ReloadConfig.java:131)) - reload error
java.lang.NullPointerException: null
        at com.actiontech.dble.meta.table.GetNodeTablesHandler.execute(GetNodeTablesHandler.java:41) ~[dble-9.9.9.9.jar:?]
        at com.actiontech.dble.meta.table.AbstractTablesMetaHandler.listExistTables(AbstractTablesMetaHandler.java:78) ~[dble-9.9.9.9.jar:?]
        at com.actiontech.dble.meta.table.AbstractTablesMetaHandler.execute(AbstractTablesMetaHandler.java:53) ~[dble-9.9.9.9.jar:?]
        at com.actiontech.dble.meta.table.MultiTablesMetaHandler.execute(MultiTablesMetaHandler.java:95) ~[dble-9.9.9.9.jar:?]
        at com.actiontech.dble.meta.table.MultiTablesInitMetaHandler.execute(MultiTablesInitMetaHandler.java:30) ~[dble-9.9.9.9.jar:?]
        at com.actiontech.dble.meta.table.SchemaMetaHandler.execute(SchemaMetaHandler.java:77) ~[dble-9.9.9.9.jar:?]
        at com.actiontech.dble.meta.ProxyMetaManager.initMeta(ProxyMetaManager.java:411) ~[dble-9.9.9.9.jar:?]
        at com.actiontech.dble.DbleServer.reloadMetaData(DbleServer.java:543) ~[dble-9.9.9.9.jar:?]
        at com.actiontech.dble.config.ServerConfig.reloadMetaData(ServerConfig.java:467) ~[dble-9.9.9.9.jar:?]
        at com.actiontech.dble.config.ServerConfig.apply(ServerConfig.java:415) ~[dble-9.9.9.9.jar:?]
        at com.actiontech.dble.config.ServerConfig.reload(ServerConfig.java:222) ~[dble-9.9.9.9.jar:?]
        at com.actiontech.dble.manager.response.ReloadConfig.reload(ReloadConfig.java:492) ~[dble-9.9.9.9.jar:?]
        at com.actiontech.dble.manager.response.ReloadConfig.load(ReloadConfig.java:245) ~[dble-9.9.9.9.jar:?]
        at com.actiontech.dble.manager.response.ReloadConfig.execute(ReloadConfig.java:128) [dble-9.9.9.9.jar:?]
        at com.actiontech.dble.manager.response.ReloadConfig.execute(ReloadConfig.java:70) [dble-9.9.9.9.jar:?]
        at com.actiontech.dble.manager.handler.ReloadHandler.handle(ReloadHandler.java:27) [dble-9.9.9.9.jar:?]
        at com.actiontech.dble.manager.ManagerQueryHandler.query(ManagerQueryHandler.java:86) [dble-9.9.9.9.jar:?]
        at com.actiontech.dble.net.FrontendConnection.query(FrontendConnection.java:330) [dble-9.9.9.9.jar:?]
        at com.actiontech.dble.net.FrontendConnection.query(FrontendConnection.java:346) [dble-9.9.9.9.jar:?]
        at com.actiontech.dble.net.handler.ManagerCommandHandler.handleData(ManagerCommandHandler.java:27) [dble-9.9.9.9.jar:?]
        at com.actiontech.dble.net.handler.FrontendCommandHandler.handle(FrontendCommandHandler.java:73) [dble-9.9.9.9.jar:?]
        at com.actiontech.dble.net.handler.FrontEndHandlerRunnable.run(FrontEndHandlerRunnable.java:44) [dble-9.9.9.9.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_121]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_121]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
2019-07-18 03:07:49.903  WARN [BusinessExecutor0] (com.actiontech.dble.manager.response.ReloadConfig.writeErrorResult(ReloadConfig.java:270)) - Reload config failure.The reason is java.lang.NullPointerException
```

**Comment by yanhuqing666** [comment]
remove reload @@config

**Comment by yanhuqing666** [comment]
https://github.com/actiontech/dble-docs-cn/blob/develop/2.Function/2.1_manager_cmd/2.1.07_reload.md

**Comment by wjl1619** [comment]
verified on version: 5.6.29-dble-9.9.9.9-97b9e4cee24afeae57e7890aa5ebba36afcd225b-20191104052741
