### ISSUE TITLE
JWS sometime not work properly

### ISSUE THREAD

**Issue by sunsun314** [actiontech/dble#1402]
* **dble version：**  2.19.07.0
* **steps：**    
    when the dble is crash the wrapper would do nothing and just hang there   
* **supplements：**  
    here is the stack of the jws
```
Thread 1 (Thread 0x7f1ab3a6f740 (LWP 32218)):
#0  0x00007f1ab334642d in __lll_lock_wait () from /lib64/libpthread.so.0
#1  0x00007f1ab3341dcb in _L_lock_812 () from /lib64/libpthread.so.0
#2  0x00007f1ab3341c98 in pthread_mutex_lock () from /lib64/libpthread.so.0
#3  0x000000000040e0a0 in lockLoggingMutex ()
#4  0x000000000040f37d in log_printf ()
#5  0x0000000000404883 in wrapperJVMProcessExited ()
#6  0x000000000040bdc5 in wrapperGetProcessStatus ()
#7  0x000000000040be7a in sigActionChildDeath ()
#8  <signal handler called>
#9  0x00007f1ab305e105 in _xstat () from /lib64/libc.so.6
#10 0x00007f1ab302590d in __tzfile_read () from /lib64/libc.so.6
#11 0x00007f1ab3024c64 in tzset_internal () from /lib64/libc.so.6
#12 0x00007f1ab3025613 in __tz_convert () from /lib64/libc.so.6
#13 0x000000000040effe in log_printf_message ()
#14 0x000000000040f486 in log_printf ()
#15 0x000000000040c59c in wrapperKillProcessNow ()
#16 0x000000000040a9e8 in wrapperEventLoop ()
#17 0x000000000040451f in wrapperRunConsole ()
#18 0x000000000040caed in main ()
```
It shows that when the interruption callback the function it would try to take the file lock of the  wrapper.log,but the main function may also in log writting.
Upgrade the jws version can help to solve the problem

**Comment by irene-coming** [comment]
no way to verify,just close issue
