### ISSUE TITLE
got error "table node buildOwn exception! Error:null" from execute sql "select  ...  from where  ...  limit n"

### ISSUE THREAD

**Issue by wjl1619** [actiontech/dble#1419]
* **dble version：**  
5.6.29-dble-9.9.9.9-02cef4c18ca820fe4401a62c6e6c8053f689b467-20190926091030
* **preconditions ：**  
```sql
use schema1;
drop table if exists sharding_4_t1;
create table sharding_4_t1(id int,pad int);
insert into sharding_4_t1 values(1,1),(2,2),(3,3),(4,4);
```
* **configs：** 

**schema.xml**  

```xml
<schema name="schema1" sqlMaxLimit="100" dataNode="dn5">
    <table name="sharding_4_t1" dataNode="dn1,dn2,dn3,dn4" rule="hash-four" />
</schema>

```

* **steps：**    
    step1.  excute sql :
```sql
select 1 from sharding_4_t1 a,sharding_4_t1 b where a.id in(1,2) and b.id in(1,2) limit 1;
```
* **expect result：**  
    1. execute success
* **real result：**  
    1.mysql> select 1 from sharding_4_t1 a,sharding_4_t1 b where a.id in(1,2) and b.id in(1,2) limit 1;
ERROR 4005 (HY000): table node buildOwn exception! Error:null

* **supplements：**  
    1.mysql> explain select 1 from sharding_4_t1 a,sharding_4_t1 b where a.id in(1,2) and b.id in(1,2) limit 1;
ERROR 1105 (HY000): table node buildOwn exception! Error:null

    2.details in dble.log：
2019-09-29 11:03:15.984  INFO [BusinessExecutor0] (com.actiontech.dble.net.handler.FrontendCommandHandler.handle(FrontendCommandHandler.java:85)) - There is an error you may need know.
com.actiontech.dble.plan.common.exception.MySQLOutPutException: table node buildOwn exception! Error:null
        at com.actiontech.dble.backend.mysql.nio.handler.builder.TableNodeHandlerBuilder.buildOwn(TableNodeHandlerBuilder.java:65) ~[dble-9.9.9.9.jar:?]
        at com.actiontech.dble.backend.mysql.nio.handler.builder.BaseHandlerBuilder.build(BaseHandlerBuilder.java:107) ~[dble-9.9.9.9.jar:?]
        at com.actiontech.dble.backend.mysql.nio.handler.builder.HandlerBuilder.getBuilder(HandlerBuilder.java:59) ~[dble-9.9.9.9.jar:?]
        at com.actiontech.dble.backend.mysql.nio.handler.builder.JoinNodeHandlerBuilder.buildJoinChild(JoinNodeHandlerBuilder.java:140) ~[dble-9.9.9.9.jar:?]
        at com.actiontech.dble.backend.mysql.nio.handler.builder.JoinNodeHandlerBuilder.buildPre(JoinNodeHandlerBuilder.java:128) ~[dble-9.9.9.9.jar:?]
        at com.actiontech.dble.backend.mysql.nio.handler.builder.BaseHandlerBuilder.build(BaseHandlerBuilder.java:106) ~[dble-9.9.9.9.jar:?]
        at com.actiontech.dble.backend.mysql.nio.handler.builder.HandlerBuilder.getBuilder(HandlerBuilder.java:59) ~[dble-9.9.9.9.jar:?]
        at com.actiontech.dble.server.handler.ExplainHandler.buildNodes(ExplainHandler.java:96) ~[dble-9.9.9.9.jar:?]
        at com.actiontech.dble.server.handler.ExplainHandler.writeOutHeadAndEof(ExplainHandler.java:223) ~[dble-9.9.9.9.jar:?]
        at com.actiontech.dble.server.handler.ExplainHandler.handle(ExplainHandler.java:79) ~[dble-9.9.9.9.jar:?]
        at com.actiontech.dble.server.ServerQueryHandler.query(ServerQueryHandler.java:73) ~[dble-9.9.9.9.jar:?]
        at com.actiontech.dble.net.FrontendConnection.query(FrontendConnection.java:339) ~[dble-9.9.9.9.jar:?]
        at com.actiontech.dble.net.FrontendConnection.query(FrontendConnection.java:355) ~[dble-9.9.9.9.jar:?]
        at com.actiontech.dble.net.handler.FrontendCommandHandler.handleData(FrontendCommandHandler.java:105) ~[dble-9.9.9.9.jar:?]
        at com.actiontech.dble.net.handler.FrontendCommandHandler.handle(FrontendCommandHandler.java:78) [dble-9.9.9.9.jar:?]
        at com.actiontech.dble.net.handler.FrontEndHandlerRunnable.run(FrontEndHandlerRunnable.java:44) [dble-9.9.9.9.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_121]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_121]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
Caused by: java.lang.NullPointerException
        at com.actiontech.dble.route.util.RouterUtil.findRouterWithConditionsForTables(RouterUtil.java:906) ~[dble-9.9.9.9.jar:?]
        at com.actiontech.dble.route.util.RouterUtil.tryRouteForTablesComplex(RouterUtil.java:745) ~[dble-9.9.9.9.jar:?]
        at com.actiontech.dble.route.util.RouterUtil.routeFromParserComplex(RouterUtil.java:145) ~[dble-9.9.9.9.jar:?]
        at com.actiontech.dble.backend.mysql.nio.handler.builder.MergeBuilder.constructByStatement(MergeBuilder.java:75) ~[dble-9.9.9.9.jar:?]
        at com.actiontech.dble.backend.mysql.nio.handler.builder.MergeBuilder.constructByQuery(MergeBuilder.java:59) ~[dble-9.9.9.9.jar:?]
        at com.actiontech.dble.backend.mysql.nio.handler.builder.MergeBuilder.construct(MergeBuilder.java:53) ~[dble-9.9.9.9.jar:?]
        at com.actiontech.dble.backend.mysql.nio.handler.builder.TableNodeHandlerBuilder.buildOwn(TableNodeHandlerBuilder.java:58) ~[dble-9.9.9.9.jar:?]
        ... 18 more

**Comment by wjl1619** [comment]
verified on version: 5.6.29-dble-9.9.9.9-4a1798f8927fa77cef643523b5451807fe469989-20191008111520
