### ISSUE TITLE
small int type with PreparedStatement protocol will cause ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by yanhuqing666** [actiontech/dble#1491]
* **dble version：all version till to 9.9.9.9 1dc8981d64a9d3930088109f57d5cbd1336863de **  
* **preconditions ：**  
```
drop table if exists test;
create table  test(
id int,
code smallint(3)
) engine =innodb;
insert into test values(1,1);
```

* **configs：** 

**schema.xml**  

```
<table name="test" dataNode="dn1,dn2,dn3,dn4" rule="rule_mod"/>

```

**rule.xml**  

```


```

**server.xml**  

```


```

* **steps：**    
    step1.  
```
public void test4() throws Exception{
		Class.forName("com.mysql.jdbc.Driver");
		Connection connection =  DriverManager.getConnection("jdbc:mysql://127.0.0.1:8066?rewriteBatchedStatements=false&useServerPrepStmts=true", "root", "123456");
		connection.setCatalog("testdb");
		try {
			PreparedStatement stmt = connection.prepareStatement("select id,code from test where id = ?");
			stmt.setInt(1, 1); 
			ResultSet rs = stmt.executeQuery();
			while(rs.next())
			{
				System.out.println(rs.getString(1));
			}
			stmt.clearParameters();
			stmt.close();
		} catch (SQLException e2) {
			System.out.println(e2);
		} finally {
			connection.close();
		}
		
	}
```

* **expect result：**  
    1. code work and print 1
* **real result：**  
    1. java.sql.SQLException: Backend connect Error, Connection{DataHost[xx.xx.xx.xx:xxxx],Schema[xx]} refused
    2. dble.log 
```
[WARN ][backendBusinessExecutor2] Backend connect Error, Connection info:MySQLConnection [backendId=5, lastTime=1573523537994, user=root, schema=xxx, old schema=db_2, borrowed=true, fromSlaveDB=false, mysqlId=887,character_set_client=utf8,character_set_results=NULL,collation_connection=utf8_general_ci, txIsolation=3, autocommit=true, attachment=dn2{select id,code from test where id = 1}.0, respHandler=SingleNodeHandler [node=dn2{select id,code from test where id = 1}.0, packetId=5], host=xxx, port=xxx, statusSync=com.actiontech.dble.backend.mysql.nio.MySQLConnection$StatusSync@47c69ec0, writeQueue=0, modifiedSQLExecuted=] java.lang.ArrayIndexOutOfBoundsException: 1
	at com.actiontech.dble.util.ByteUtil.getShort(ByteUtil.java:149)
	at com.actiontech.dble.net.mysql.BinaryRowDataPacket.convert(BinaryRowDataPacket.java:139)
	at com.actiontech.dble.net.mysql.BinaryRowDataPacket.read(BinaryRowDataPacket.java:72)
	at com.actiontech.dble.backend.mysql.nio.handler.SingleNodeHandler.rowResponse(SingleNodeHandler.java:391)
	at com.actiontech.dble.backend.mysql.nio.MySQLConnectionHandler.handleRowPacket(MySQLConnectionHandler.java:208)
	at com.actiontech.dble.backend.mysql.nio.MySQLConnectionHandler.handleData(MySQLConnectionHandler.java:132)
	at com.actiontech.dble.net.handler.BackendAsyncHandler.handleInnerData(BackendAsyncHandler.java:100)
	at com.actiontech.dble.net.handler.BackendAsyncHandler.access$000(BackendAsyncHandler.java:19)
	at com.actiontech.dble.net.handler.BackendAsyncHandler$1.run(BackendAsyncHandler.java:51)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
 (com.actiontech.dble.backend.mysql.nio.handler.SingleNodeHandler:SingleNodeHandler.java:134) 
```
* **supplements：**  
    1.

**Comment by wjl1619** [comment]
verified on version: 5.6.29-dble-9.9.9.9-2acfdadab457bf0c6506e67c65041c80a8636876-20191112094813
