### ISSUE TITLE
Every first time sysbench test got [Backend connect Error]

### ISSUE THREAD

**Issue by irene-coming** [actiontech/dble#1514]
* **dble version：**  
5.6.29-dble-2.19.09.0-28c8819f535c0fa0405d243628c58ccbff6fde3d-20191120070105
* **preconditions ：**  
from dble -performance-base-testing-of-broadcast-select
* **configs：** 

**schema.xml**  

```


```

**rule.xml**  

```


```

**server.xml**  

```


```

* **steps：**    
    step1.  sysbench test dble:
```sysbench
sysbench --mysql-db=mytest --mysql-host=xx.xx.xx.xx --mysql-port=8066 --mysql-user=xx --mysql-password=xx /usr/share/sysbench/tests/include/oltp_legacy/oltp.lua --oltp_tables_count=1 --oltp-table-size=10000000 --oltp-read-only=on --report-interval=3 --default-charset=utf8 --max-requests=0 --percentile=95 --oltp_skip_trx=on --oltp_point_selects=0 --oltp_simple_ranges=1 --oltp_sum_ranges=0 --oltp_order_ranges=0 --oltp_distinct_ranges=0 --oltp_range_size=9 --threads=512 --time=60 run
```

* **expect result：**  
    1.sysbench success
* **real result：**  
    1.the first time failed for:
```
FATAL: mysql_store_result() returned error 5314 (Backend connect Error, Connection{DataHost[10.186.17.101:3306],Schema[mfdb1]} refused)
FATAL: `thread_run' function failed: /usr/share/sysbench/tests/include/oltp_legacy/oltp.lua:56: db_query() failed
```
 the second time can success.
* **supplements：**  
    1. related dble log:
```log
2019-11-26 15:28:52.235  INFO [backendBusinessExecutor8] (com.actiontech.dble.backend.mysql.nio.MySQLConnectionHandler.handleDataError(MySQLConnectionHandler.java:241)) - MySQLConnection [backendId=70, lastTime=1574753332229, user=action, schema=mfdb1, old schema=null, borrowed=true, fromSlaveDB=false, mysqlId=376141,character_set_client=utf8mb4,character_set_results=utf8mb4,collation_connection=utf8mb4_general_ci, txIsolation=-1, autocommit=true, attachment=dn1{SELECT c FROM sbtest1 WHERE id BETWEEN 5025837 AND 5025845}.0, respHandler=com.actiontech.dble.backend.mysql.nio.handler.MultiNodeQueryHandler@5efc1271, host=10.186.17.101, port=3306, statusSync=com.actiontech.dble.backend.mysql.nio.MySQLConnection$StatusSync@503bf7de, writeQueue=0, modifiedSQLExecuted=] handle data error:
java.lang.NullPointerException: null
        at java.util.TreeMap.rotateRight(TreeMap.java:2243) ~[?:1.8.0_161]
        at java.util.TreeMap.fixAfterInsertion(TreeMap.java:2275) ~[?:1.8.0_161]
        at java.util.TreeMap.put(TreeMap.java:582) ~[?:1.8.0_161]
        at com.actiontech.dble.net.handler.BackendAsyncHandler.handleInnerData(BackendAsyncHandler.java:92) ~[dble-2.19.09.0.jar:?]
        at com.actiontech.dble.net.handler.BackendAsyncHandler.executeQueue(BackendAsyncHandler.java:68) [dble-2.19.09.0.jar:?]
        at com.actiontech.dble.net.handler.ConcurrentBackEndHandlerRunnable.run(ConcurrentBackEndHandlerRunnable.java:23) [dble-2.19.09.0.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_161]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_161]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]
2019-11-26 15:28:53.247  WARN [backendBusinessExecutor8] (com.actiontech.dble.backend.mysql.nio.handler.MultiNodeQueryHandler.connectionError(MultiNodeQueryHandler.java:176)) - Backend connect Error, Connection info:MySQLConnection [backendId=70, lastTime=1574753332229, user=action, schema=mfdb1, old schema=null, borrowed=true, fromSlaveDB=false, mysqlId=376141,character_set_client=utf8mb4,character_set_results=utf8mb4,collation_connection=utf8mb4_general_ci, txIsolation=-1, autocommit=true, attachment=dn1{SELECT c FROM sbtest1 WHERE id BETWEEN 5025837 AND 5025845}.0, respHandler=com.actiontech.dble.backend.mysql.nio.handler.MultiNodeQueryHandler@5efc1271, host=10.186.17.101, port=3306, statusSync=com.actiontech.dble.backend.mysql.nio.MySQLConnection$StatusSync@503bf7de, writeQueue=0, modifiedSQLExecuted=]
java.lang.NullPointerException: null
        at java.util.TreeMap.rotateRight(TreeMap.java:2243) ~[?:1.8.0_161]
        at java.util.TreeMap.fixAfterInsertion(TreeMap.java:2275) ~[?:1.8.0_161]
        at java.util.TreeMap.put(TreeMap.java:582) ~[?:1.8.0_161]
        at com.actiontech.dble.net.handler.BackendAsyncHandler.handleInnerData(BackendAsyncHandler.java:92) ~[dble-2.19.09.0.jar:?]
        at com.actiontech.dble.net.handler.BackendAsyncHandler.executeQueue(BackendAsyncHandler.java:68) [dble-2.19.09.0.jar:?]
        at com.actiontech.dble.net.handler.ConcurrentBackEndHandlerRunnable.run(ConcurrentBackEndHandlerRunnable.java:23) [dble-2.19.09.0.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_161]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_161]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]
```

**Comment by irene-coming** [comment]
verified on dble: 5.6.29-dble-2.19.09.1-f4a23b411d365ab67b3b0870e56e42768ed57d37-20191203074446
