### ISSUE TITLE
When try to pushdown the OR condition with Error

### ISSUE THREAD

**Issue by uliude** [actiontech/dble#1705]
dble with condition below
```
<table name="vs_store_company,vs_store,vs_fin_cash_accinfo" dataNode="dn1,dn2" rule="rule_mod2" />
rule_mod2 is tableRule to split data into 2 nodes with any way with column id

create table vs_store_company(pk_id int,remakr int,audit_status int,`status` int);
create table vs_store(fk_store_comp_id int);
create table vs_fin_cash_accinfo(fk_store_comp_id int,audit_status int);

```

execute sql below:
```
SELECT
	count(0)
FROM
	(
		SELECT
			c.pk_id,
			c.remark
		FROM
			vs_store_company c
		LEFT JOIN vs_store s ON c.pk_id = s.fk_store_comp_id
		INNER JOIN vs_fin_cash_accinfo ca ON ca.fk_store_comp_id = c.pk_id
		WHERE
			c.`status` = 1
		AND (
			c.audit_status = 2
			OR ca.audit_status = 2
		)
	) t

```
get error return :
```
[Err] 1105 - com.actiontech.dble.plan.node.JoinNode cannot be cast to com.actiontech.dble.plan.node.TableNode
```
find error in dble.log
```
2020-03-18 13:47:47,789 [INFO ][BusinessExecutor1] There is an error you may need know. java.lang.ClassCastException: com.actiontech.dble.plan.node.JoinNode cannot be cast to com.actiontech.dble.plan.node.TableNode
	at com.actiontech.dble.plan.util.FilterUtils.gourpByRefertTable(FilterUtils.java:109)
	at com.actiontech.dble.plan.util.FilterUtils.splitFilter(FilterUtils.java:56)
	at com.actiontech.dble.plan.util.FilterUtils.splitFilter(FilterUtils.java:41)
	at com.actiontech.dble.plan.optimizer.FilterPusher.pushFilter(FilterPusher.java:120)
	at com.actiontech.dble.plan.optimizer.FilterPusher.getQueryNode(FilterPusher.java:148)
	at com.actiontech.dble.plan.optimizer.FilterPusher.pushFilter(FilterPusher.java:126)
	at com.actiontech.dble.plan.optimizer.FilterPusher.optimize(FilterPusher.java:71)
	at com.actiontech.dble.plan.optimizer.MyOptimizer.optimize(MyOptimizer.java:52)
	at com.actiontech.dble.server.NonBlockingSession.executeMultiSelect(NonBlockingSession.java:665)
	at com.actiontech.dble.server.NonBlockingSession.execute(NonBlockingSession.java:490)
	at com.actiontech.dble.server.ServerConnection.routeEndExecuteSQL(ServerConnection.java:341)
	at com.actiontech.dble.server.ServerConnection.execute(ServerConnection.java:279)
	at com.actiontech.dble.server.handler.SelectHandler.handle(SelectHandler.java:108)
	at com.actiontech.dble.server.ServerQueryHandler.query(ServerQueryHandler.java:100)
	at com.actiontech.dble.net.FrontendConnection.query(FrontendConnection.java:342)
	at com.actiontech.dble.net.FrontendConnection.query(FrontendConnection.java:359)
	at com.actiontech.dble.net.handler.FrontendCommandHandler.handleData(FrontendCommandHandler.java:118)
	at com.actiontech.dble.net.handler.FrontendCommandHandler.handle(FrontendCommandHandler.java:91)
	at com.actiontech.dble.net.handler.FrontEndHandlerRunnable.run(FrontEndHandlerRunnable.java:40)
```

**Comment by FlyingMao** [comment]
**verified version:** dble-9.9.9.9-4618b013d5fae2b625c86b04244c3ee7eba27fe5-20200402074058
