### ISSUE TITLE
NestLoop may cause java.util.ConcurrentModificationException 

### ISSUE THREAD

**Issue by uliude** [actiontech/dble#1706]
dble version : 2.19.11/rel
dble with config below:
```
server.xml useJoinStrategy is true
<table name="vs_order_return,vs_store,vs_order" dataNode="dn1,dn2" rule="rule_mod2" />

create table vs_order_return(pk_id int,return_num int,src_order_id int,order_handle_status int)
create table vs_order(pk_id int,sale_act_type int,fk_store_id int)
create table vs_store(pk_id int,fk_org_id int,store_name int)
```
add delay in ：
```
com.actiontech.dble.backend.mysql.nio.handler.builder.HandlerBuilder  Line#51
```
execute sql below:
```
SELECT
		vor.pk_id,
		store.fk_org_id,
		store.store_name storeName,
		vor.return_num orderGoodsNum,
		vo.sale_act_type
FROM
	vs_order_return vor
LEFT JOIN vs_order vo ON vo.pk_id = vor.src_order_id
LEFT JOIN vs_store store ON vo.fk_store_id = store.pk_id
WHERE
	vor.order_handle_status = 3
```
May get error result :
```
Cause: java.sql.SQLException: java.util.ConcurrentModificationException
```
get error stack in dble.log
```
java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:901)
	at java.util.ArrayList$Itr.next(ArrayList.java:851)
	at com.actiontech.dble.backend.mysql.nio.handler.builder.HandlerBuilder.startHandler(HandlerBuilder.java:50)
	at com.actiontech.dble.backend.mysql.nio.handler.builder.HandlerBuilder.build(HandlerBuilder.java:77)
	at com.actiontech.dble.server.NonBlockingSession.executeMultiResultSet(NonBlockingSession.java:629)
	at com.actiontech.dble.server.NonBlockingSession.executeMultiSelect(NonBlockingSession.java:686)
	at com.actiontech.dble.server.NonBlockingSession.execute(NonBlockingSession.java:490)
	at com.actiontech.dble.server.ServerConnection.routeEndExecuteSQL(ServerConnection.java:341)
	at com.actiontech.dble.server.ServerConnection.execute(ServerConnection.java:279)
	at com.actiontech.dble.server.handler.SelectHandler.handle(SelectHandler.java:108)
	at com.actiontech.dble.server.ServerQueryHandler.query(ServerQueryHandler.java:100)
	at com.actiontech.dble.net.FrontendConnection.query(FrontendConnection.java:342)
	at com.actiontech.dble.net.FrontendConnection.query(FrontendConnection.java:359)
	at com.actiontech.dble.net.handler.FrontendCommandHandler.handleData(FrontendCommandHandler.java:118)
	at com.actiontech.dble.net.handler.FrontendCommandHandler.handle(FrontendCommandHandler.java:91)
	at com.actiontech.dble.net.handler.FrontEndHandlerRunnable.run(FrontEndHandlerRunnable.java:40)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by FlyingMao** [comment]
**verified version:** 9.9.9.9-1e1ac03945b95a1c3e54852e2edb7f04cc3d6bc8-20200402092740
