### ISSUE TITLE
got "NullPointerException" error when execute a complex query after executing insert into multi-nodes query

### ISSUE THREAD

**Issue by wjl1619** [actiontech/dble#1762]
* **dble version：**  
5.6.29-dble-9.9.9.9-14e43f2e85d2b29aea766d8836f6f799bee2fb2d-20200401051400
* **preconditions ：**  
```sql
set autocommit=0;
insert into sharding_4_t1 values(5,5),(6,6),(7,7),(8,8);
```
* **configs：** 

**server.xml**  

```xml
<system>
        <property name="processors">1</property>
        <property name="processorExecutor">1</property>
        <property name="autocommit">1</property>
        <property name="txIsolation">3</property>
        </system>
```

* **steps：**    
    step1.  execute sql 
```sql
select count(*) from sharding_4_t1 order by id;
```
* **expect result：**  
    1.select success
* **real result：**  
    1.mysql> select count(*) from sharding_4_t1 order by id;
ERROR 2013 (HY000): Lost connection to MySQL server during query
* **supplements：**  
    1.dble.log:
```
2020-04-01 17:53:28.505 DEBUG [BusinessExecutor0] (com.actiontech.dble.backend.mysql.nio.handler.query.impl.BaseSelectHandler.execute(BaseSelectHandler.java:79)) - MySQLConnection [backendId=27, lastTime=1585734784390, user=test, schema=db2, old schema=db2, borrowed=true, fromSlaveDB=false, mysqlId=82,character_set_client=latin1,character_set_results=latin1,collation_connection=latin1_swedish_ci, txIsolation=3, autocommit=false, attachment=dn4{select COUNT(*) as `_$COUNT$_rpda_0`,`sharding_4_t1`.`id` from  `sharding_4_t1` ORDER BY `sharding_4_t1`.`id` ASC LIMIT 100}.0, respHandler=com.actiontech.dble.backend.mysql.nio.handler.MultiNodeQueryHandler@33b7e13d, host=172.100.9.6, port=3306, statusSync=null, writeQueue=0, xaStatus=0] send sql:select COUNT(*) as `_$COUNT$_rpda_0`,`sharding_4_t1`.`id` from  `sharding_4_t1` ORDER BY `sharding_4_t1`.`id` ASC LIMIT 100
2020-04-01 17:53:28.505 DEBUG [BusinessExecutor0] (com.actiontech.dble.backend.mysql.nio.handler.builder.HandlerBuilder.build(HandlerBuilder.java:80)) - HandlerBuilder.build cost:22666278
2020-04-01 17:53:28.506  INFO [complexQueryExecutor5] (com.actiontech.dble.backend.mysql.nio.handler.MultiNodeQueryHandler.handleDataProcessException(MultiNodeQueryHandler.java:583)) - caught exception
java.lang.NullPointerException: null
        at com.actiontech.dble.net.AbstractConnection.writeToBuffer(AbstractConnection.java:493) ~[dble-9.9.9.9.jar:?]
        at com.actiontech.dble.backend.mysql.nio.handler.MultiNodeQueryHandler.executeFieldEof(MultiNodeQueryHandler.java:540) [dble-9.9.9.9.jar:?]
        at com.actiontech.dble.backend.mysql.nio.handler.MultiNodeQueryHandler.fieldEofResponse(MultiNodeQueryHandler.java:324) [dble-9.9.9.9.jar:?]
        at com.actiontech.dble.backend.mysql.nio.MySQLConnectionHandler.handleFieldEofPacket(MySQLConnectionHandler.java:198) [dble-9.9.9.9.jar:?]
        at com.actiontech.dble.backend.mysql.nio.MySQLConnectionHandler.handleData(MySQLConnectionHandler.java:113) [dble-9.9.9.9.jar:?]
        at com.actiontech.dble.net.handler.BackendAsyncHandler.handleInnerData(BackendAsyncHandler.java:100) [dble-9.9.9.9.jar:?]
        at com.actiontech.dble.net.handler.BackendAsyncHandler.access$000(BackendAsyncHandler.java:19) [dble-9.9.9.9.jar:?]
        at com.actiontech.dble.net.handler.BackendAsyncHandler$1.run(BackendAsyncHandler.java:51) [dble-9.9.9.9.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_121]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_121]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
```

**Comment by wjl1619** [comment]
verified on version:  5.6.29-dble-9.9.9.9-61858e92bf2265b6a98f88e18033df7f8973455c-20200402060226
