### ISSUE TITLE
dble may hang when try to reload config

### ISSUE THREAD

**Issue by sunsun314** [actiontech/dble#1773]
* **dble version：**   2.19.11.0/rel
```
INFO   | jvm 1    | 2020/04/01 18:51:24 | "BusinessExecutor1" #36 daemon prio=5 os_prio=0 tid=0x00007fe3245ee000 nid=0x666b waiting on condition [0x00007fe3781f6000]
INFO   | jvm 1    | 2020/04/01 18:51:24 |    java.lang.Thread.State: WAITING (parking)
INFO   | jvm 1    | 2020/04/01 18:51:24 | 	at sun.misc.Unsafe.park(Native Method)
INFO   | jvm 1    | 2020/04/01 18:51:24 | 	- parking to wait for  <0x000000076d7b9278> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
INFO   | jvm 1    | 2020/04/01 18:51:24 | 	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
INFO   | jvm 1    | 2020/04/01 18:51:24 | 	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
INFO   | jvm 1    | 2020/04/01 18:51:24 | 	at com.actiontech.dble.server.variables.VarsExtractorHandler.waitDone(VarsExtractorHandler.java:110)
INFO   | jvm 1    | 2020/04/01 18:51:24 | 	at com.actiontech.dble.server.variables.VarsExtractorHandler.execute(VarsExtractorHandler.java:47)
INFO   | jvm 1    | 2020/04/01 18:51:24 | 	at com.actiontech.dble.manager.response.ReloadConfig.getSystemVariablesFromDataHost(ReloadConfig.java:481)
INFO   | jvm 1    | 2020/04/01 18:51:24 | 	at com.actiontech.dble.manager.response.ReloadConfig.intelligentReloadAll(ReloadConfig.java:346)
INFO   | jvm 1    | 2020/04/01 18:51:24 | 	at com.actiontech.dble.manager.response.ReloadConfig.reloadAll(ReloadConfig.java:329)
INFO   | jvm 1    | 2020/04/01 18:51:24 | 	at com.actiontech.dble.manager.response.ReloadConfig.reloadWithUcore(ReloadConfig.java:165)
INFO   | jvm 1    | 2020/04/01 18:51:24 | 	at com.actiontech.dble.manager.response.ReloadConfig.execute(ReloadConfig.java:123)
INFO   | jvm 1    | 2020/04/01 18:51:24 | 	at com.actiontech.dble.manager.response.ReloadConfig.execute(ReloadConfig.java:75)
INFO   | jvm 1    | 2020/04/01 18:51:24 | 	at com.actiontech.dble.manager.handler.ReloadHandler.handle(ReloadHandler.java:27)
INFO   | jvm 1    | 2020/04/01 18:51:24 | 	at com.actiontech.dble.manager.ManagerQueryHandler.query(ManagerQueryHandler.java:86)
INFO   | jvm 1    | 2020/04/01 18:51:24 | 	at com.actiontech.dble.net.FrontendConnection.query(FrontendConnection.java:342)
INFO   | jvm 1    | 2020/04/01 18:51:24 | 	at com.actiontech.dble.net.FrontendConnection.query(FrontendConnection.java:359)
INFO   | jvm 1    | 2020/04/01 18:51:24 | 	at com.actiontech.dble.net.handler.ManagerCommandHandler.handleData(ManagerCommandHandler.java:27)
INFO   | jvm 1    | 2020/04/01 18:51:24 | 	at com.actiontech.dble.net.handler.FrontendCommandHandler.handle(FrontendCommandHandler.java:91)
INFO   | jvm 1    | 2020/04/01 18:51:24 | 	at com.actiontech.dble.net.handler.FrontEndHandlerRunnable.run(FrontEndHandlerRunnable.java:40)
INFO   | jvm 1    | 2020/04/01 18:51:24 | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
INFO   | jvm 1    | 2020/04/01 18:51:24 | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
INFO   | jvm 1    | 2020/04/01 18:51:24 | 	at java.lang.Thread.run(Thread.java:745)

```

**Comment by sunsun314** [comment]
detail issue would be fix in https://github.com/actiontech/dble/issues/1801
