### ISSUE TITLE
if value of binlog pause status in zk is empty, dble report ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by Dinosauria** [actiontech/dble#1838]
* **dble version：**  
[root@dble-1 dble]# cat version.txt
GitVersion d4ff003692996886fee1206ddfde76fe4abb53f9
BuildTime 20200429033631
MavenVersion 2.19.11.99
* **preconditions ：**  
3 dble nodes in a zk cluster
* **configs：** 

**schema.xml**  

```


```

**rule.xml**  

```


```

**server.xml**  

```


```

* **steps：**    
1. add 3 nodes dbles with zk cluster by testing automation code
2. exec `./bin/dble stop` on dble-2 & dble-3
3. update dble version from 9.9.9.9 to 2.19.11.99（on all dble nodes）by update_dble_version.sh (dble-test-suite-master\behave_dble\compose\update_dble_version.sh)
4. exec `./bin/dble stop` on dble-2 & dble-3 again ( all the dble nodes will be restart after upgrade dble-versions by using the bash shell)
5. check dble.log on dble-1,we may find:

```
2020-04-29 14:06:31.234  INFO [WrapperSimpleAppMain] (org.quartz.impl.StdSchedulerFactory.instantiate(StdSchedulerFactory.java:1339)) - Quartz scheduler 'QuartzScheduler' initialized from an externally provided properties instance.2020-04-29 14:06:31.234  INFO [WrapperSimpleAppMain] (org.quartz.impl.StdSchedulerFactory.instantiate(StdSchedulerFactory.java:1343)) - Quartz scheduler version: 2.2.1
2020-04-29 14:06:31.235  INFO [WrapperSimpleAppMain] (org.quartz.core.QuartzScheduler.start(QuartzScheduler.java:575)) - Scheduler QuartzScheduler_$_NON_CLUSTERED started.
2020-04-29 14:06:31.236  INFO [WrapperSimpleAppMain] (com.actiontech.dble.DbleServer.startup(DbleServer.java:272)) - ====================================CronScheduler started=========================================
2020-04-29 14:06:31.265  INFO [WrapperSimpleAppMain] (com.actiontech.dble.DbleServer.startup(DbleServer.java:276)) - ======================================ALL START INIT FINISH=======================================
2020-04-29 15:24:37.825  WARN [Curator-PathChildrenCache-0] (com.actiontech.dble.server.OfflineStatusListener.releaseForBinlog(OfflineStatusListener.java:130)) -  releaseForBinlog error
java.lang.ArrayIndexOutOfBoundsException: 1
        at com.actiontech.dble.config.loader.zkprocess.zookeeper.process.BinlogPause.<init>(BinlogPause.java:28) ~[dble-2.19.11.99.jar:?]
        at com.actiontech.dble.server.OfflineStatusListener.releaseForBinlog(OfflineStatusListener.java:98) [dble-2.19.11.99.jar:?]
        at com.actiontech.dble.server.OfflineStatusListener.deleteNode(OfflineStatusListener.java:53) [dble-2.19.11.99.jar:?]
        at com.actiontech.dble.server.OfflineStatusListener.childEvent(OfflineStatusListener.java:43) [dble-2.19.11.99.jar:?]
        at org.apache.curator.framework.recipes.cache.PathChildrenCache$5.apply(PathChildrenCache.java:522) [curator-recipes-2.11.0.jar:?]
        at org.apache.curator.framework.recipes.cache.PathChildrenCache$5.apply(PathChildrenCache.java:516) [curator-recipes-2.11.0.jar:?]
        at org.apache.curator.framework.listen.ListenerContainer$1.run(ListenerContainer.java:93) [curator-framework-2.11.0.jar:?]
        at com.google.common.util.concurrent.MoreExecutors$DirectExecutorService.execute(MoreExecutors.java:310) [guava-19.0.jar:?]
        at org.apache.curator.framework.listen.ListenerContainer.forEach(ListenerContainer.java:84) [curator-framework-2.11.0.jar:?]
        at org.apache.curator.framework.recipes.cache.PathChildrenCache.callListeners(PathChildrenCache.java:513) [curator-recipes-2.11.0.jar:?]
        at org.apache.curator.framework.recipes.cache.EventOperation.invoke(EventOperation.java:35) [curator-recipes-2.11.0.jar:?]
        at org.apache.curator.framework.recipes.cache.PathChildrenCache$9.run(PathChildrenCache.java:773) [curator-recipes-2.11.0.jar:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_121]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_121]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_121]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_121]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_121]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_121]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
2020-04-29 15:24:37.831  WARN [Curator-PathChildrenCache-0] (com.actiontech.dble.server.OfflineStatusListener.releaseForBinlog(OfflineStatusListener.java:130)) -  releaseForBinlog error
java.lang.ArrayIndexOutOfBoundsException: 1
        at com.actiontech.dble.config.loader.zkprocess.zookeeper.process.BinlogPause.<init>(BinlogPause.java:28) ~[dble-2.19.11.99.jar:?]
        at com.actiontech.dble.server.OfflineStatusListener.releaseForBinlog(OfflineStatusListener.java:98) [dble-2.19.11.99.jar:?]
        at com.actiontech.dble.server.OfflineStatusListener.deleteNode(OfflineStatusListener.java:53) [dble-2.19.11.99.jar:?]
        at com.actiontech.dble.server.OfflineStatusListener.childEvent(OfflineStatusListener.java:43) [dble-2.19.11.99.jar:?]
        at org.apache.curator.framework.recipes.cache.PathChildrenCache$5.apply(PathChildrenCache.java:522) [curator-recipes-2.11.0.jar:?]
        at org.apache.curator.framework.recipes.cache.PathChildrenCache$5.apply(PathChildrenCache.java:516) [curator-recipes-2.11.0.jar:?]
        at org.apache.curator.framework.listen.ListenerContainer$1.run(ListenerContainer.java:93) [curator-framework-2.11.0.jar:?]
        at com.google.common.util.concurrent.MoreExecutors$DirectExecutorService.execute(MoreExecutors.java:310) [guava-19.0.jar:?]
        at org.apache.curator.framework.listen.ListenerContainer.forEach(ListenerContainer.java:84) [curator-framework-2.11.0.jar:?]
        at org.apache.curator.framework.recipes.cache.PathChildrenCache.callListeners(PathChildrenCache.java:513) [curator-recipes-2.11.0.jar:?]
        at org.apache.curator.framework.recipes.cache.EventOperation.invoke(EventOperation.java:35) [curator-recipes-2.11.0.jar:?]
        at org.apache.curator.framework.recipes.cache.PathChildrenCache$9.run(PathChildrenCache.java:773) [curator-recipes-2.11.0.jar:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_121]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_121]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_121]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_121]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_121]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_121]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
```

6. then restart dble-1,checking dble.log on dble-1(./bin/dble stop && ./bin/dble start),we may find:

```
2020-04-29 16:15:20.553  INFO [WrapperSimpleAppMain] (com.actiontech.dble.config.loader.zkprocess.zktoxml.listen.RuleszkToxmlLoader.notifyProcess(RuleszkToxmlLoader.java:91)) - RuleszkToxmlLoader notifyProcess zk to object zk Rules  
    write :/opt/dble/conf/rule.xml is success
2020-04-29 16:15:20.571  INFO [WrapperSimpleAppMain] (com.actiontech.dble.config.loader.zkprocess.zktoxml.listen.ServerzkToxmlLoader.notifyProcess(ServerzkToxmlLoader.java:76)) - ServerzkToxmlLoader notifyProcess zk to object  zk ser
ver Object  :Server [system=System [property=[Property{value='1', name='processors'}, Property{value='1', name='processorExecutor'}, Property{value='false', name='useOuterHa'}]], user=[User{name='test', property=[Property{value='1111
11', name='password'}, Property{value='schema1', name='schemas'}]}, User{name='root', property=[Property{value='111111', name='password'}, Property{value='true', name='manager'}]}], firewall=FireWall{whiteHost =null, blacklist=null}]
2020-04-29 16:15:20.572  INFO [WrapperSimpleAppMain] (com.actiontech.dble.config.loader.zkprocess.zktoxml.listen.ServerzkToxmlLoader.notifyProcess(ServerzkToxmlLoader.java:82)) - ServerzkToxmlLoader notifyProcess zk to object writePa
th :/opt/dble/conf/server.xml
2020-04-29 16:15:20.573  INFO [WrapperSimpleAppMain] (com.actiontech.dble.config.loader.zkprocess.zktoxml.listen.ServerzkToxmlLoader.notifyProcess(ServerzkToxmlLoader.java:86)) - ServerzkToxmlLoader notifyProcess zk to object zk serv
er      write :/opt/dble/conf/server.xml is success
2020-04-29 16:15:20.595  WARN [WrapperSimpleAppMain] (com.actiontech.dble.config.loader.zkprocess.comm.ZookeeperProcessListen.initAllNode(ZookeeperProcessListen.java:66)) - ZookeeperProcessListen initAllNode :com.actiontech.dble.conf
ig.loader.zkprocess.zktoxml.listen.SchemaszkToxmlLoader@5fa1e19f;error:Exception info:
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was BEGIN_OBJECT at line 1 column 132 path $[0].writeHost
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:224) ~[gson-2.8.0.jar:?]
        at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41) ~[gson-2.8.0.jar:?]
        at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:82) ~[gson-2.8.0.jar:?]
        at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:61) ~[gson-2.8.0.jar:?]
        at com.google.gson.Gson.fromJson(Gson.java:887) ~[gson-2.8.0.jar:?]
        at com.google.gson.Gson.fromJson(Gson.java:852) ~[gson-2.8.0.jar:?]
        at com.google.gson.Gson.fromJson(Gson.java:801) ~[gson-2.8.0.jar:?]
        at com.actiontech.dble.config.loader.zkprocess.parse.JsonProcessBase.toBeanformJson(JsonProcessBase.java:47) ~[dble-2.19.11.99.jar:?]
        at com.actiontech.dble.config.loader.zkprocess.parse.entryparse.schema.json.DataHostJsonParse.parseJsonToBean(DataHostJsonParse.java:35) ~[dble-2.19.11.99.jar:?]
        at com.actiontech.dble.config.loader.zkprocess.parse.entryparse.schema.json.DataHostJsonParse.parseJsonToBean(DataHostJsonParse.java:23) ~[dble-2.19.11.99.jar:?]
        at com.actiontech.dble.config.loader.zkprocess.zktoxml.listen.SchemaszkToxmlLoader.zktoSchemasBean(SchemaszkToxmlLoader.java:114) ~[dble-2.19.11.99.jar:?]
        at com.actiontech.dble.config.loader.zkprocess.zktoxml.listen.SchemaszkToxmlLoader.notifyProcess(SchemaszkToxmlLoader.java:86) ~[dble-2.19.11.99.jar:?]
        at com.actiontech.dble.config.loader.zkprocess.comm.ZookeeperProcessListen.initAllNode(ZookeeperProcessListen.java:64) [dble-2.19.11.99.jar:?]
        at com.actiontech.dble.config.loader.zkprocess.zktoxml.ZktoXmlMain.initLocalConfFromZK(ZktoXmlMain.java:85) [dble-2.19.11.99.jar:?]
        at com.actiontech.dble.config.loader.zkprocess.zktoxml.ZktoXmlMain.loadZktoFile(ZktoXmlMain.java:49) [dble-2.19.11.99.jar:?]
        at com.actiontech.dble.config.loader.zkprocess.comm.ZkConfig.initZk(ZkConfig.java:42) [dble-2.19.11.99.jar:?]
        at com.actiontech.dble.singleton.ClusterGeneralConfig.initData(ClusterGeneralConfig.java:71) [dble-2.19.11.99.jar:?]
        at com.actiontech.dble.cluster.ClusterController.init(ClusterController.java:47) [dble-2.19.11.99.jar:?]
        at com.actiontech.dble.DbleStartup.main(DbleStartup.java:23) [dble-2.19.11.99.jar:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_121]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_121]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_121]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_121]
        at org.tanukisoftware.wrapper.WrapperSimpleApp.run(WrapperSimpleApp.java:349) [wrapper.jar:3.5.40]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
Caused by: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was BEGIN_OBJECT at line 1 column 132 path $[0].writeHost
        at com.google.gson.stream.JsonReader.beginArray(JsonReader.java:350) ~[gson-2.8.0.jar:?]
        at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:80) ~[gson-2.8.0.jar:?]
        at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:61) ~[gson-2.8.0.jar:?]
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:129) ~[gson-2.8.0.jar:?]
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:220) ~[gson-2.8.0.jar:?]
        ... 24 more
2020-04-29 16:15:20.629  INFO [WrapperSimpleAppMain] (com.actiontech.dble.config.loader.zkprocess.zktoxml.ZktoXmlMain.loadZkWatch(ZktoXmlMain.java:128)) - ZktoxmlMain loadZkWatch path:/dble/cluster-1/conf/status regist success
2020-04-29 16:15:20.635  INFO [WrapperSimpleAppMain] (com.actiontech.dble.config.loader.zkprocess.zktoxml.ZktoXmlMain.loadZkWatch(ZktoXmlMain.java:128)) - ZktoxmlMain loadZkWatch path:/dble/cluster-1/binlog_pause/status regist success
```

**Comment by Dinosauria** [comment]
verified on version:5.6.29-dble-2.19.11.99-0ac4a09af279c006eea0243e08603f14f7514043-20200504005314 & 5.6.29-dble-2.20.04.99-03f03ab8ff50fcddbadd393dd64a277bc8f5984c-20200513054314
