### ISSUE TITLE
druid parser gives error when do sql statistics( after sql executed success)

### ISSUE THREAD

**Issue by irene-coming** [actiontech/dble#1844]
* **dble version：**  
5.6.29-dble-2.20.04.99-a95d66d91f01939078354d4bc098fbcdd4b87681-20200507091741
* **preconditions ：**  
create table sharding_2_t1(id int,
 normal_col_1 varchar(30),
 normal_col_2 varchar(30),
 normal_col_3 varchar(30),
 normal_col_4 varchar(30),
 normal_col_5 varchar(30),
 normal_col_6 varchar(30),
 normal_col_7 varchar(30),
 normal_col_8 varchar(30),
 normal_col_9 varchar(30),
 normal_col_10 varchar(30),
 normal_col_11 varchar(30),
 normal_col_12 varchar(30),
 normal_col_13 varchar(30),
 normal_col_14 varchar(30),
 normal_col_15 varchar(30),
 min_val1   varchar(30),
  min_val2   varchar(30),
   min_val3   varchar(30),
    min_val4   varchar(30),
     min_val5   varchar(30),
      min_val6   varchar(30),
       min_val7   varchar(30),
  max_val1   varchar(30),
  max_val2   varchar(30),
   max_val3   varchar(30),
    max_val4   varchar(30),
     max_val5   varchar(30),
      max_val6   varchar(30),
       max_val7   varchar(30)
 );
* **configs：** 

**schema.xml**  

```


```

**rule.xml**  

```


```

**server.xml**  

```


```

* **steps：**    
    step1.  execute query in dble:
```mysql
  SET TRACE=1;
  
  select *
 from sharding_2_t1
 where id = '12'
   and normal_col_1 = '0000345171'
   and normal_col_2 = '1'
   and normal_col_3 = '100'
   and normal_col_4 = '1'
   and normal_col_5 = '001'
   and normal_col_6 = ''
   and normal_col_7 = ''
   and normal_col_8 = ''
   and normal_col_9 = 1
   and normal_col_10 = 1
   and normal_col_11 = 1
   and normal_col_12 = 1
   and normal_col_13 = 0
   and normal_col_14 = 0
   and normal_col_15 = 0
   and ((normal_col_9 = 0
     or (normal_col_9 = 1
       and min_val1 <= 1
       and max_val1 >= 1)
     or (normal_col_9 = 2
       and min_val1 < 1
       and max_val1 > 1)
     or (normal_col_9 = 3
       and min_val1 <= 1
       and max_val1 > 1)
     or (normal_col_9 = 4
       and min_val1 < 1
       and max_val1 >= 1))
   and (normal_col_10 = 0
     or (normal_col_10 = 1
       and min_val2 <= 100
       and max_val2 >= 100)
     or (normal_col_10 = 2
       and min_val2 < 100
       and max_val2 > 100)
     or (normal_col_10 = 3
       and min_val2 <= 100
       and max_val2 > 100)
     or (normal_col_10 = 4
       and min_val2 < 100
       and max_val2 >= 100))
   and (normal_col_11 = 0
     or (normal_col_11 = 1
       and min_val3 <= 1
       and max_val3 >= 1)
     or (normal_col_11 = 2
       and min_val3 < 1
       and max_val3 > 1)
     or (normal_col_11 = 3
       and min_val3 <= 1
       and max_val3 > 1)
     or (normal_col_11 = 4
       and min_val3 < 1
       and max_val3 >= 1))
   and (normal_col_12 = 0
     or (normal_col_12 = 1
       and min_val4 <= 1
       and max_val4 >= 1)
     or (normal_col_12 = 2
       and min_val4 < 1
       and max_val4 > 1)
     or (normal_col_12 = 3
       and min_val4 <= 1
       and max_val4 > 1)
     or (normal_col_12 = 4
       and min_val4 < 1
       and max_val4 >= 1))
   and (normal_col_13 = 0
     or (normal_col_13 = 1
       and min_val5 <= 0
       and max_val5 >= 0)
     or (normal_col_13 = 2
       and min_val5 < 0
       and max_val5 > 0)
     or (normal_col_13 = 3
       and min_val5 <= 0
       and max_val5 > 0)
     or (normal_col_13 = 4
       and min_val5 < 0
       and max_val5 >= 0))
   and (normal_col_14 = 0
     or (normal_col_14 = 1
       and min_val6 <= 0
       and max_val6 >= 0)
     or (normal_col_14 = 2
       and min_val6 < 0
       and max_val6 > 0)
     or (normal_col_14 = 3
       and min_val6 <= 0
       and max_val6 > 0)
     or (normal_col_14 = 4
       and min_val6 < 0
       and max_val6 >= 0))
   and (normal_col_15 = 0
     or (normal_col_15 = 1
       and min_val7 <= 0
       and max_val7 >= 0)
     or (normal_col_15 = 2
       and min_val7 < 0
       and max_val7 > 0)
     or (normal_col_15 = 3
       and min_val7 <= 0
       and max_val7 > 0)
     or (normal_col_15 = 4
       and min_val7 < 0
       and max_val7 >= 0)))
 limit 0, 1
 ;
```
* **expect result：**  
    1.
* **real result：**  
    1.step1 success, but get err in dble log:
```
2020-05-08 11:58:33.344  INFO [complexQueryExecutor1] (com.actiontech.dble.statistic.stat.QueryResultDispatcher$1.run(QueryResultDispatcher.java:59)) - error:
com.alibaba.druid.sql.parser.ParserException: syntax error, expect RPAREN, actual DOTDOTDOT pos 1027, line 1, column 1025, token DOTDOTDOT
        at com.alibaba.druid.sql.parser.SQLExprParser.accept(SQLExprParser.java:2742) ~[druid-1.1.14.jar:1.1.14]
        at com.alibaba.druid.sql.parser.SQLExprParser.primary(SQLExprParser.java:366) ~[druid-1.1.14.jar:1.1.14]
        at com.alibaba.druid.sql.dialect.mysql.parser.MySqlExprParser.primary(MySqlExprParser.java:198) ~[druid-1.1.14.jar:1.1.14]
        at com.alibaba.druid.sql.parser.SQLExprParser.bitXor(SQLExprParser.java:188) ~[druid-1.1.14.jar:1.1.14]
        at com.alibaba.druid.sql.parser.SQLExprParser.multiplicative(SQLExprParser.java:275) ~[druid-1.1.14.jar:1.1.14]
        at com.alibaba.druid.sql.parser.SQLExprParser.additive(SQLExprParser.java:1920) ~[druid-1.1.14.jar:1.1.14]
        at com.alibaba.druid.sql.parser.SQLExprParser.shift(SQLExprParser.java:1958) ~[druid-1.1.14.jar:1.1.14]
        at com.alibaba.druid.sql.parser.SQLExprParser.bitAnd(SQLExprParser.java:1778) ~[druid-1.1.14.jar:1.1.14]
        at com.alibaba.druid.sql.parser.SQLExprParser.bitOr(SQLExprParser.java:1792) ~[druid-1.1.14.jar:1.1.14]
        at com.alibaba.druid.sql.parser.SQLExprParser.relational(SQLExprParser.java:2137) ~[druid-1.1.14.jar:1.1.14]
        at com.alibaba.druid.sql.parser.SQLExprParser.and(SQLExprParser.java:1981) ~[druid-1.1.14.jar:1.1.14]
        at com.alibaba.druid.sql.parser.SQLExprParser.xor(SQLExprParser.java:2054) ~[druid-1.1.14.jar:1.1.14]
        at com.alibaba.druid.sql.parser.SQLExprParser.orRest(SQLExprParser.java:2103) ~[druid-1.1.14.jar:1.1.14]
        at com.alibaba.druid.sql.parser.SQLExprParser.expr(SQLExprParser.java:163) ~[druid-1.1.14.jar:1.1.14]
        at com.alibaba.druid.sql.parser.SQLExprParser.primary(SQLExprParser.java:350) ~[druid-1.1.14.jar:1.1.14]
        at com.alibaba.druid.sql.dialect.mysql.parser.MySqlExprParser.primary(MySqlExprParser.java:198) ~[druid-1.1.14.jar:1.1.14]
        at com.alibaba.druid.sql.parser.SQLExprParser.bitXor(SQLExprParser.java:188) ~[druid-1.1.14.jar:1.1.14]
        at com.alibaba.druid.sql.parser.SQLExprParser.multiplicative(SQLExprParser.java:275) ~[druid-1.1.14.jar:1.1.14]
        at com.alibaba.druid.sql.parser.SQLExprParser.additive(SQLExprParser.java:1920) ~[druid-1.1.14.jar:1.1.14]
        at com.alibaba.druid.sql.parser.SQLExprParser.shift(SQLExprParser.java:1958) ~[druid-1.1.14.jar:1.1.14]
        at com.alibaba.druid.sql.parser.SQLExprParser.bitAnd(SQLExprParser.java:1778) ~[druid-1.1.14.jar:1.1.14]
        at com.alibaba.druid.sql.parser.SQLExprParser.bitOr(SQLExprParser.java:1792) ~[druid-1.1.14.jar:1.1.14]
        at com.alibaba.druid.sql.parser.SQLExprParser.relational(SQLExprParser.java:2137) ~[druid-1.1.14.jar:1.1.14]
        at com.alibaba.druid.sql.parser.SQLExprParser.andRest(SQLExprParser.java:1998) ~[druid-1.1.14.jar:1.1.14]
        at com.alibaba.druid.sql.parser.SQLExprParser.exprRest(SQLExprParser.java:180) ~[druid-1.1.14.jar:1.1.14]
        at com.alibaba.druid.sql.parser.SQLExprParser.expr(SQLExprParser.java:166) ~[druid-1.1.14.jar:1.1.14]
        at com.alibaba.druid.sql.parser.SQLExprParser.primary(SQLExprParser.java:350) ~[druid-1.1.14.jar:1.1.14]
        at com.alibaba.druid.sql.dialect.mysql.parser.MySqlExprParser.primary(MySqlExprParser.java:198) ~[druid-1.1.14.jar:1.1.14]
        at com.alibaba.druid.sql.parser.SQLExprParser.bitXor(SQLExprParser.java:188) ~[druid-1.1.14.jar:1.1.14]
        at com.alibaba.druid.sql.parser.SQLExprParser.multiplicative(SQLExprParser.java:275) ~[druid-1.1.14.jar:1.1.14]
        at com.alibaba.druid.sql.parser.SQLExprParser.additive(SQLExprParser.java:1920) ~[druid-1.1.14.jar:1.1.14]
        at com.alibaba.druid.sql.parser.SQLExprParser.shift(SQLExprParser.java:1958) ~[druid-1.1.14.jar:1.1.14]
        at com.alibaba.druid.sql.parser.SQLExprParser.bitAnd(SQLExprParser.java:1778) ~[druid-1.1.14.jar:1.1.14]
        at com.alibaba.druid.sql.parser.SQLExprParser.bitOr(SQLExprParser.java:1792) ~[druid-1.1.14.jar:1.1.14]
        at com.alibaba.druid.sql.parser.SQLExprParser.relational(SQLExprParser.java:2137) ~[druid-1.1.14.jar:1.1.14]
        at com.alibaba.druid.sql.parser.SQLExprParser.andRest(SQLExprParser.java:2013) ~[druid-1.1.14.jar:1.1.14]
        at com.alibaba.druid.sql.parser.SQLSelectParser.parseWhere(SQLSelectParser.java:497) ~[druid-1.1.14.jar:1.1.14]
        at com.alibaba.druid.sql.dialect.mysql.parser.MySqlSelectParser.query(MySqlSelectParser.java:195) ~[druid-1.1.14.jar:1.1.14]
        at com.alibaba.druid.sql.parser.SQLSelectParser.query(SQLSelectParser.java:236) ~[druid-1.1.14.jar:1.1.14]
        at com.alibaba.druid.sql.parser.SQLSelectParser.select(SQLSelectParser.java:88) ~[druid-1.1.14.jar:1.1.14]
        at com.alibaba.druid.sql.dialect.mysql.parser.MySqlStatementParser.parseSelect(MySqlStatementParser.java:284) ~[druid-1.1.14.jar:1.1.14]
        at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:248) ~[druid-1.1.14.jar:1.1.14]
        at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:171) ~[druid-1.1.14.jar:1.1.14]
        at com.alibaba.druid.sql.visitor.ParameterizedOutputVisitorUtils.parameterize(ParameterizedOutputVisitorUtils.java:98) ~[druid-1.1.14.jar:1.1.14]
        at com.alibaba.druid.sql.visitor.ParameterizedOutputVisitorUtils.parameterize(ParameterizedOutputVisitorUtils.java:81) ~[druid-1.1.14.jar:1.1.14]
        at com.alibaba.druid.sql.visitor.ParameterizedOutputVisitorUtils.parameterize(ParameterizedOutputVisitorUtils.java:54) ~[druid-1.1.14.jar:1.1.14]
        at com.actiontech.dble.statistic.stat.UserSqlHighStat$SqlParser.mergeSql(UserSqlHighStat.java:95) ~[dble-2.20.04.99.jar:?]
        at com.actiontech.dble.statistic.stat.UserSqlHighStat.addSql(UserSqlHighStat.java:26) ~[dble-2.20.04.99.jar:?]
        at com.actiontech.dble.statistic.stat.UserStat.update(UserStat.java:174) ~[dble-2.20.04.99.jar:?]
        at com.actiontech.dble.statistic.stat.UserStatAnalyzer.onQueryResult(UserStatAnalyzer.java:53) ~[dble-2.20.04.99.jar:?]
        at com.actiontech.dble.statistic.stat.QueryResultDispatcher$1.run(QueryResultDispatcher.java:57) [dble-2.20.04.99.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_121]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_121]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
```
* **supplements：**  
    1.

**Comment by irene-coming** [comment]
verified on dble:
5.6.29-dble-2.20.04.99-7ab10f5c88349b299e256df7a68849ebd726ee76-20200508085505
