### ISSUE TITLE
sharding value is an hextype,dble will report error or route to wrong node

### ISSUE THREAD

**Issue by yanhuqing666** [actiontech/dble#1926]
* **dble version：any version,use develop version as example **  
* **preconditions ：**  
You must konw，In MySQL   

```
mysql> SELECT x'4D7953514
+---------------+
| x'4D7953514C' |
+---------------+
| MySQL         |
+---------------+
1 row in set (0.12 sec)
```

* **configs：** 

**sharding.xml**  

```
<schema name="testdb" >
<shardingTable name="tb_jump_hash" shardingNode="dn1,dn2" function="func_jumpHash" shardingColumn="code"/>
</schema>

<!-- jumpStringHash partition for string-->
<function name="func_jumpHash" class="jumpStringHash">
	<property name="partitionCount">2</property>
	<property name="hashSlice">0:2</property>
</function>

```

* **steps：**    
step1.  
```
drop table if exists tb_jump_hash;
create table if not exists tb_jump_hash (
  id int not null,
  code varchar(250) not null,
  content varchar(250) not null,
  primary key(id)
)engine=innodb charset=utf8;
```

step2.  

```
insert into tb_jump_hash values (12,x'4D7953514C','MySQL');
```
step3. 
```
insert into tb_jump_hash values (13,'MySQL','MySQL');
```

* **expect result：**  
    1.step2 success and route to current node
* **real result：**  
    1.ERROR 1064 (HY000): Not Supported of Sharding Value EXPR :0x4D7953514C
* **supplements：**  
    1.

**Comment by quepangpang** [comment]
* **verified on version: 5.6.29-dble-9.9.9.9-51c80d4735ced4da410a3d536da4b836a182b166-20200731155021**
* **verified process:**
* **configs：**
sharding.xml
   '''
    <shardingTable name="tb_jump_hash" shardingNode="dn1,dn2" function="jumpHash" shardingColumn="code"/>
    <shardingTable name="sharding_date" shardingNode="dn1,dn2,dn3,dn4" function="date_rule" shardingColumn="create_data"/>

        <function name="date_rule" class="Date">
                <property name="dateFormat">yyyy-MM-dd</property>
                <property name="sBeginDate">2016-12-01</property>
                <property name="sEndDate">2017-01-09</property>
                <property name="sPartionDay">10</property>
                
        </function>

       <function name="jumpHash" class="jumpStringHash">
        <property name="partitionCount">2</property>
        <property name="hashSlice">0:2</property>
       </function>
   '''
* **step1:**
```
drop table if exists schema1.sharding_date;
create table sharding_date (id int,create_data date);
insert into schema1.sharding_date (id,create_data) values (1,0x323031362D31322D3031);
drop table if exists schema1. tb_jump_hash;
create table if not exists tb_jump_hash (id int not null,code varchar(250) not null,content varchar(250) not null,primary key(id))engine=innodb charset=utf8;
insert into tb_jump_hash values (11,x'74657374696e67',0x74657374696e67);
```
* **step2:**
```
select * from schema1.sharding_date where create_data=0x323031362D31322D3031;
delete from schema1.sharding_date where create_data=x'323031362D31322D3031';
```
* **step3:**
```
elect * from tb_jump_hash where code=x'74657374696e67';
delete * from tb_jump_hash  where code=x'74657374696e67';
```
* **expect result：**  
    1.step2 success and show correct results
    2.step3 success and show correct results
* **real result：**  
    1.step2:ERROR 1064 (HY000): columnValue:[B@24cd2406 Please check if the format satisfied.
    2.step3:donot show correct results
* **supplements：**  
    1.step2: dble.log
```
2020-08-03 16:07:18.831  INFO [BusinessExecutor4] (com.actiontech.dble.server.ServerConnection.executeException(ServerConnection.java:674)) - ServerConnection [frontId=6, schema=schema1, host=127.0.0.1,port=8066, user=test,txIsolation=3, autocommit=true]delete from schema1.sharding_date where create_data=x'323031362D31322D3031' err:java.lang.IllegalArgumentException: columnValue:[B@6b4c5c61 Please check if the format satisfied.
java.lang.IllegalArgumentException: columnValue:[B@6b4c5c61 Please check if the format satisfied.
	at com.actiontech.dble.route.function.PartitionByDate.calculate(PartitionByDate.java:119) ~[dble-9.9.9.9.jar:?]
	at com.actiontech.dble.route.util.RouterUtil.ruleCalculateSingleValue(RouterUtil.java:456) ~[dble-9.9.9.9.jar:?]
	at com.actiontech.dble.route.util.RouterUtil.ruleCalculate(RouterUtil.java:392) ~[dble-9.9.9.9.jar:?]
	at com.actiontech.dble.route.util.RouterUtil.findRouterWithConditionsForShardingTable(RouterUtil.java:947) ~[dble-9.9.9.9.jar:?]
	at com.actiontech.dble.route.util.RouterUtil.findRouterForTablesInOneSchema(RouterUtil.java:927) ~[dble-9.9.9.9.jar:?]
	at com.actiontech.dble.route.util.RouterUtil.tryRouteForOneTable(RouterUtil.java:835) ~[dble-9.9.9.9.jar:?]
	at com.actiontech.dble.route.util.RouterUtil.tryRouteForTables(RouterUtil.java:649) ~[dble-9.9.9.9.jar:?]
	at com.actiontech.dble.route.util.RouterUtil.routeFromParser(RouterUtil.java:201) ~[dble-9.9.9.9.jar:?]
	at com.actiontech.dble.route.impl.DefaultRouteStrategy.routeNormalSqlWithAST(DefaultRouteStrategy.java:86) ~[dble-9.9.9.9.jar:?]
	at com.actiontech.dble.route.impl.AbstractRouteStrategy.route(AbstractRouteStrategy.java:49) ~[dble-9.9.9.9.jar:?]
	at com.actiontech.dble.singleton.RouteService.route(RouteService.java:104) ~[dble-9.9.9.9.jar:?]
	at com.actiontech.dble.singleton.RouteService.route(RouteService.java:35) ~[dble-9.9.9.9.jar:?]
	at com.actiontech.dble.server.ServerConnection.routeEndExecuteSQL(ServerConnection.java:422) [dble-9.9.9.9.jar:?]
	at com.actiontech.dble.server.ServerConnection.execute(ServerConnection.java:385) [dble-9.9.9.9.jar:?]
	at com.actiontech.dble.server.ServerQueryHandler.query(ServerQueryHandler.java:183) [dble-9.9.9.9.jar:?]
	at com.actiontech.dble.server.ServerConnection.handlerQuery(ServerConnection.java:814) [dble-9.9.9.9.jar:?]
	at com.actiontech.dble.net.FrontendConnection.query(FrontendConnection.java:207) [dble-9.9.9.9.jar:?]
	at com.actiontech.dble.net.FrontendConnection.query(FrontendConnection.java:187) [dble-9.9.9.9.jar:?]
	at com.actiontech.dble.net.handler.ShardingUserCommandHandler.handleData(ShardingUserCommandHandler.java:75) [dble-9.9.9.9.jar:?]
	at com.actiontech.dble.net.handler.FrontendCommandHandler.handle(FrontendCommandHandler.java:60) [dble-9.9.9.9.jar:?]
	at com.actiontech.dble.net.handler.FrontEndHandlerRunnable.run(FrontEndHandlerRunnable.java:41) [dble-9.9.9.9.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_121]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
Caused by: java.text.ParseException: Unparseable date: "[B@6b4c5c61"
	at java.text.DateFormat.parse(DateFormat.java:366) ~[?:1.8.0_121]
	at com.actiontech.dble.route.function.PartitionByDate.calculate(PartitionByDate.java:107) ~[dble-9.9.9.9.jar:?]
	... 23 more
```

    2.setp3: 
```
mysql> explain insert into tb_jump_hash values (11,x'74657374696e67',0x74657374696e67);
+---------------+----------+--------------------------------------------------------------------------+
| SHARDING_NODE | TYPE     | SQL/REF                                                                  |
+---------------+----------+--------------------------------------------------------------------------+
| dn2           | BASE SQL | INSERT INTO tb_jump_hash VALUES (11, 0x74657374696e67, 0x74657374696e67) |
+---------------+----------+--------------------------------------------------------------------------+

mysql> explain select * from tb_jump_hash where code=x'74657374696e67';
+---------------+----------+---------------------------------------------------------+
| SHARDING_NODE | TYPE     | SQL/REF                                                 |
+---------------+----------+---------------------------------------------------------+
| dn1           | BASE SQL | select * from tb_jump_hash where code=x'74657374696e67' |
+---------------+----------+---------------------------------------------------------+
```

**Comment by quepangpang** [comment]
verified on version: 5.6.29-dble-3.20.07.99-bb66c9d3ab238f480f3d620e94c962d8cd229ba5-20200804114836

**Comment by PanternBao** [comment]
* **step1:**

drop table if exists schema1. sharding_4_t1;
create table sharding_4_t1 (id int,file blob);

* **step2:**

insert into sharding_4_t1 values(1,x'exc');

* **expect result：**
insert ok
* **real result：**
ERROR 1054 (42S22): Unknown column '0xexc' in 'field list',because the statement changes to 'INSERT INTO tb_hash_sharding_er2
VALUES (1, 0xexc)'
