### ISSUE TITLE
 The query needs to be printed in the log，when management commands not supported by druid

### ISSUE THREAD

**Issue by FlyingMao** [actiontech/dble#1977]
* **dble version：**  
dble-9.9.9.9-78b92f823d9a410a03e90152003576d3ffa2df0f-20200727014231
* **preconditions ：**  
dble log level：info 
* **configs：** 

**schema.xml**  

```


```

**rule.xml**  

```


```

**server.xml**  

```


```

* **steps：**    
    step1.  execute query in manager port
```
mysql> show VARINT;
ERROR 1105 (HY000): TODO pos 11, line 1, column 5, token IDENTIFIER VARINT
```
   step2.  check log in dble.log
* **expect result：**  
    1.  the query can be found in dble.log
* **real result：**  
    1.
```
2020-07-29 03:28:21.706  INFO [BusinessExecutor1] (com.actiontech.dble.net.handler.FrontendCommandHandler.handle(FrontendCommandHandler.java:67)) - There is an error you may need know.
com.alibaba.druid.sql.parser.ParserException: TODO pos 11, line 1, column 5, token IDENTIFIER VARINT
	at com.alibaba.druid.sql.dialect.mysql.parser.MySqlStatementParser.parseShow(MySqlStatementParser.java:2071) ~[druid-1.1.14.jar:1.1.14]
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:320) ~[druid-1.1.14.jar:1.1.14]
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatement(SQLStatementParser.java:2853) ~[druid-1.1.14.jar:1.1.14]
	at com.actiontech.dble.manager.handler.ShowHandler.isSupportShow(ShowHandler.java:273) ~[dble-9.9.9.9.jar:?]
	at com.actiontech.dble.manager.handler.ShowHandler.handle(ShowHandler.java:255) ~[dble-9.9.9.9.jar:?]
	at com.actiontech.dble.manager.ManagerQueryHandler.query(ManagerQueryHandler.java:62) ~[dble-9.9.9.9.jar:?]
	at com.actiontech.dble.manager.ManagerConnection.handlerQuery(ManagerConnection.java:43) ~[dble-9.9.9.9.jar:?]
	at com.actiontech.dble.net.FrontendConnection.query(FrontendConnection.java:207) ~[dble-9.9.9.9.jar:?]
	at com.actiontech.dble.net.FrontendConnection.query(FrontendConnection.java:187) ~[dble-9.9.9.9.jar:?]
	at com.actiontech.dble.net.handler.ManagerCommandHandler.handleData(ManagerCommandHandler.java:26) ~[dble-9.9.9.9.jar:?]
	at com.actiontech.dble.net.handler.FrontendCommandHandler.handle(FrontendCommandHandler.java:60) [dble-9.9.9.9.jar:?]
	at com.actiontech.dble.net.handler.FrontEndHandlerRunnable.run(FrontEndHandlerRunnable.java:41) [dble-9.9.9.9.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_131]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_131]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]

```
* **supplements：**  
    1.

**Comment by quepangpang** [comment]
verified on dble:5.6.29-dble-9.9.9.9-37105477a83b9d0719a218b86b614bff84f3354a-20200803075033
the result:
```
2020-08-04 11:15:58.505 DEBUG [BusinessExecutor5] (com.actiontech.dble.net.FrontendConnection.query(FrontendConnection.java:198)) - com.actiontech.dble.manager.ManagerConnection@4b79e67f show VARINT
2020-08-04 11:15:58.505 DEBUG [BusinessExecutor5] (com.actiontech.dble.manager.ManagerQueryHandler.query(ManagerQueryHandler.java:45)) - com.actiontech.dble.manager.ManagerConnection@4b79e67fshow VARINT
2020-08-04 11:15:58.505  WARN [BusinessExecutor5] (com.actiontech.dble.manager.handler.ShowHandler.handle(ShowHandler.java:276)) - Unsupported show:show VARINT
```
