### ISSUE TITLE
handle data error: com.actiontech.dble.plan.common.exception.TempTableException: temptable too much rows,[rows size is 8001], conn info

### ISSUE THREAD

**Issue by sunshinecb** [actiontech/dble#2005]
* **dble version：*最新*  
* **preconditions ：**  
no
* **configs：** 

**schema.xml**  

```

<schema name="kfxt" sqlMaxLimit="1000">
        <table name="ods_cur_hdvd" dataNode="dn1" /> <!-- one year -->
		<table name="ods_dfs_gantry_transaction" dataNode="dn1" /> <!-- 0.5 year -->
		<table name="ods_dfs_gantry_travelimage" dataNode="dn1" /> <!-- 0.5 year -->
		<table name="ods_entry_jour" dataNode="dn1" /> <!-- one year -->
		<table name="ods_exit_jour" dataNode="dn1" /> <!-- one year -->
		
		<!-- kfxt -->
		<table name="t_incremental_log" dataNode="dn_kfxt" />
		<table name="sys_dictionary" dataNode="dn_kfxt" />
		<table name="t_statistic_service_area" dataNode="dn_kfxt" />
		<table name="t_station"  dataNode="dn_kfxt" />
		<table name="t_service_area" dataNode="dn_kfxt" />
		<table name="t_service_area_day" dataNode="dn_kfxt" />

		
		
    </schema>

    
    <!-- datanode -->
    <dataNode name="dn1" dataHost="dataHost1" database="db1" />
	<!-- kefu -->
	<dataNode name="dn_kfxt" dataHost="dataHost1" database="basedb" />


    <!-- datahost -->
    <dataHost name="dataHost1" maxCon="1000" minCon="10" balance="0" slaveThreshold="100">
        <heartbeat>select 1</heartbeat>
        <writeHost host="hostM1" url="localhost:3306" user="root" password="root">
        </writeHost>
    </dataHost>
```

**rule.xml**  

```


```

**server.xml**  

```


```

* **steps：**    
    SELECT
	a.*
FROM
	ods_cur_hdvd a
LEFT JOIN t_service_area b ON a.ID = b.device_id
WHERE
	a.ds = '2020-07-30' 
* **expect result：**  
    
* **real result：**  
    1.[Err] 1003 - Backend connect Error, Connection{DataHost[172.24.4.84:3306],Schema[db1]} refused
* **supplements：**  
    1.2020-08-06 14:45:09.095  WARN [complexQueryExecutor1] (com.actiontech.dble.backend.mysql.nio.handler.query.impl.BaseSelectHandler.connectionError(BaseSelectHandler.java:152)) - Backend connect Error, Connection info:MySQLConnection [backendId=13, lastTime=1596696306991, user=ddb_mycat, schema=db1, old schema=db1, borrowed=true, fromSlaveDB=false, mysqlId=51186,character_set_client=utf8mb4,character_set_results=utf8mb4,collation_connection=utf8mb4_general_ci, txIsolation=3, autocommit=true, attachment=dn1{select `a`.`ds`,`a`.`CARNUM`,`a`.`CARNUMCOLOR`,`a`.`ID` from  `ods_cur_hdvd` `a` where (`a`.`CARNUM` <> '') AND (a.CARNUM IS NOT UNKNOWN) order by `a`.`ID` ASC}.0, respHandler=com.actiontech.dble.backend.mysql.nio.handler.query.impl.BaseSelectHandler@2bef1853, host=172.24.4.84, port=3306, statusSync=null, writeQueue=0, xaStatus=0, PROFILING=1]
com.actiontech.dble.plan.common.exception.TempTableException: temptable too much rows,[rows size is 8001], conn info [MySQLConnection [backendId=13, lastTime=1596696306991, user=ddb_mycat, schema=db1, old schema=db1, borrowed=true, fromSlaveDB=false, mysqlId=51186,character_set_client=utf8mb4,character_set_results=utf8mb4,collation_connection=utf8mb4_general_ci, txIsolation=3, autocommit=true, attachment=dn1{select `a`.`ds`,`a`.`CARNUM`,`a`.`CARNUMCOLOR`,`a`.`ID` from  `ods_cur_hdvd` `a` where (`a`.`CARNUM` <> '') AND (a.CARNUM IS NOT UNKNOWN) order by `a`.`ID` ASC}.0, respHandler=com.actiontech.dble.backend.mysql.nio.handler.query.impl.BaseSelectHandler@2bef1853, host=172.24.4.84, port=3306, statusSync=null, writeQueue=0, xaStatus=0, PROFILING=1]] !
	at com.actiontech.dble.backend.mysql.nio.handler.query.impl.TempTableHandler.rowResponse(TempTableHandler.java:104) ~[dble-2.20.04.0.jar:?]
	at com.actiontech.dble.backend.mysql.nio.handler.query.impl.MultiNodeEasyMergeHandler.rowResponse(MultiNodeEasyMergeHandler.java:79) ~[dble-2.20.04.0.jar:?]
	at com.actiontech.dble.backend.mysql.nio.handler.query.impl.BaseSelectHandler.rowResponse(BaseSelectHandler.java:123) [dble-2.20.04.0.jar:?]
	at com.actiontech.dble.backend.mysql.nio.MySQLConnectionHandler.handleRowPacket(MySQLConnectionHandler.java:210) ~[dble-2.20.04.0.jar:?]
	at com.actiontech.dble.backend.mysql.nio.MySQLConnectionHandler.handleData(MySQLConnectionHandler.java:134) [dble-2.20.04.0.jar:?]
	at com.actiontech.dble.net.handler.BackendAsyncHandler.handleInnerData(BackendAsyncHandler.java:100) ~[dble-2.20.04.0.jar:?]
	at com.actiontech.dble.net.handler.BackendAsyncHandler.access$000(BackendAsyncHandler.java:19) ~[dble-2.20.04.0.jar:?]
	at com.actiontech.dble.net.handler.BackendAsyncHandler$1.run(BackendAsyncHandler.java:51) [dble-2.20.04.0.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_73]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_73]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_73]

**Comment by yanhuqing666** [comment]
not a bug,you can change your config ,see https://actiontech.github.io/dble-docs-cn/A.Faq/ErrorCode/Content/NestLoopParametersLeadToTemptableException.html
