### ISSUE TITLE
Error on `index_hint_list` which contains multiple index hints

### ISSUE THREAD

**Issue by FlyingMao** [actiontech/dble#272]
steps:
```
mysql> SELECT * FROM a_test  use INDEX (k_1) use INDEX (pad_index);
ERROR 1064 (HY000): error INDEX INDEX
```
log:
```
2017-09-20 17:36:32.446  INFO [BusinessExecutor2] (com.actiontech.dble.server.ServerConnection.executeException(ServerConnection.java:278)) - ServerConnection [id=11, schema=mytest, host=127.0.0.1, user=test,txIsolation=3, autocommit=true, schema=mytest]SELECT * FROM a_test  force INDEX (k_1) ignore INDEX (pad_index) err:syntax error, error in :'nore INDEX (pad_index)',expect INDEX, actual INDEX INDEX
2017-09-20 17:39:53.286 ERROR [BusinessExecutor7] (com.actiontech.dble.route.impl.DefaultRouteStrategy.parserSQL(DefaultRouteStrategy.java:44)) - routeNormalSqlWithAST
com.alibaba.druid.sql.parser.ParserException: error INDEX INDEX
	at com.alibaba.druid.sql.parser.SQLExprParser.name(SQLExprParser.java:1025) ~[druid-1.0.31.jar:1.0.31]
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseUse(SQLStatementParser.java:415) ~[druid-1.0.31.jar:1.0.31]
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:270) ~[druid-1.0.31.jar:1.0.31]
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:84) ~[druid-1.0.31.jar:1.0.31]
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:80) ~[druid-1.0.31.jar:1.0.31]
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:75) ~[druid-1.0.31.jar:1.0.31]
	at com.actiontech.dble.route.impl.DefaultRouteStrategy.parserSQL(DefaultRouteStrategy.java:38) [dble-2.17.08.0.jar:?]
	at com.actiontech.dble.route.impl.DefaultRouteStrategy.routeNormalSqlWithAST(DefaultRouteStrategy.java:57) [dble-2.17.08.0.jar:?]
	at com.actiontech.dble.route.impl.AbstractRouteStrategy.route(AbstractRouteStrategy.java:45) [dble-2.17.08.0.jar:?]
	at com.actiontech.dble.route.RouteService.route(RouteService.java:105) [dble-2.17.08.0.jar:?]
	at com.actiontech.dble.server.ServerConnection.routeEndExecuteSQL(ServerConnection.java:232) [dble-2.17.08.0.jar:?]
	at com.actiontech.dble.server.ServerConnection.execute(ServerConnection.java:176) [dble-2.17.08.0.jar:?]
	at com.actiontech.dble.server.handler.SelectHandler.handle(SelectHandler.java:96) [dble-2.17.08.0.jar:?]
	at com.actiontech.dble.server.ServerQueryHandler.query(ServerQueryHandler.java:62) [dble-2.17.08.0.jar:?]
	at com.actiontech.dble.net.FrontendConnection.query(FrontendConnection.java:299) [dble-2.17.08.0.jar:?]
	at com.actiontech.dble.net.FrontendConnection.query(FrontendConnection.java:317) [dble-2.17.08.0.jar:?]
	at com.actiontech.dble.net.handler.FrontendCommandHandler.handleData(FrontendCommandHandler.java:65) [dble-2.17.08.0.jar:?]
	at com.actiontech.dble.net.handler.FrontendCommandHandler$1.run(FrontendCommandHandler.java:117) [dble-2.17.08.0.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110) [?:1.7.0_05]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603) [?:1.7.0_05]
	at java.lang.Thread.run(Thread.java:722) [?:1.7.0_05]
2017-09-20 17:39:53.287  INFO [BusinessExecutor7] (com.actiontech.dble.server.ServerConnection.executeException(ServerConnection.java:278)) - ServerConnection [id=11, schema=mytest, host=127.0.0.1, user=test,txIsolation=3, autocommit=true, schema=mytest]SELECT * FROM a_test  use INDEX (k_1) use INDEX (pad_index) err:error INDEX INDEX
```

**Comment by ditdb** [comment]
这个问题修正已经提交到alibaba/druid上，并被其合并，见#2136 。
另外，一般不会这么用，最好把相同目的的索引写到一起。比如：use INDEX (k_1, pad_index);

**Comment by FlyingMao** [comment]
for tester:

suggest autotest position: sqls/select/reference.sql (reference line 37)

**verified version：** 5.6.29-dble-9.9.9.9-359645c-20181029082136
