### ISSUE TITLE
`prepare` one of the nodes on sharding table failed,xa transaction hangs

### ISSUE THREAD

**Issue by FlyingMao** [actiontech/dble#289]
steps
```
1. set autocommit=0;                                                                                                                                                                                          
2. set xa=on;
3. update sbtest1 set pad=1;
4.commit;
5.kill back-end connection on one of the nodes
```
dble logs:
```
2017-10-16 10:42:04.390 DEBUG [BusinessExecutor0] (com.actiontech.dble.net.FrontendConnection.query(FrontendConnection.java:297)) - ServerConnection [id=1, schema=mytest, host=127.0.0.1, user=test,txIsolation=3, autocommit=false, schema=mytest] commit
2017-10-16 10:42:04.390 DEBUG [BusinessExecutor0] (com.actiontech.dble.server.ServerQueryHandler.query(ServerQueryHandler.java:38)) - ServerConnection [id=1, schema=mytest, host=127.0.0.1, user=test,txIsolation=3, autocommit=false, schema=mytest]commit
2017-10-16 10:42:04.409 DEBUG [BusinessExecutor6] (com.actiontech.dble.backend.mysql.nio.handler.transaction.xa.XACommitNodesHandler.debugCommitDelay(XACommitNodesHandler.java:340)) - before xa 'XA PREPARED' sleep time = 50000
2017-10-16 10:42:13.763 DEBUG [$_NIOREACTOR-1-RW] (com.actiontech.dble.net.AbstractConnection.close(AbstractConnection.java:481)) - close connection,reason:stream closed ,MySQLConnection [id=22, lastTime=1508121724396, user=test, schema=db1, old schema=db1, borrowed=true, fromSlaveDB=false, threadId=330,character_set_client=utf8,character_set_results=utf8,collation_connection=utf8_general_ci, txIsolation=3, autocommit=false, attachment=dn1{update sbtest1 set pad=1}.0, respHandler=com.actiontech.dble.backend.mysql.nio.handler.transaction.xa.XACommitNodesHandler@5832cd58, host=10.186.24.45, port=3307, statusSync=null, writeQueue=0, modifiedSQLExecuted=true]
2017-10-16 10:42:16.006 DEBUG [$_NIOREACTOR-2-RW] (com.actiontech.dble.net.AbstractConnection.close(AbstractConnection.java:481)) - close connection,reason:stream closed ,MySQLConnection [id=23, lastTime=1508121724396, user=test, schema=db2, old schema=db2, borrowed=true, fromSlaveDB=false, threadId=331,character_set_client=utf8,character_set_results=utf8,collation_connection=utf8_general_ci, txIsolation=3, autocommit=false, attachment=dn3{update sbtest1 set pad=1}.0, respHandler=com.actiontech.dble.backend.mysql.nio.handler.transaction.xa.XACommitNodesHandler@5832cd58, host=10.186.24.45, port=3307, statusSync=null, writeQueue=0, modifiedSQLExecuted=true]
2017-10-16 10:42:54.410 DEBUG [BusinessExecutor6] (com.actiontech.dble.backend.mysql.nio.handler.transaction.xa.XACommitNodesHandler.debugCommitDelay(XACommitNodesHandler.java:342)) - before xa 'XA PREPARED' sleep finished 50000
2017-10-16 10:42:54.411 DEBUG [BusinessExecutor6] (com.actiontech.dble.net.NIOSocketWR.doNextWriteCheck(NIOSocketWR.java:62)) - caught err:
java.nio.channels.ClosedChannelException: null
	at sun.nio.ch.SocketChannelImpl.ensureWriteOpen(SocketChannelImpl.java:249) ~[?:1.7.0_05]
	at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:440) ~[?:1.7.0_05]
	at com.actiontech.dble.net.NIOSocketWR.write0(NIOSocketWR.java:102) ~[dble-2.17.09.0-dev.jar:?]
	at com.actiontech.dble.net.NIOSocketWR.doNextWriteCheck(NIOSocketWR.java:46) [dble-2.17.09.0-dev.jar:?]
	at com.actiontech.dble.net.AbstractConnection.write(AbstractConnection.java:409) [dble-2.17.09.0-dev.jar:?]
	at com.actiontech.dble.net.mysql.CommandPacket.write(CommandPacket.java:103) [dble-2.17.09.0-dev.jar:?]
	at com.actiontech.dble.backend.mysql.nio.MySQLConnection.sendQueryCmd(MySQLConnection.java:280) [dble-2.17.09.0-dev.jar:?]
	at com.actiontech.dble.backend.mysql.nio.MySQLConnection.execCmd(MySQLConnection.java:532) [dble-2.17.09.0-dev.jar:?]
	at com.actiontech.dble.backend.mysql.nio.handler.transaction.xa.XACommitNodesHandler.preparePhase(XACommitNodesHandler.java:98) [dble-2.17.09.0-dev.jar:?]
	at com.actiontech.dble.backend.mysql.nio.handler.transaction.xa.XACommitNodesHandler.executeCommit(XACommitNodesHandler.java:61) [dble-2.17.09.0-dev.jar:?]
	at com.actiontech.dble.backend.mysql.nio.handler.transaction.AbstractCommitNodesHandler.commit(AbstractCommitNodesHandler.java:51) [dble-2.17.09.0-dev.jar:?]
	at com.actiontech.dble.backend.mysql.nio.handler.transaction.xa.XACommitNodesHandler.nextParse(XACommitNodesHandler.java:274) [dble-2.17.09.0-dev.jar:?]
	at com.actiontech.dble.backend.mysql.nio.handler.transaction.xa.XACommitNodesHandler.okResponse(XACommitNodesHandler.java:124) [dble-2.17.09.0-dev.jar:?]
	at com.actiontech.dble.backend.mysql.nio.MySQLConnectionHandler.handleOkPacket(MySQLConnectionHandler.java:139) [dble-2.17.09.0-dev.jar:?]
	at com.actiontech.dble.backend.mysql.nio.MySQLConnectionHandler.handleData(MySQLConnectionHandler.java:77) [dble-2.17.09.0-dev.jar:?]
	at com.actiontech.dble.net.handler.BackendAsyncHandler$1.run(BackendAsyncHandler.java:37) [dble-2.17.09.0-dev.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110) [?:1.7.0_05]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603) [?:1.7.0_05]
	at java.lang.Thread.run(Thread.java:722) [?:1.7.0_05]
2017-10-16 10:42:58.041  INFO [Timer0] (com.actiontech.dble.backend.datasource.PhysicalDatasource.getConnection(PhysicalDatasource.java:380)) - no ilde connection in pool,create new connection for hostM1 of schema db1
```

**Comment by zhunina** [comment]
fixed
