### ISSUE TITLE
dble deadlock

### ISSUE THREAD

**Issue by hiramwu** [actiontech/dble#2966]
* **dble version：**  dble-3.21.06.0-tag
* **preconditions ：**  

Found one Java-level deadlock:
=============================
"complexQueryExecutor365":
  waiting for ownable synchronizer 0x00000000b9c606e8, (a java.util.concurrent.locks.ReentrantLock$NonfairSync),
  which is held by "complexQueryExecutor364"
"complexQueryExecutor364":
  waiting to lock monitor 0x00007fdc90026ac8 (object 0x00000000b8b0da78, a com.actiontech.dble.net.connection.BackendConnection),
  which is held by "complexQueryExecutor365"

"complexQueryExecutor365" #495 daemon prio=5 os_prio=0 tid=0x00007fdc88014000 nid=0x2ac0e8 waiting on condition [0x00007fdcbe7e6000]
   java.lang.Thread.State: WAITING (parking)
    at sun.misc.Unsafe.park(Native Method)
    - parking to wait for  <0x00000000b9c606e8> (a java.util.concurrent.locks.ReentrantLock$NonfairSync)
    at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
    at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:836)
    at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireQueued(AbstractQueuedSynchronizer.java:870)
    at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(AbstractQueuedSynchronizer.java:1199)
    at java.util.concurrent.locks.ReentrantLock$NonfairSync.lock(ReentrantLock.java:209)
    at java.util.concurrent.locks.ReentrantLock.lock(ReentrantLock.java:285)
    at com.actiontech.dble.net.handler.BackEndRecycleRunnable.signal(BackEndRecycleRunnable.java:55)
    at com.actiontech.dble.services.BackendService.signal(BackendService.java:257)
    at com.actiontech.dble.services.BackendService.backendSpecialCleanUp(BackendService.java:252)
    at com.actiontech.dble.services.BackendService.cleanup(BackendService.java:206)
    at com.actiontech.dble.net.connection.AbstractConnection.cleanup(AbstractConnection.java:465)
    - locked <0x00000000b8b0da78> (a com.actiontech.dble.net.connection.BackendConnection)
    at com.actiontech.dble.net.connection.PooledConnection.cleanup(PooledConnection.java:43)
    - locked <0x00000000b8b0da78> (a com.actiontech.dble.net.connection.BackendConnection)
    at com.actiontech.dble.net.connection.AbstractConnection.closeImmediatelyInner(AbstractConnection.java:156)
    at com.actiontech.dble.net.connection.AbstractConnection.close(AbstractConnection.java:264)
    at com.actiontech.dble.net.connection.BackendConnection.close(BackendConnection.java:99)
    - locked <0x00000000b8b0da78> (a com.actiontech.dble.net.connection.BackendConnection)
    at com.actiontech.dble.net.impl.nio.NIOSocketWR.write0(NIOSocketWR.java:273)
    at com.actiontech.dble.net.impl.nio.NIOSocketWR.doNextWriteCheck(NIOSocketWR.java:67)
    at com.actiontech.dble.net.connection.BackendConnection.writeClose(BackendConnection.java:153)
    at com.actiontech.dble.net.connection.BackendConnection.closeGracefullyPassive(BackendConnection.java:147)
    at com.actiontech.dble.net.connection.BackendConnection.close(BackendConnection.java:92)
    - locked <0x00000000b8b0da78> (a com.actiontech.dble.net.connection.BackendConnection)
    at com.actiontech.dble.services.BackendService.handleDataError(BackendService.java:195)
    at com.actiontech.dble.services.BackendService.lambda$doHandle$36(BackendService.java:103)
    at com.actiontech.dble.services.BackendService$$Lambda$39/1943893207.run(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)

	
	
	
"complexQueryExecutor364" #494 daemon prio=5 os_prio=0 tid=0x00007fdc9c015000 nid=0x2a7f02 waiting for monitor entry [0x00007fdc830ef000]
   java.lang.Thread.State: BLOCKED (on object monitor)
    at com.actiontech.dble.net.connection.AbstractConnection.getService(AbstractConnection.java:372)
    - waiting to lock <0x00000000b8b0da78> (a com.actiontech.dble.net.connection.BackendConnection)
    at com.actiontech.dble.net.connection.BackendConnection.businessClose(BackendConnection.java:54)
    at com.actiontech.dble.net.handler.BackEndRecycleRunnable.run(BackEndRecycleRunnable.java:36)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    at java.lang.Thread.run(Thread.java:748)

   Locked ownable synchronizers:
    - <0x00000000b50363c8> (a java.util.concurrent.ThreadPoolExecutor$Worker)
    - <0x00000000b9c606e8> (a java.util.concurrent.locks.ReentrantLock$NonfairSync)

**Comment by hiramwu** [comment]
save as https://github.com/actiontech/dble/pull/2959
