### ISSUE TITLE
XA error in log when start

### ISSUE THREAD

**Issue by zhunina** [actiontech/dble#305]
```
2017-10-25 13:14:13.447  WARN [WrapperSimpleAppMain] (com.actiontech.ushard.backend.mysql.xa.recovery.impl.FileSystemRepository.getAllCoordinatorLogEntries(FileSystemRepository.java:103)) - FileSystemRepository.getAllCoordinatorLogEntries error
java.io.FileNotFoundException: ./tmlogs/tmlog-1.log (No such file or directory)
        at java.io.FileInputStream.open0(Native Method) ~[?:1.8.0_111]
        at java.io.FileInputStream.open(FileInputStream.java:195) ~[?:1.8.0_111]
        at java.io.FileInputStream.<init>(FileInputStream.java:138) ~[?:1.8.0_111]
        at java.io.FileInputStream.<init>(FileInputStream.java:93) ~[?:1.8.0_111]
        at com.actiontech.ushard.backend.mysql.xa.VersionedFile.openLastValidVersionForReading(VersionedFile.java:124) ~[UShard-2.17.08.1.jar:?]
        at com.actiontech.ushard.backend.mysql.xa.recovery.impl.FileSystemRepository.getAllCoordinatorLogEntries(FileSystemRepository.java:99) [UShard-2.17.08.1.jar:?]
        at com.actiontech.ushard.UshardServer.getCoordinatorLogEntries(UshardServer.java:945) [UShard-2.17.08.1.jar:?]
        at com.actiontech.ushard.UshardServer.performXARecoveryLog(UshardServer.java:865) [UShard-2.17.08.1.jar:?]
        at com.actiontech.ushard.UshardServer.startup(UshardServer.java:403) [UShard-2.17.08.1.jar:?]
        at com.actiontech.ushard.UshardStartup.main(UshardStartup.java:42) [UShard-2.17.08.1.jar:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_111]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_111]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_111]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_111]
        at org.tanukisoftware.wrapper.WrapperSimpleApp.run(WrapperSimpleApp.java:240) [wrapper.jar:3.2.3]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
```
However,I have never used 'XA' transaction.

**Comment by zhunina** [comment]
fixed
