### ISSUE TITLE
NPE cause of logging in client by manager user

### ISSUE THREAD

**Issue by zhunina** [actiontech/dble#324]
```
2017-11-13 16:33:47.991  WARN [BusinessExecutor4] (com.actiontech.dble.net.handler.FrontendCommandHandler$1.run(FrontendCommandHandler.java:123)) - Maybe occur a bug, please check it.
java.lang.NullPointerException: null
        at com.actiontech.dble.server.response.ShowTables.response(ShowTables.java:73) ~[dble-2.17.09.0-dev.jar:?]
        at com.actiontech.dble.server.handler.ShowHandler.handle(ShowHandler.java:33) ~[dble-2.17.09.0-dev.jar:?]
        at com.actiontech.dble.server.ServerQueryHandler.query(ServerQueryHandler.java:65) ~[dble-2.17.09.0-dev.jar:?]
        at com.actiontech.dble.net.FrontendConnection.query(FrontendConnection.java:314) ~[dble-2.17.09.0-dev.jar:?]
        at com.actiontech.dble.net.FrontendConnection.query(FrontendConnection.java:332) ~[dble-2.17.09.0-dev.jar:?]
        at com.actiontech.dble.net.handler.FrontendCommandHandler.handleData(FrontendCommandHandler.java:66) ~[dble-2.17.09.0-dev.jar:?]
        at com.actiontech.dble.net.handler.FrontendCommandHandler$1.run(FrontendCommandHandler.java:118) [dble-2.17.09.0-dev.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_151]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_151]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
```

**Comment by zhunina** [comment]
fixed
