### ISSUE TITLE
"table _name doesn't exist" by blob.length()

### ISSUE THREAD

**Issue by zhunina** [actiontech/dble#325]
```
public class TestBlob {
	 Connection conn=null;
	 Blob b=null;
	 File f=null;
	 FileInputStream fis=null;
	 PreparedStatement pstmt=null;
	 ResultSet rs=null;
	 int insert_rows;
 public  Connection bulidConnection(String url){
	  	Connection conn=null;
	  	String Url=url;
		String user = "test";
		String password = "test";
		Properties info = new Properties();
		info.setProperty("user", user);
		info.setProperty("password", password);
       try {
           Class.forName("com.mysql.jdbc.Driver").newInstance();
           System.out.println("loadDriver successfully");
       } catch (Exception ex) {
       }
       
       try {
       	conn = DriverManager.getConnection(Url, info);
           System.out.println("create connecton successfully:"+conn);
          
       } catch (SQLException ex) {
           System.out.println("SQLException: " + ex.getMessage());
           System.out.println("SQLState: " + ex.getSQLState());
           System.out.println("VendorError: " + ex.getErrorCode());
   }	
       return conn;
 }
 @BeforeMethod
 public  void initializationBlob() throws SQLException, IOException{
	String urldble="jdbc:mysql://10.186.21.74:8066?jdbcCompliantTruncation=false&emulateLocators=true&useServerPrepStmts=true";
	conn=bulidConnection(urldble);
	f=new File("C:\\Users\\user\\Pictures\\photo.png");
	fis=new FileInputStream(f);
	String drop_sql="DROP TABLE IF EXISTS  aly_test";
	String create_blob_sql="CREATE TABLE  aly_test( id int primary key,data LONGBLOB)";
	String insert_blob_sql="insert into aly_test(id,data) values(0,?)";
	String query_sql="select id,'data' as blob_data from aly_test";
	conn.setCatalog("testdb");
	conn.createStatement().execute(drop_sql);
	conn.createStatement().execute(create_blob_sql);
	pstmt=conn.prepareStatement(insert_blob_sql);
	pstmt.setBinaryStream(1, fis,fis.available());
	insert_rows=pstmt.executeUpdate();
	assert insert_rows==insert_rows1;
	pstmt=conn.prepareStatement(query_sql);
	rs=pstmt.executeQuery();
	while(rs.next()){
		b = rs.getBlob("blob_data");
	}
 }
 @Test
 public void testBlobLength() throws SQLException{
	 Long l=b.length();
	 Long l1=b1.length();
	 System.out.println("l:"+l);
	 System.out.println("l1："+l1);
	 assert l==l1;
 }
}

```
```
com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table `db2`.`aly_test` doesn't exist
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:404)
	at com.mysql.jdbc.Util.getInstance(Util.java:387)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:941)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3870)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3806)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2470)
	at com.mysql.jdbc.ServerPreparedStatement.serverExecute(ServerPreparedStatement.java:1274)
	at com.mysql.jdbc.ServerPreparedStatement.executeInternal(ServerPreparedStatement.java:780)
	at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:1962)
	at com.mysql.jdbc.BlobFromLocator.length(BlobFromLocator.java:304)
	at jdbc.TestBlob.testBlobLength(TestBlob.java:120)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:100)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:646)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:811)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1129)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:746)
	at org.testng.TestRunner.run(TestRunner.java:600)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1264)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1189)
	at org.testng.TestNG.runSuites(TestNG.java:1104)
	at org.testng.TestNG.run(TestNG.java:1076)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:152)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:57)

```

**Comment by yanhuqing666** [comment]
show databases/tables will not support metaData

**Comment by zhunina** [comment]
fixed
