### ISSUE TITLE
配置文件报错提示不详

### ISSUE THREAD

**Issue by kevinbin** [actiontech/dble#3302]
望提示错误信息中增加文件名，缩小排查范围。

```
2022-06-26 07:56:44.619  INFO [main] (com.actiontech.dble.DbleServer.startup(DbleServer.java:126)) - ===========================================DBLE SERVER STARTING===================================
2022-06-26 07:56:44.975  WARN [main] (com.actiontech.dble.config.converter.DBConverter.parseDbGroupXmlFileToJson(DBConverter.java:183)) - parseXmlToBean Exception
javax.xml.bind.UnmarshalException: null
        at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallerImpl.handleStreamException(UnmarshallerImpl.java:470) ~[?:1.8.0_112]
        at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal0(UnmarshallerImpl.java:402) ~[?:1.8.0_112]
        at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal(UnmarshallerImpl.java:371) ~[?:1.8.0_112]
        at com.actiontech.dble.cluster.zkprocess.parse.XmlProcessBase.baseParseXmlToBean(XmlProcessBase.java:117) ~[dble-3.21.10.3.jar:?]
        at com.actiontech.dble.cluster.zkprocess.parse.XmlProcessBase.baseParseXmlToBean(XmlProcessBase.java:99) ~[dble-3.21.10.3.jar:?]
        at com.actiontech.dble.config.converter.DBConverter.parseDbGroupXmlFileToJson(DBConverter.java:181) [dble-3.21.10.3.jar:?]
        at com.actiontech.dble.config.converter.DBConverter.parseDbGroupXmlFileToJson(DBConverter.java:174) [dble-3.21.10.3.jar:?]
        at com.actiontech.dble.config.converter.DBConverter.dbXmlToJson(DBConverter.java:55) [dble-3.21.10.3.jar:?]
        at com.actiontech.dble.config.ConfigInitializer.<init>(ConfigInitializer.java:70) [dble-3.21.10.3.jar:?]
        at com.actiontech.dble.config.ServerConfig.<init>(ServerConfig.java:79) [dble-3.21.10.3.jar:?]
        at com.actiontech.dble.DbleServer.initServerConfig(DbleServer.java:316) [dble-3.21.10.3.jar:?]
        at com.actiontech.dble.DbleServer.startup(DbleServer.java:127) [dble-3.21.10.3.jar:?]
        at com.actiontech.dble.DbleStartup.initClusterAndServerStart(DbleStartup.java:62) [dble-3.21.10.3.jar:?]
        at com.actiontech.dble.DbleStartup.main(DbleStartup.java:41) [dble-3.21.10.3.jar:?]
Caused by: javax.xml.stream.XMLStreamException: ParseError at [row,col]:[26,13]
Message: 注释中不允许出现字符串 "--"。
        at com.sun.org.apache.xerces.internal.impl.XMLStreamReaderImpl.next(XMLStreamReaderImpl.java:596) ~[?:1.8.0_112]
        at com.sun.xml.internal.bind.v2.runtime.unmarshaller.StAXStreamConnector.bridge(StAXStreamConnector.java:181) ~[?:1.8.0_112]
        at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal0(UnmarshallerImpl.java:400) ~[?:1.8.0_112]
        ... 12 more

```

**Comment by LUAgam** [comment]
> 



> 望提示错误信息中增加文件名，缩小排查范围。
> 
> ```
> 2022-06-26 07:56:44.619  INFO [main] (com.actiontech.dble.DbleServer.startup(DbleServer.java:126)) - ===========================================DBLE SERVER STARTING===================================
> 2022-06-26 07:56:44.975  WARN [main] (com.actiontech.dble.config.converter.DBConverter.parseDbGroupXmlFileToJson(DBConverter.java:183)) - parseXmlToBean Exception
> javax.xml.bind.UnmarshalException: null
>         at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallerImpl.handleStreamException(UnmarshallerImpl.java:470) ~[?:1.8.0_112]
>         at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal0(UnmarshallerImpl.java:402) ~[?:1.8.0_112]
>         at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal(UnmarshallerImpl.java:371) ~[?:1.8.0_112]
>         at com.actiontech.dble.cluster.zkprocess.parse.XmlProcessBase.baseParseXmlToBean(XmlProcessBase.java:117) ~[dble-3.21.10.3.jar:?]
>         at com.actiontech.dble.cluster.zkprocess.parse.XmlProcessBase.baseParseXmlToBean(XmlProcessBase.java:99) ~[dble-3.21.10.3.jar:?]
>         at com.actiontech.dble.config.converter.DBConverter.parseDbGroupXmlFileToJson(DBConverter.java:181) [dble-3.21.10.3.jar:?]
>         at com.actiontech.dble.config.converter.DBConverter.parseDbGroupXmlFileToJson(DBConverter.java:174) [dble-3.21.10.3.jar:?]
>         at com.actiontech.dble.config.converter.DBConverter.dbXmlToJson(DBConverter.java:55) [dble-3.21.10.3.jar:?]
>         at com.actiontech.dble.config.ConfigInitializer.<init>(ConfigInitializer.java:70) [dble-3.21.10.3.jar:?]
>         at com.actiontech.dble.config.ServerConfig.<init>(ServerConfig.java:79) [dble-3.21.10.3.jar:?]
>         at com.actiontech.dble.DbleServer.initServerConfig(DbleServer.java:316) [dble-3.21.10.3.jar:?]
>         at com.actiontech.dble.DbleServer.startup(DbleServer.java:127) [dble-3.21.10.3.jar:?]
>         at com.actiontech.dble.DbleStartup.initClusterAndServerStart(DbleStartup.java:62) [dble-3.21.10.3.jar:?]
>         at com.actiontech.dble.DbleStartup.main(DbleStartup.java:41) [dble-3.21.10.3.jar:?]
> Caused by: javax.xml.stream.XMLStreamException: ParseError at [row,col]:[26,13]
> Message: 注释中不允许出现字符串 "--"。
>         at com.sun.org.apache.xerces.internal.impl.XMLStreamReaderImpl.next(XMLStreamReaderImpl.java:596) ~[?:1.8.0_112]
>         at com.sun.xml.internal.bind.v2.runtime.unmarshaller.StAXStreamConnector.bridge(StAXStreamConnector.java:181) ~[?:1.8.0_112]
>         at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal0(UnmarshallerImpl.java:400) ~[?:1.8.0_112]
>         ... 12 more
> ```
`2022-06-26 07:56:44.975 WARN [main] (com.actiontech.dble.config.converter.DBConverter.parseDbGroupXmlFileToJson(DBConverter.java:183)) - parseXmlToBean Exception`
At present, it can be identified by the keyword **DbGroup** in the above log, and others are 
**parseShardingXmlFileToJson->shardingXml
parseUserXmlFileToJson->userXml**

The file name will also be added to the log later.
