### ISSUE TITLE
Error of "lost connection" cause of "analyze table table_name" 

### ISSUE THREAD

**Issue by zhunina** [actiontech/dble#337]
```
mysql> analyze table t1;
ERROR 2006 (HY000): MySQL server has gone away
No connection. Trying to reconnect...
Connection id:    10
Current database: testdb
```
```
2017-11-27 15:47:28.217  WARN [$_NIOREACTOR-0-RW] (com.actiontech.dble.net.NIOReactor$RW.run(NIOReactor.java:78)) - caught err:
java.lang.StringIndexOutOfBoundsException: String index out of range: 23
        at java.lang.String.charAt(String.java:658) ~[?:1.8.0_151]
        at com.actiontech.dble.server.parser.ServerParse.tCheck(ServerParse.java:251) ~[dble-2.17.11.0-dev.jar:?]
        at com.actiontech.dble.server.parser.ServerParse.parse(ServerParse.java:126) ~[dble-2.17.11.0-dev.jar:?]
        at com.actiontech.dble.server.ServerQueryHandler.query(ServerQueryHandler.java:47) ~[dble-2.17.11.0-dev.jar:?]
        at com.actiontech.dble.net.FrontendConnection.query(FrontendConnection.java:314) ~[dble-2.17.11.0-dev.jar:?]
        at com.actiontech.dble.net.FrontendConnection.query(FrontendConnection.java:332) ~[dble-2.17.11.0-dev.jar:?]
        at com.actiontech.dble.net.handler.FrontendCommandHandler.handleData(FrontendCommandHandler.java:51) ~[dble-2.17.11.0-dev.jar:?]
        at com.actiontech.dble.net.handler.FrontendCommandHandler.handle(FrontendCommandHandler.java:40) ~[dble-2.17.11.0-dev.jar:?]
        at com.actiontech.dble.net.FrontendConnection.rawHandle(FrontendConnection.java:469) ~[dble-2.17.11.0-dev.jar:?]
        at com.actiontech.dble.net.FrontendConnection.handle(FrontendConnection.java:451) ~[dble-2.17.11.0-dev.jar:?]
        at com.actiontech.dble.net.AbstractConnection.onReadData(AbstractConnection.java:297) ~[dble-2.17.11.0-dev.jar:?]
        at com.actiontech.dble.net.NIOSocketWR.asyncRead(NIOSocketWR.java:175) ~[dble-2.17.11.0-dev.jar:?]
        at com.actiontech.dble.net.AbstractConnection.asyncRead(AbstractConnection.java:256) ~[dble-2.17.11.0-dev.jar:?]
        at com.actiontech.dble.net.NIOReactor$RW.run(NIOReactor.java:73) [dble-2.17.11.0-dev.jar:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
```

Expected Results: Unsupport statement

**Comment by zhunina** [comment]
"checksum table table_name " has the same problem

**Comment by zhunina** [comment]
"flush table table_name" also has the same problem

**Comment by zhunina** [comment]
```
mysql> LOAD INDEX INTO CACHE t1;
ERROR 1064 (HY000): TODO
```
Suggestion:change the messages to "Unsupport statement"

**Comment by zhunina** [comment]
"optimize table table_name" has the same problem as title

**Comment by zhunina** [comment]
"rename table table_name1 to table_name2" has the same problem as title

**Comment by zhunina** [comment]
"repair table table_name" has the same problem as title

**Comment by yanhuqing666** [comment]
Except “LOAD INDEX INTO CACHE”，the other statementa are all parse problem.

**Comment by ditdb** [comment]
fix， please do regression testing.

**Comment by zhunina** [comment]
fixed
