### ISSUE TITLE
dead lock by 'reload @@_config' twice

### ISSUE THREAD

**Issue by zhunina** [actiontech/dble#339]
```
mysql> reload @@config_all;
ERROR 2006 (HY000): MySQL server has gone away
No connection. Trying to reconnect...
Connection id:    2
Current database: *** NONE ***

Query OK, 1 row affected (1 min 0.31 sec)
Reload config success

mysql> reload @@config_all;
```
Jstack log: 
```
2017-11-28 16:39:39
Full thread dump Java HotSpot(TM) 64-Bit Server VM (25.151-b12 mixed mode):

"Attach Listener" #44 daemon prio=9 os_prio=0 tid=0x00007f2e80001000 nid=0x6095 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Timer0" #42 daemon prio=5 os_prio=0 tid=0x00007f2e44002000 nid=0x6913 waiting on condition [0x00007f2e2d2e2000]
   java.lang.Thread.State: WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x00000006c0013ff0> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
	at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
	at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1074)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

"TimerScheduler-0" #41 prio=5 os_prio=0 tid=0x00007f2e301d6800 nid=0x6912 runnable [0x00007f2e2d3e3000]
   java.lang.Thread.State: TIMED_WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x00000006c001c148> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2078)
	at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1093)
	at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:809)
	at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1074)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

"$_Dble_Server" #30 prio=5 os_prio=0 tid=0x00007f2e301d4000 nid=0x6911 runnable [0x00007f2e2d4e4000]
   java.lang.Thread.State: RUNNABLE
	at sun.nio.ch.EPollArrayWrapper.epollWait(Native Method)
	at sun.nio.ch.EPollArrayWrapper.poll(EPollArrayWrapper.java:269)
	at sun.nio.ch.EPollSelectorImpl.doSelect(EPollSelectorImpl.java:93)
	at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:86)
	- locked <0x00000006c0023948> (a sun.nio.ch.Util$3)
	- locked <0x00000006c0023938> (a java.util.Collections$UnmodifiableSet)
	- locked <0x00000006c0023958> (a sun.nio.ch.EPollSelectorImpl)
	at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:97)
	at com.actiontech.dble.net.NIOAcceptor.run(NIOAcceptor.java:61)

"$_Dble_Manager" #29 prio=5 os_prio=0 tid=0x00007f2e301d3000 nid=0x6910 runnable [0x00007f2e2d5e5000]
   java.lang.Thread.State: RUNNABLE
	at sun.nio.ch.EPollArrayWrapper.epollWait(Native Method)
	at sun.nio.ch.EPollArrayWrapper.poll(EPollArrayWrapper.java:269)
	at sun.nio.ch.EPollSelectorImpl.doSelect(EPollSelectorImpl.java:93)
	at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:86)
	- locked <0x00000006c00142c0> (a sun.nio.ch.Util$3)
	- locked <0x00000006c00142b0> (a java.util.Collections$UnmodifiableSet)
	- locked <0x00000006c00142d0> (a sun.nio.ch.EPollSelectorImpl)
	at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:97)
	at com.actiontech.dble.net.NIOAcceptor.run(NIOAcceptor.java:61)

"net.sf.ehcache.CacheManager@242aeb6e" #39 daemon prio=5 os_prio=0 tid=0x00007f2e301b1800 nid=0x690e in Object.wait() [0x00007f2e2d6e6000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	- waiting on <0x00000006c0014898> (a java.util.TaskQueue)
	at java.lang.Object.wait(Object.java:502)
	at java.util.TimerThread.mainLoop(Timer.java:526)
	- locked <0x00000006c0014898> (a java.util.TaskQueue)
	at java.util.TimerThread.run(Timer.java:505)

"BusinessExecutor7" #38 daemon prio=5 os_prio=0 tid=0x00007f2e3012c000 nid=0x6904 waiting on condition [0x00007f2e2d9e7000]
   java.lang.Thread.State: WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x00000006c0023be0> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
	at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
	at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1074)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

"BusinessExecutor6" #37 daemon prio=5 os_prio=0 tid=0x00007f2e3012a000 nid=0x6903 waiting on condition [0x00007f2e2dae8000]
   java.lang.Thread.State: WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x00000006c0023be0> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
	at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
	at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1074)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

"BusinessExecutor5" #36 daemon prio=5 os_prio=0 tid=0x00007f2e24003000 nid=0x6902 waiting on condition [0x00007f2e2dbe9000]
   java.lang.Thread.State: WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x00000006c0023be0> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
	at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
	at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1074)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

"BusinessExecutor4" #35 daemon prio=5 os_prio=0 tid=0x00007f2e30121000 nid=0x6901 waiting on condition [0x00007f2e2dcea000]
   java.lang.Thread.State: WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x00000006c0023be0> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
	at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
	at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1074)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

"BusinessExecutor3" #34 daemon prio=5 os_prio=0 tid=0x00007f2e24001000 nid=0x6900 waiting on condition [0x00007f2e2ddeb000]
   java.lang.Thread.State: WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x00000006c0023be0> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
	at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
	at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1074)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

"BusinessExecutor2" #33 daemon prio=5 os_prio=0 tid=0x00007f2e30127000 nid=0x68ff waiting on condition [0x00007f2e2deec000]
   java.lang.Thread.State: WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x00000006c0023be0> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
	at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
	at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1074)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

"BusinessExecutor1" #32 daemon prio=5 os_prio=0 tid=0x00007f2e20003800 nid=0x68fb waiting on condition [0x00007f2e2e1ed000]
   java.lang.Thread.State: WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x00000006c0023be0> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
	at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
	at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1074)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

"BusinessExecutor0" #31 daemon prio=5 os_prio=0 tid=0x00007f2e3011f000 nid=0x68f0 waiting on condition [0x00007f2e2e2ee000]
   java.lang.Thread.State: WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x00000006c0023be0> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
	at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
	at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1074)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

"$_NIOConnector" #28 prio=5 os_prio=0 tid=0x00007f2e300ca800 nid=0x68ed runnable [0x00007f2e2e3ef000]
   java.lang.Thread.State: RUNNABLE
	at sun.nio.ch.EPollArrayWrapper.epollWait(Native Method)
	at sun.nio.ch.EPollArrayWrapper.poll(EPollArrayWrapper.java:269)
	at sun.nio.ch.EPollSelectorImpl.doSelect(EPollSelectorImpl.java:93)
	at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:86)
	- locked <0x00000006c0028278> (a sun.nio.ch.Util$3)
	- locked <0x00000006c0028268> (a java.util.Collections$UnmodifiableSet)
	- locked <0x00000006c0028288> (a sun.nio.ch.EPollSelectorImpl)
	at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:97)
	at com.actiontech.dble.net.NIOConnector.run(NIOConnector.java:53)

"$_NIOREACTOR-3-RW" #27 prio=5 os_prio=0 tid=0x00007f2e300c8800 nid=0x68ec runnable [0x00007f2e2e4f0000]
   java.lang.Thread.State: RUNNABLE
	at sun.nio.ch.EPollArrayWrapper.epollWait(Native Method)
	at sun.nio.ch.EPollArrayWrapper.poll(EPollArrayWrapper.java:269)
	at sun.nio.ch.EPollSelectorImpl.doSelect(EPollSelectorImpl.java:93)
	at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:86)
	- locked <0x00000006c00877e0> (a sun.nio.ch.Util$3)
	- locked <0x00000006c00877d0> (a java.util.Collections$UnmodifiableSet)
	- locked <0x00000006c0029908> (a sun.nio.ch.EPollSelectorImpl)
	at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:97)
	at com.actiontech.dble.net.NIOReactor$RW.run(NIOReactor.java:62)
	at java.lang.Thread.run(Thread.java:748)

"$_NIOREACTOR-2-RW" #26 prio=5 os_prio=0 tid=0x00007f2e300ba000 nid=0x68eb runnable [0x00007f2e2e5f1000]
   java.lang.Thread.State: RUNNABLE
	at sun.nio.ch.EPollArrayWrapper.epollWait(Native Method)
	at sun.nio.ch.EPollArrayWrapper.poll(EPollArrayWrapper.java:269)
	at sun.nio.ch.EPollSelectorImpl.doSelect(EPollSelectorImpl.java:93)
	at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:86)
	- locked <0x00000006c00793d8> (a sun.nio.ch.Util$3)
	- locked <0x00000006c00793c8> (a java.util.Collections$UnmodifiableSet)
	- locked <0x00000006c005c730> (a sun.nio.ch.EPollSelectorImpl)
	at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:97)
	at com.actiontech.dble.net.NIOReactor$RW.run(NIOReactor.java:62)
	at java.lang.Thread.run(Thread.java:748)

"$_NIOREACTOR-1-RW" #25 prio=5 os_prio=0 tid=0x00007f2e300ab800 nid=0x68ea waiting on condition [0x00007f2e341df000]
   java.lang.Thread.State: WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x00000007734be450> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
	at com.actiontech.dble.server.variables.VarsExtractorHandler.waitDone(VarsExtractorHandler.java:74)
	at com.actiontech.dble.server.variables.VarsExtractorHandler.execute(VarsExtractorHandler.java:45)
	at com.actiontech.dble.manager.response.ReloadConfig.reloadAll(ReloadConfig.java:182)
	at com.actiontech.dble.manager.response.ReloadConfig.execute(ReloadConfig.java:128)
	at com.actiontech.dble.manager.handler.ReloadHandler.handle(ReloadHandler.java:28)
	at com.actiontech.dble.manager.ManagerQueryHandler.query(ManagerQueryHandler.java:72)
	at com.actiontech.dble.net.FrontendConnection.query(FrontendConnection.java:314)
	at com.actiontech.dble.net.FrontendConnection.query(FrontendConnection.java:332)
	at com.actiontech.dble.net.handler.ManagerCommandHandler.handleData(ManagerCommandHandler.java:27)
	at com.actiontech.dble.net.handler.FrontendCommandHandler.handle(FrontendCommandHandler.java:40)
	at com.actiontech.dble.manager.ManagerConnection.handle(ManagerConnection.java:36)
	at com.actiontech.dble.net.AbstractConnection.onReadData(AbstractConnection.java:297)
	at com.actiontech.dble.net.NIOSocketWR.asyncRead(NIOSocketWR.java:175)
	at com.actiontech.dble.net.AbstractConnection.asyncRead(AbstractConnection.java:256)
	at com.actiontech.dble.net.NIOReactor$RW.run(NIOReactor.java:73)
	at java.lang.Thread.run(Thread.java:748)

"$_NIOREACTOR-0-RW" #24 prio=5 os_prio=0 tid=0x00007f2e3009d000 nid=0x68e9 runnable [0x00007f2e7415d000]
   java.lang.Thread.State: RUNNABLE
	at sun.nio.ch.EPollArrayWrapper.epollWait(Native Method)
	at sun.nio.ch.EPollArrayWrapper.poll(EPollArrayWrapper.java:269)
	at sun.nio.ch.EPollSelectorImpl.doSelect(EPollSelectorImpl.java:93)
	at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:86)
	- locked <0x00000006c005e520> (a sun.nio.ch.Util$3)
	- locked <0x00000006c005e510> (a java.util.Collections$UnmodifiableSet)
	- locked <0x00000006c005d900> (a sun.nio.ch.EPollSelectorImpl)
	at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:97)
	at com.actiontech.dble.net.NIOReactor$RW.run(NIOReactor.java:62)
	at java.lang.Thread.run(Thread.java:748)

"DestroyJavaVM" #21 prio=5 os_prio=0 tid=0x00007f2eb800a000 nid=0x687a waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Wrapper-Connection" #20 daemon prio=10 os_prio=0 tid=0x00007f2eb8629800 nid=0x68db runnable [0x00007f2ea2dca000]
   java.lang.Thread.State: RUNNABLE
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
	at java.net.SocketInputStream.read(SocketInputStream.java:171)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at java.net.SocketInputStream.read(SocketInputStream.java:224)
	at java.io.DataInputStream.readByte(DataInputStream.java:265)
	at org.tanukisoftware.wrapper.WrapperManager.handleSocket(WrapperManager.java:3737)
	at org.tanukisoftware.wrapper.WrapperManager.run(WrapperManager.java:4084)
	at java.lang.Thread.run(Thread.java:748)

"Log4j2-TF-4-AsyncLoggerConfig-3" #19 daemon prio=5 os_prio=0 tid=0x00007f2eb860e800 nid=0x68da runnable [0x00007f2ea2ecb000]
   java.lang.Thread.State: TIMED_WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x00000006c0175f30> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2078)
	at com.lmax.disruptor.TimeoutBlockingWaitStrategy.waitFor(TimeoutBlockingWaitStrategy.java:38)
	at com.lmax.disruptor.ProcessingSequenceBarrier.waitFor(ProcessingSequenceBarrier.java:56)
	at com.lmax.disruptor.BatchEventProcessor.run(BatchEventProcessor.java:124)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

"Log4j2-TF-3-Scheduled-2" #18 daemon prio=5 os_prio=0 tid=0x00007f2eb860a800 nid=0x68d9 waiting on condition [0x00007f2ea2fcc000]
   java.lang.Thread.State: TIMED_WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x00000006c011f050> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2078)
	at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1093)
	at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:809)
	at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1074)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

"Wrapper-Control-Event-Monitor" #14 daemon prio=5 os_prio=0 tid=0x00007f2eb8458800 nid=0x68c4 waiting on condition [0x00007f2ea36cf000]
   java.lang.Thread.State: TIMED_WAITING (sleeping)
	at java.lang.Thread.sleep(Native Method)
	at org.tanukisoftware.wrapper.WrapperManager$3.run(WrapperManager.java:731)

"RMI TCP Accept-0" #12 daemon prio=5 os_prio=0 tid=0x00007f2eb8423000 nid=0x68bb runnable [0x00007f2ea39d4000]
   java.lang.Thread.State: RUNNABLE
	at java.net.PlainSocketImpl.socketAccept(Native Method)
	at java.net.AbstractPlainSocketImpl.accept(AbstractPlainSocketImpl.java:409)
	at java.net.ServerSocket.implAccept(ServerSocket.java:545)
	at java.net.ServerSocket.accept(ServerSocket.java:513)
	at sun.management.jmxremote.LocalRMIServerSocketFactory$1.accept(LocalRMIServerSocketFactory.java:52)
	at sun.rmi.transport.tcp.TCPTransport$AcceptLoop.executeAcceptLoop(TCPTransport.java:400)
	at sun.rmi.transport.tcp.TCPTransport$AcceptLoop.run(TCPTransport.java:372)
	at java.lang.Thread.run(Thread.java:748)

"RMI TCP Accept-1984" #11 daemon prio=5 os_prio=0 tid=0x00007f2eb8412800 nid=0x68ba runnable [0x00007f2ea3ad5000]
   java.lang.Thread.State: RUNNABLE
	at java.net.PlainSocketImpl.socketAccept(Native Method)
	at java.net.AbstractPlainSocketImpl.accept(AbstractPlainSocketImpl.java:409)
	at java.net.ServerSocket.implAccept(ServerSocket.java:545)
	at java.net.ServerSocket.accept(ServerSocket.java:513)
	at sun.rmi.transport.tcp.TCPTransport$AcceptLoop.executeAcceptLoop(TCPTransport.java:400)
	at sun.rmi.transport.tcp.TCPTransport$AcceptLoop.run(TCPTransport.java:372)
	at java.lang.Thread.run(Thread.java:748)

"RMI TCP Accept-0" #10 daemon prio=5 os_prio=0 tid=0x00007f2eb83fd800 nid=0x68b9 runnable [0x00007f2ea3bd6000]
   java.lang.Thread.State: RUNNABLE
	at java.net.PlainSocketImpl.socketAccept(Native Method)
	at java.net.AbstractPlainSocketImpl.accept(AbstractPlainSocketImpl.java:409)
	at java.net.ServerSocket.implAccept(ServerSocket.java:545)
	at java.net.ServerSocket.accept(ServerSocket.java:513)
	at sun.rmi.transport.tcp.TCPTransport$AcceptLoop.executeAcceptLoop(TCPTransport.java:400)
	at sun.rmi.transport.tcp.TCPTransport$AcceptLoop.run(TCPTransport.java:372)
	at java.lang.Thread.run(Thread.java:748)

"Service Thread" #8 daemon prio=9 os_prio=0 tid=0x00007f2eb80ea000 nid=0x68a1 runnable [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C1 CompilerThread2" #7 daemon prio=9 os_prio=0 tid=0x00007f2eb80bd000 nid=0x689f waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C2 CompilerThread1" #6 daemon prio=9 os_prio=0 tid=0x00007f2eb80bb800 nid=0x689e waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C2 CompilerThread0" #5 daemon prio=9 os_prio=0 tid=0x00007f2eb80b8800 nid=0x689d waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Signal Dispatcher" #4 daemon prio=9 os_prio=0 tid=0x00007f2eb80b4000 nid=0x689c runnable [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Finalizer" #3 daemon prio=8 os_prio=0 tid=0x00007f2eb8084000 nid=0x688c in Object.wait() [0x00007f2ea89f8000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	- waiting on <0x00000006c01e7980> (a java.lang.ref.ReferenceQueue$Lock)
	at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:143)
	- locked <0x00000006c01e7980> (a java.lang.ref.ReferenceQueue$Lock)
	at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:164)
	at java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:209)

"Reference Handler" #2 daemon prio=10 os_prio=0 tid=0x00007f2eb807f800 nid=0x688a in Object.wait() [0x00007f2ea8af9000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	- waiting on <0x00000006c01fc490> (a java.lang.ref.Reference$Lock)
	at java.lang.Object.wait(Object.java:502)
	at java.lang.ref.Reference.tryHandlePending(Reference.java:191)
	- locked <0x00000006c01fc490> (a java.lang.ref.Reference$Lock)
	at java.lang.ref.Reference$ReferenceHandler.run(Reference.java:153)

"VM Thread" os_prio=0 tid=0x00007f2eb8078000 nid=0x6886 runnable 

"GC task thread#0 (ParallelGC)" os_prio=0 tid=0x00007f2eb801f000 nid=0x687f runnable 

"GC task thread#1 (ParallelGC)" os_prio=0 tid=0x00007f2eb8021000 nid=0x6880 runnable 

"GC task thread#2 (ParallelGC)" os_prio=0 tid=0x00007f2eb8022800 nid=0x6881 runnable 

"GC task thread#3 (ParallelGC)" os_prio=0 tid=0x00007f2eb8024800 nid=0x6882 runnable 

"VM Periodic Task Thread" os_prio=0 tid=0x00007f2eb8425000 nid=0x68bc waiting on condition 

JNI global references: 318


```

**Comment by zhunina** [comment]
fixed
