### ISSUE TITLE
Error when `join syntax` contains global table and two non-global tables

### ISSUE THREAD

**Issue by FlyingMao** [actiontech/dble#350]
steps:
```
mysql> CREATE TABLE a_test(`id` int(10) unsigned NOT NULL,`t_id` int(10) unsigned NOT NULL DEFAULT '0',`name` char(120) NOT NULL DEFAULT '',`pad` int(11) NOT NULL,PRIMARY KEY (`id`),KEY `k_1` (`t_id`))DEFAULT CHARSET=UTF8;/*sharding table*/
Query OK, 0 rows affected (0.44 sec)

mysql> CREATE TABLE test_global(`id` int(10) unsigned NOT NULL,`o_id` int(10) unsigned NOT NULL DEFAULT '0',`name` char(120) NOT NULL DEFAULT '',`pad` int(11) NOT NULL,PRIMARY KEY (`id`),KEY `k_1` (`o_id`))DEFAULT CHARSET=UTF8;/*global table*/
Query OK, 0 rows affected (1.00 sec)

mysql> CREATE TABLE a_manager(`id` int(10) unsigned NOT NULL,`m_id` int(10) unsigned NOT NULL DEFAULT '0',`name` char(120) NOT NULL DEFAULT '',`pad` int(11) NOT NULL,PRIMARY KEY (`id`),KEY `k_1` (`m_id`))DEFAULT CHARSET=UTF8;/*sharding table*/
Query OK, 0 rows affected (2.89 sec)

mysql> insert into a_test values(1,1,'test中id为1',1),(2,2,'test_2',2),(3,3,'test中id为3',4),(4,4,'$test$4',3),(5,5,'test...5',1),(6,6,'test6',6);
Query OK, 6 rows affected (0.43 sec)

mysql> insert into test_global values(1,1,'order中id为1',1),(2,2,'test_2',2),(3,3,'order中id为3',3),(4,4,'$order$4',4),(5,5,'order...5',1);
Query OK, 5 rows affected (0.65 sec)
Records: 5  Duplicates: 0  Warnings: 0

mysql> insert into a_manager values(1,1,'manager中id为1',1),(2,2,'test_2',2),(3,3,'manager中id为3',3),(4,4,'$manager$4',4),(5,5,'manager...5',6);
Query OK, 5 rows affected (0.28 sec)

mysql> select a.id,b.id,c.pad from test_global a,a_test b,a_manager c where a.id=b.id and a.id=c.pad;
ERROR 1105 (HY000): java.lang.NullPointerException

```
log：
```
2017-11-30 13:38:27.332  WARN [BusinessExecutor6] (com.actiontech.dble.net.handler.FrontendCommandHandler$1.run(FrontendCommandHandler.java:123)) - Maybe occur a bug, please check it.
java.lang.NullPointerException: null
	at java.util.AbstractCollection.retainAll(AbstractCollection.java:397) ~[?:1.7.0_05]
	at com.actiontech.dble.plan.optimizer.GlobalTableProcessor.calcUnGlobalCount(GlobalTableProcessor.java:103) ~[dble-2.17.09.0.jar:?]
	at com.actiontech.dble.plan.optimizer.GlobalTableProcessor.initGlobalStatus(GlobalTableProcessor.java:47) ~[dble-2.17.09.0.jar:?]
	at com.actiontech.dble.plan.optimizer.GlobalTableProcessor.optimize(GlobalTableProcessor.java:21) ~[dble-2.17.09.0.jar:?]
	at com.actiontech.dble.plan.optimizer.MyOptimizer.optimize(MyOptimizer.java:44) ~[dble-2.17.09.0.jar:?]
	at com.actiontech.dble.server.NonBlockingSession.executeMultiSelect(NonBlockingSession.java:238) ~[dble-2.17.09.0.jar:?]
	at com.actiontech.dble.server.NonBlockingSession.execute(NonBlockingSession.java:153) ~[dble-2.17.09.0.jar:?]
	at com.actiontech.dble.server.ServerConnection.routeEndExecuteSQL(ServerConnection.java:305) ~[dble-2.17.09.0.jar:?]
	at com.actiontech.dble.server.ServerConnection.execute(ServerConnection.java:238) ~[dble-2.17.09.0.jar:?]
	at com.actiontech.dble.server.handler.SelectHandler.handle(SelectHandler.java:96) ~[dble-2.17.09.0.jar:?]
	at com.actiontech.dble.server.ServerQueryHandler.query(ServerQueryHandler.java:68) ~[dble-2.17.09.0.jar:?]
	at com.actiontech.dble.net.FrontendConnection.query(FrontendConnection.java:315) ~[dble-2.17.09.0.jar:?]
	at com.actiontech.dble.net.FrontendConnection.query(FrontendConnection.java:333) ~[dble-2.17.09.0.jar:?]
	at com.actiontech.dble.net.handler.FrontendCommandHandler.handleData(FrontendCommandHandler.java:66) ~[dble-2.17.09.0.jar:?]
	at com.actiontech.dble.net.handler.FrontendCommandHandler$1.run(FrontendCommandHandler.java:118) [dble-2.17.09.0.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110) [?:1.7.0_05]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603) [?:1.7.0_05]
	at java.lang.Thread.run(Thread.java:722) [?:1.7.0_05]

```

**Comment by yanhuqing666** [comment]
fixed ，see  src/main/java/com/actiontech/dble/plan/optimizer/GlobalTableProcessor.java in 
ab510df55d838ca19e341f9f2111f6e7d7c0b9cd  and a78b8a100a7cd3bb314e3f49d4cc839fb29de23d
