### ISSUE TITLE
Error cause of high concurrency insertion when sequence type is one

### ISSUE THREAD

**Issue by zhunina** [actiontech/dble#372]
```
2017-12-06 10:04:49.253  WARN [BusinessExecutor2] (com.actiontech.dble.server.ServerConnection.executeException(ServerConnection.java:367)) - ServerConnection [id=68, schema=testdb, host=10.186.23.12, user=test,txIsolation=2, autocommit=true, schema=testdb]insert into t5 values('aa') err:java.lang.RuntimeException: can't fetch sequence in db,sequence :`testdb`.`t5` detail:null
java.lang.RuntimeException: can't fetch sequence in db,sequence :`testdb`.`t5` detail:null
        at com.actiontech.dble.route.sequence.handler.IncrSequenceMySQLHandler.getSeqValueFromDB(IncrSequenceMySQLHandler.java:104) ~[dble-2.17.11.0-dev.jar:?]
        at com.actiontech.dble.route.sequence.handler.IncrSequenceMySQLHandler.getNextValidSeqVal(IncrSequenceMySQLHandler.java:87) ~[dble-2.17.11.0-dev.jar:?]
        at com.actiontech.dble.route.sequence.handler.IncrSequenceMySQLHandler.nextId(IncrSequenceMySQLHandler.java:76) ~[dble-2.17.11.0-dev.jar:?]
        at com.actiontech.dble.route.parser.druid.impl.DruidInsertParser.appendValues(DruidInsertParser.java:459) ~[dble-2.17.11.0-dev.jar:?]
        at com.actiontech.dble.route.parser.druid.impl.DruidInsertParser.convertInsertSQL(DruidInsertParser.java:375) ~[dble-2.17.11.0-dev.jar:?]
        at com.actiontech.dble.route.parser.druid.impl.DruidInsertParser.visitorParse(DruidInsertParser.java:85) ~[dble-2.17.11.0-dev.jar:?]
        at com.actiontech.dble.route.parser.druid.impl.DefaultDruidParser.parser(DefaultDruidParser.java:47) ~[dble-2.17.11.0-dev.jar:?]
        at com.actiontech.dble.route.util.RouterUtil.routeFromParser(RouterUtil.java:119) ~[dble-2.17.11.0-dev.jar:?]
        at com.actiontech.dble.route.impl.DefaultRouteStrategy.routeNormalSqlWithAST(DefaultRouteStrategy.java:59) ~[dble-2.17.11.0-dev.jar:?]
        at com.actiontech.dble.route.impl.AbstractRouteStrategy.route(AbstractRouteStrategy.java:60) ~[dble-2.17.11.0-dev.jar:?]
        at com.actiontech.dble.route.RouteService.route(RouteService.java:108) ~[dble-2.17.11.0-dev.jar:?]
        at com.actiontech.dble.server.ServerConnection.routeEndExecuteSQL(ServerConnection.java:306) [dble-2.17.11.0-dev.jar:?]
        at com.actiontech.dble.server.ServerConnection.execute(ServerConnection.java:250) [dble-2.17.11.0-dev.jar:?]
        at com.actiontech.dble.server.ServerQueryHandler.query(ServerQueryHandler.java:137) [dble-2.17.11.0-dev.jar:?]
        at com.actiontech.dble.net.FrontendConnection.query(FrontendConnection.java:314) [dble-2.17.11.0-dev.jar:?]
        at com.actiontech.dble.net.FrontendConnection.query(FrontendConnection.java:332) [dble-2.17.11.0-dev.jar:?]
        at com.actiontech.dble.net.handler.FrontendCommandHandler.handleData(FrontendCommandHandler.java:64) [dble-2.17.11.0-dev.jar:?]
        at com.actiontech.dble.net.handler.FrontendCommandHandler$1.run(FrontendCommandHandler.java:116) [dble-2.17.11.0-dev.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_151]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_151]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
2017-12-06 10:04:49.254  WARN [BusinessExecutor7] (com.actiontech.dble.server.ServerConnection.executeException(ServerConnection.java:367)) - ServerConnection [id=75, schema=testdb, host=10.186.23.12, user=test,txIsolation=2, autocommit=true, schema=testdb]insert into t5 values('aa') err:java.lang.RuntimeException: can't fetch sequence in db,sequence :`testdb`.`t5` detail:null
java.lang.RuntimeException: can't fetch sequence in db,sequence :`testdb`.`t5` detail:null
        at com.actiontech.dble.route.sequence.handler.IncrSequenceMySQLHandler.getSeqValueFromDB(IncrSequenceMySQLHandler.java:104) ~[dble-2.17.11.0-dev.jar:?]
        at com.actiontech.dble.route.sequence.handler.IncrSequenceMySQLHandler.getNextValidSeqVal(IncrSequenceMySQLHandler.java:87) ~[dble-2.17.11.0-dev.jar:?]
        at com.actiontech.dble.route.sequence.handler.IncrSequenceMySQLHandler.nextId(IncrSequenceMySQLHandler.java:76) ~[dble-2.17.11.0-dev.jar:?]
        at com.actiontech.dble.route.parser.druid.impl.DruidInsertParser.appendValues(DruidInsertParser.java:459) ~[dble-2.17.11.0-dev.jar:?]
        at com.actiontech.dble.route.parser.druid.impl.DruidInsertParser.convertInsertSQL(DruidInsertParser.java:375) ~[dble-2.17.11.0-dev.jar:?]
        at com.actiontech.dble.route.parser.druid.impl.DruidInsertParser.visitorParse(DruidInsertParser.java:85) ~[dble-2.17.11.0-dev.jar:?]
        at com.actiontech.dble.route.parser.druid.impl.DefaultDruidParser.parser(DefaultDruidParser.java:47) ~[dble-2.17.11.0-dev.jar:?]
        at com.actiontech.dble.route.util.RouterUtil.routeFromParser(RouterUtil.java:119) ~[dble-2.17.11.0-dev.jar:?]
        at com.actiontech.dble.route.impl.DefaultRouteStrategy.routeNormalSqlWithAST(DefaultRouteStrategy.java:59) ~[dble-2.17.11.0-dev.jar:?]
        at com.actiontech.dble.route.impl.AbstractRouteStrategy.route(AbstractRouteStrategy.java:60) ~[dble-2.17.11.0-dev.jar:?]
        at com.actiontech.dble.route.RouteService.route(RouteService.java:108) ~[dble-2.17.11.0-dev.jar:?]
        at com.actiontech.dble.server.ServerConnection.routeEndExecuteSQL(ServerConnection.java:306) [dble-2.17.11.0-dev.jar:?]
        at com.actiontech.dble.server.ServerConnection.execute(ServerConnection.java:250) [dble-2.17.11.0-dev.jar:?]
        at com.actiontech.dble.server.ServerQueryHandler.query(ServerQueryHandler.java:137) [dble-2.17.11.0-dev.jar:?]
        at com.actiontech.dble.net.FrontendConnection.query(FrontendConnection.java:314) [dble-2.17.11.0-dev.jar:?]
        at com.actiontech.dble.net.FrontendConnection.query(FrontendConnection.java:332) [dble-2.17.11.0-dev.jar:?]
        at com.actiontech.dble.net.handler.FrontendCommandHandler.handleData(FrontendCommandHandler.java:64) [dble-2.17.11.0-dev.jar:?]
        at com.actiontech.dble.net.handler.FrontendCommandHandler$1.run(FrontendCommandHandler.java:116) [dble-2.17.11.0-dev.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_151]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_151]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
```

**Comment by zhunina** [comment]
fixed
