### ISSUE TITLE
Dble can not startup when the schema.xml is almost empty

### ISSUE THREAD

**Issue by sunsun314** [actiontech/dble#411]
when the schema.xml is 
<\?xml version="1.0"\?>
<\!DOCTYPE dble:schema SYSTEM "schema.dtd">
<dble:schema xmlns:dble="http://dble.cloud/">
</dble:schema>

the dble server can not start up with error :
2018-01-04 15:19:45,381 [ERROR][main] DBLE_CORE_ERROR::2018-01-04 15:19:45 startup error java.util.NoSuchElementException
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1431)
	at java.util.HashMap$EntryIterator.next(HashMap.java:1463)
	at java.util.HashMap$EntryIterator.next(HashMap.java:1461)
	at com.actiontech.dble.server.variables.VarsExtractorHandler.execute(VarsExtractorHandler.java:38)
	at com.actiontech.dble.DbleServer.pullVarAndMeta(DbleServer.java:262)
	at com.actiontech.dble.DbleServer.startup(DbleServer.java:376)
	at com.actiontech.dble.DbleStartup.main(DbleStartup.java:46)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
 (com.actiontech.dble.DbleStartup:DbleStartup.java:51)

**Comment by yanhuqing666** [comment]
```
<?xml version="1.0"?>
<!DOCTYPE dble:schema SYSTEM "schema.dtd">
<dble:schema xmlns:dble="http://io.dble/">
    <dataHost name="test-1" dbType="mysql" dbDriver="native" maxCon="100" minCon="10" balance="0" switchType="-1" slaveThreshold="-1" tempReadHostAvailable="0">
        <heartbeat>show slave status</heartbeat>
        <writeHost host="mysql-nx5wuy" url="172.20.134.2:3306" user="root" password="asdasd"></writeHost>
    </dataHost>
</dble:schema>
```
this config will error again

**Comment by yanhuqing666** [comment]
<?xml version="1.0"?>
<!DOCTYPE dble:schema SYSTEM "schema.dtd">
<dble:schema xmlns:dble="http://io.dble/">
    <dataHost name="test-1" dbType="mysql" dbDriver="native" maxCon="100" minCon="10" balance="0" switchType="-1" slaveThreshold="-1" tempReadHostAvailable="0">
        <heartbeat>show slave status</heartbeat> 
    </dataHost>
</dble:schema>

this case should be reloaded。
