### ISSUE TITLE
Error when use `between...and...` connection subquery

### ISSUE THREAD

**Issue by FlyingMao** [actiontech/dble#429]
steps：
```
mysql> select * from test_shard where 'A' between 1 and (select 'A' from test_shard limit 1);
ERROR 4004 (HY000): not support subquery of:FUNC_ITEM

```

**Comment by FlyingMao** [comment]
prepare table:
```
mysql> create table test_shard (id int(11) primary key,R_REGIONKEY float,R_NAME varchar(50),R_COMMENT varchar(50))DEFAULT CHARSET=UTF8;
Query OK, 0 rows affected (0.07 sec)

mysql> insert into test_shard (id,R_REGIONKEY,R_NAME,R_COMMENT) values (1,1, 'a string','test001'),(3,3, 'another string','test003'),(2,2, 'a\nstring','test002'),(4,4, '中','test004'),(5,5, 'a\'string\'','test005'),(6,6, 'a\""string\""','test006'),(7,7, 'a\bstring','test007'),(8,8, 'a\nstring','test008'),(9,9, 'a\rstring','test009'),(10,10, 'a\tstring','test010'),(11,11, 'a\zstring','test011'),(12,12, 'a\\string','test012'),(13,13, 'a\%string','test013'),(14,14, 'a\_string','test014'),(15,15, 'MySQL','test015'),(16,16, 'binary','test016'),(65,16, 'binary','test016'),(17,12345678901234567890123.4567890,17,17),(18,18, 'A','test018'),(19,19, '','test019');
Query OK, 20 rows affected (0.09 sec)
Records: 6  Duplicates: 0  Warnings: 0
```
execute select in dble:
```
mysql> select * from test_shard where id between 1 and (select 3 from test_shard limit 1);
ERROR 1064 (HY000): NullPointerException
```
execute select in mysql:
```
mysql> select * from test_shard where id between 1 and (select 3 from test_shard limit 1);
+----+-------------+----------------+-----------+
| id | R_REGIONKEY | R_NAME         | R_COMMENT |
+----+-------------+----------------+-----------+
|  1 |           1 | a string       | test001   |
|  2 |           2 | a
string       | test002   |
|  3 |           3 | another string | test003   |
+----+-------------+----------------+-----------+
3 rows in set (0.00 sec)
```
dble logs;
```
2018-06-15 13:55:15.668  INFO [BusinessExecutor1] (com.actiontech.dble.server.ServerConnection.executeException(ServerConnection.java:377)) - ServerConnection [id=8907, schema=mytest, host=127.0.0.1, user=test,txIsolation=3, autocommit=true, schema=mytest]select * from test_shard where id between 1 and (select 3 from test_shard limit 1) err:java.lang.NullPointerException
java.lang.NullPointerException: null
	at com.actiontech.dble.route.parser.druid.ServerSchemaStatVisitor.visit(ServerSchemaStatVisitor.java:164) ~[dble-2.18.06.0.jar:?]
	at com.alibaba.druid.sql.ast.expr.SQLBetweenExpr.accept0(SQLBetweenExpr.java:48) ~[druid-1.0.31.jar:1.0.31]
	at com.alibaba.druid.sql.ast.SQLObjectImpl.accept(SQLObjectImpl.java:41) ~[druid-1.0.31.jar:1.0.31]
	at com.alibaba.druid.sql.ast.SQLObjectImpl.acceptChild(SQLObjectImpl.java:63) ~[druid-1.0.31.jar:1.0.31]
	at com.alibaba.druid.sql.dialect.mysql.ast.statement.MySqlSelectQueryBlock.accept0(MySqlSelectQueryBlock.java:222) ~[druid-1.0.31.jar:1.0.31]
	at com.alibaba.druid.sql.dialect.mysql.ast.statement.MySqlSelectQueryBlock.accept0(MySqlSelectQueryBlock.java:210) ~[druid-1.0.31.jar:1.0.31]
	at com.alibaba.druid.sql.ast.SQLObjectImpl.accept(SQLObjectImpl.java:41) ~[druid-1.0.31.jar:1.0.31]
	at com.alibaba.druid.sql.visitor.SchemaStatVisitor.accept(SchemaStatVisitor.java:706) ~[druid-1.0.31.jar:1.0.31]
	at com.actiontech.dble.route.parser.druid.ServerSchemaStatVisitor.visit(ServerSchemaStatVisitor.java:339) ~[dble-2.18.06.0.jar:?]
	at com.alibaba.druid.sql.ast.statement.SQLSelect.accept0(SQLSelect.java:87) ~[druid-1.0.31.jar:1.0.31]
	at com.alibaba.druid.sql.ast.SQLObjectImpl.accept(SQLObjectImpl.java:41) ~[druid-1.0.31.jar:1.0.31]
	at com.alibaba.druid.sql.ast.SQLObjectImpl.acceptChild(SQLObjectImpl.java:63) ~[druid-1.0.31.jar:1.0.31]
	at com.alibaba.druid.sql.ast.statement.SQLSelectStatement.accept0(SQLSelectStatement.java:64) ~[druid-1.0.31.jar:1.0.31]
	at com.alibaba.druid.sql.ast.SQLObjectImpl.accept(SQLObjectImpl.java:41) ~[druid-1.0.31.jar:1.0.31]
	at com.actiontech.dble.route.parser.druid.impl.DefaultDruidParser.visitorParse(DefaultDruidParser.java:68) ~[dble-2.18.06.0.jar:?]
	at com.actiontech.dble.route.parser.druid.impl.DruidSelectParser.visitorParse(DruidSelectParser.java:114) ~[dble-2.18.06.0.jar:?]
	at com.actiontech.dble.route.parser.druid.impl.DefaultDruidParser.parser(DefaultDruidParser.java:53) ~[dble-2.18.06.0.jar:?]
	at com.actiontech.dble.route.util.RouterUtil.routeFromParser(RouterUtil.java:119) ~[dble-2.18.06.0.jar:?]
	at com.actiontech.dble.route.impl.DefaultRouteStrategy.routeNormalSqlWithAST(DefaultRouteStrategy.java:81) ~[dble-2.18.06.0.jar:?]
	at com.actiontech.dble.route.impl.AbstractRouteStrategy.route(AbstractRouteStrategy.java:60) ~[dble-2.18.06.0.jar:?]
	at com.actiontech.dble.route.RouteService.route(RouteService.java:111) ~[dble-2.18.06.0.jar:?]
	at com.actiontech.dble.server.ServerConnection.routeEndExecuteSQL(ServerConnection.java:314) [dble-2.18.06.0.jar:?]
	at com.actiontech.dble.server.ServerConnection.execute(ServerConnection.java:258) [dble-2.18.06.0.jar:?]
	at com.actiontech.dble.server.handler.SelectHandler.handle(SelectHandler.java:96) [dble-2.18.06.0.jar:?]
	at com.actiontech.dble.server.ServerQueryHandler.query(ServerQueryHandler.java:77) [dble-2.18.06.0.jar:?]
	at com.actiontech.dble.net.FrontendConnection.query(FrontendConnection.java:318) [dble-2.18.06.0.jar:?]
	at com.actiontech.dble.net.FrontendConnection.query(FrontendConnection.java:334) [dble-2.18.06.0.jar:?]
	at com.actiontech.dble.net.handler.FrontendCommandHandler.handleData(FrontendCommandHandler.java:77) [dble-2.18.06.0.jar:?]
	at com.actiontech.dble.net.handler.FrontendCommandHandler.handle(FrontendCommandHandler.java:55) [dble-2.18.06.0.jar:?]
	at com.actiontech.dble.net.handler.FrontEndHandlerRunnable.run(FrontEndHandlerRunnable.java:44) [dble-2.18.06.0.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_121]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]

```

**Comment by yanhuqing666** [comment]
import by #477
