### ISSUE TITLE
Hang when `order by` contains `subquery`

### ISSUE THREAD

**Issue by FlyingMao** [actiontech/dble#443]
steps：
```
mysql> select * from a_test order by (select pad from a_order limit 1);/*hang*/

```
log:
```
2018-01-25 11:25:26.562  INFO [complexQueryExecutor34] (com.actiontech.dble.backend.mysql.nio.MySQLConnectionHandler.handleDataError(MySQLConnectionHandler.java:212)) - MySQLConnection [id=32, lastTime=1516850726542, user=test, schema=db1, old schema=db1, borrowed=true, fromSlaveDB=false, threadId=6060,character_set_client=utf8,character_set_results=utf8,collation_connection=utf8_general_ci, txIsolation=3, autocommit=true, attachment=null, respHandler=com.actiontech.dble.backend.mysql.nio.handler.query.impl.BaseSelectHandler@3666418f, host=10.186.24.46, port=3307, statusSync=null, writeQueue=0, modifiedSQLExecuted=false] handle data error:
java.lang.NullPointerException: null
	at com.actiontech.dble.backend.mysql.nio.handler.util.RowDataComparator.<init>(RowDataComparator.java:40) ~[dble-2.17.11.0-dev.jar:?]
	at com.actiontech.dble.backend.mysql.nio.handler.query.impl.MultiNodeMergeHandler.makeRowDataSorter(MultiNodeMergeHandler.java:280) ~[dble-2.17.11.0-dev.jar:?]
	at com.actiontech.dble.backend.mysql.nio.handler.query.impl.MultiNodeMergeHandler.fieldEofResponse(MultiNodeMergeHandler.java:105) ~[dble-2.17.11.0-dev.jar:?]
	at com.actiontech.dble.backend.mysql.nio.handler.query.impl.BaseSelectHandler.fieldEofResponse(BaseSelectHandler.java:105) ~[dble-2.17.11.0-dev.jar:?]
	at com.actiontech.dble.backend.mysql.nio.MySQLConnectionHandler.handleFieldEofPacket(MySQLConnectionHandler.java:173) ~[dble-2.17.11.0-dev.jar:?]
	at com.actiontech.dble.backend.mysql.nio.MySQLConnectionHandler.handleData(MySQLConnectionHandler.java:99) [dble-2.17.11.0-dev.jar:?]
	at com.actiontech.dble.net.handler.BackendAsyncHandler$1.run(BackendAsyncHandler.java:37) [dble-2.17.11.0-dev.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_131]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_131]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]

```

**Comment by joycezhou007** [comment]
original issue order by with sub-query was fixed, but comments without semicolon is not supported, have reported issue #13 in intranet. Below sql1 is supported, sql2 isn't.

sql1= select * from a_test order by (select pad from a_order limit 1);/*hang*/; 
sql2= select * from a_test order by (select pad from a_order limit 1);/*hang*/
