### ISSUE TITLE
[SELECT JSON_EXTRACT(a_global_table_field, "$.id") xxxx  ] query get IndexOutOfBoundsException

### ISSUE THREAD

**Issue by irene-coming** [actiontech/dble#484]
**version**:5.6.29-dble-2.18.02.0-dev-20180323043211

**global_table1 related config:**

`<table name="global_table1" primaryKey="id" type="global" dataNode="dn1,dn2,dn3,dn4" />`

 ```xml
        <dataNode name="dn1" dataHost="172.100.9.5" database="db1" />
        <dataNode name="dn2" dataHost="172.100.9.6" database="db1" />
        <dataNode name="dn3" dataHost="172.100.9.5" database="db2" />
        <dataNode name="dn4" dataHost="172.100.9.6" database="db2" />

        <dataHost name="172.100.9.5" maxCon="1000" minCon="10" balance="0"
                          writeType="0" switchType="1"  slaveThreshold="100">
                <heartbeat>select user()</heartbeat>
                <writeHost host="hostM1" url="172.100.9.5:3306" user="test"
                                   password="111111">
                </writeHost>
        </dataHost>

        <dataHost name="172.100.9.6" maxCon="1000" minCon="10" balance="0"
                          writeType="0" switchType="1"  slaveThreshold="100">
                <heartbeat>select user()</heartbeat>
                <writeHost host="hostM2" url="172.100.9.6:3306" user="test"
                                   password="111111">
                </writeHost>
        </dataHost>
```

**steps:**
```mysql
drop table if exists global_table1;
create table global_table1(a json, b int);
insert into global_table1 values('{"id": "3", "name": "Barney"}' ,3),('{"id": "4", "name": "Betty"}' ,3), ('{"id": "2", "name": "Wilma"}',2);
SELECT a, JSON_EXTRACT(a, "$.id"), b FROM global_table1 WHERE JSON_EXTRACT(a, "$.id") > 1 ORDER BY JSON_EXTRACT(a, "$.name"); // ERROR 1003 (HY000): Invalid ordinal:245
```
dble.log:
```
2018-03-26 14:22:34.783 DEBUG [complexQueryExecutor1] (com.actiontech.dble.backend.heartbeat.MySQLConsistencyHelper.onResult(MySQLConsistencyHelper.java:49)) - resultresultresultresult:{"dataNode":"db1","result":{},"success":false}
2018-03-26 14:22:34.783  INFO [complexQueryExecutor1] (com.actiontech.dble.backend.heartbeat.MySQLConsistencyChecker.setResult(MySQLConsistencyChecker.java:136)) - null execute failed in db: db1 during global table consistency check task.
2018-03-26 14:22:34.783 DEBUG [complexQueryExecutor1] (com.actiontech.dble.server.util.GlobalTableUtil.finished(GlobalTableUtil.java:181)) - list:::::::::::[]
2018-03-26 14:22:34.855 DEBUG [BusinessExecutor3] (com.actiontech.dble.backend.datasource.PhysicalDBPool.getRWBalanceNode(PhysicalDBPool.java:536)) - select read source hostM1 for dataHost:172.100.9.5
2018-03-26 14:22:34.856  INFO [BusinessExecutor3] (com.actiontech.dble.backend.mysql.nio.handler.query.impl.BaseSelectHandler.execute(BaseSelectHandler.java:69)) - MySQLConnection [id=5, lastTime=1522045354856, user=test, schema=db1, old schema=db1, borrowed=true, fromSlaveDB=false, threadId=1247,character_set_client=latin1,character_set_results=latin1,collation_connection=latin1_swedish_ci, txIsolation=-1, autocommit=true, attachment=null, respHandler=com.actiontech.dble.backend.mysql.nio.handler.query.impl.BaseSelectHandler@3b24fc4b, host=172.100.9.5, port=3306, statusSync=null, writeQueue=0, modifiedSQLExecuted=false] send sql:select `global_table1`.`a`,JSON_EXTRACT(a, '$.id'),`global_table1`.`b` from  `global_table1` where JSON_EXTRACT(a, '$.id') > 1 order by JSON_EXTRACT(a, '$.name') ASC limit 0,100
2018-03-26 14:22:34.856 DEBUG [BusinessExecutor3] (com.actiontech.dble.backend.mysql.nio.MySQLConnection.synAndDoExecute(MySQLConnection.java:395)) - con need syn ,total syn cmd 1 commands SET SESSION TRANSACTION ISOLATION LEVEL REPEATABLE READ;schema change:false con:MySQLConnection [id=5, lastTime=1522045354856, user=test, schema=db1, old schema=db1, borrowed=true, fromSlaveDB=false, threadId=1247,character_set_client=latin1,character_set_results=latin1,collation_connection=latin1_swedish_ci, txIsolation=-1, autocommit=true, attachment=null, respHandler=com.actiontech.dble.backend.mysql.nio.handler.query.impl.BaseSelectHandler@3b24fc4b, host=172.100.9.5, port=3306, statusSync=null, writeQueue=0, modifiedSQLExecuted=false]
2018-03-26 14:22:34.856  INFO [BusinessExecutor3] (com.actiontech.dble.backend.mysql.nio.handler.builder.HandlerBuilder.build(HandlerBuilder.java:75)) - HandlerBuilder.build cost:8582996
2018-03-26 14:22:34.857 DEBUG [complexQueryExecutor1] (com.actiontech.dble.backend.mysql.nio.handler.query.impl.BaseSelectHandler.fieldEofResponse(BaseSelectHandler.java:91)) - MySQLConnection [id=5, lastTime=1522045354847, user=test, schema=db1, old schema=db1, borrowed=true, fromSlaveDB=false, threadId=1247,character_set_client=latin1,character_set_results=latin1,collation_connection=latin1_swedish_ci, txIsolation=3, autocommit=true, attachment=null, respHandler=com.actiontech.dble.backend.mysql.nio.handler.query.impl.BaseSelectHandler@3b24fc4b, host=172.100.9.5, port=3306, statusSync=com.actiontech.dble.backend.mysql.nio.MySQLConnection$StatusSync@1af4e0b2, writeQueue=0, modifiedSQLExecuted=false]'s field is reached.
2018-03-26 14:22:34.857  INFO [complexQueryExecutor1] (com.actiontech.dble.backend.mysql.nio.handler.query.impl.MultiNodeMergeHandler.fieldEofResponse(MultiNodeMergeHandler.java:95)) - MySQLConnection [id=5, lastTime=1522045354847, user=test, schema=db1, old schema=db1, borrowed=true, fromSlaveDB=false, threadId=1247,character_set_client=latin1,character_set_results=latin1,collation_connection=latin1_swedish_ci, txIsolation=3, autocommit=true, attachment=null, respHandler=com.actiontech.dble.backend.mysql.nio.handler.query.impl.BaseSelectHandler@3b24fc4b, host=172.100.9.5, port=3306, statusSync=com.actiontech.dble.backend.mysql.nio.MySQLConnection$StatusSync@1af4e0b2, writeQueue=0, modifiedSQLExecuted=false]'s field is reached.
2018-03-26 14:22:34.867  INFO [complexQueryExecutor1] (com.actiontech.dble.backend.mysql.nio.MySQLConnectionHandler.handleDataError(MySQLConnectionHandler.java:227)) - MySQLConnection [id=5, lastTime=1522045354847, user=test, schema=db1, old schema=db1, borrowed=true, fromSlaveDB=false, threadId=1247,character_set_client=latin1,character_set_results=latin1,collation_connection=latin1_swedish_ci, txIsolation=3, autocommit=true, attachment=null, respHandler=com.actiontech.dble.backend.mysql.nio.handler.query.impl.BaseSelectHandler@3b24fc4b, host=172.100.9.5, port=3306, statusSync=com.actiontech.dble.backend.mysql.nio.MySQLConnection$StatusSync@1af4e0b2, writeQueue=0, modifiedSQLExecuted=false] handle data error:
java.lang.IndexOutOfBoundsException: Invalid ordinal:245
        at com.actiontech.dble.plan.common.item.FieldTypes.valueOf(FieldTypes.java:58) ~[dble-2.18.02.0-dev.jar:?]
        at com.actiontech.dble.plan.common.field.Field.getFieldItem(Field.java:41) ~[dble-2.18.02.0-dev.jar:?]
        at com.actiontech.dble.plan.common.field.Field.getFieldItem(Field.java:29) ~[dble-2.18.02.0-dev.jar:?]
        at com.actiontech.dble.backend.mysql.nio.handler.util.HandlerTool.createField(HandlerTool.java:60) ~[dble-2.18.02.0-dev.jar:?]
        at com.actiontech.dble.backend.mysql.nio.handler.util.HandlerTool.createFields(HandlerTool.java:67) ~[dble-2.18.02.0-dev.jar:?]
        at com.actiontech.dble.backend.mysql.nio.handler.query.impl.SendMakeHandler.fieldEofResponse(SendMakeHandler.java:60) ~[dble-2.18.02.0-dev.jar:?]
        at com.actiontech.dble.backend.mysql.nio.handler.query.impl.MultiNodeMergeHandler.fieldEofResponse(MultiNodeMergeHandler.java:106) ~[dble-2.18.02.0-dev.jar:?]
        at com.actiontech.dble.backend.mysql.nio.handler.query.impl.BaseSelectHandler.fieldEofResponse(BaseSelectHandler.java:106) ~[dble-2.18.02.0-dev.jar:?]
        at com.actiontech.dble.backend.mysql.nio.MySQLConnectionHandler.handleFieldEofPacket(MySQLConnectionHandler.java:188) ~[dble-2.18.02.0-dev.jar:?]
        at com.actiontech.dble.backend.mysql.nio.MySQLConnectionHandler.handleData(MySQLConnectionHandler.java:110) [dble-2.18.02.0-dev.jar:?]
        at com.actiontech.dble.net.handler.BackendAsyncHandler.handleInnerData(BackendAsyncHandler.java:102) ~[dble-2.18.02.0-dev.jar:?]
        at com.actiontech.dble.net.handler.BackendAsyncHandler.access$000(BackendAsyncHandler.java:19) ~[dble-2.18.02.0-dev.jar:?]
        at com.actiontech.dble.net.handler.BackendAsyncHandler$1.run(BackendAsyncHandler.java:51) [dble-2.18.02.0-dev.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_121]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_121]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
2018-03-26 14:22:34.868  INFO [complexQueryExecutor1] (com.actiontech.dble.backend.mysql.nio.handler.query.impl.BaseSelectHandler.connectionError(BaseSelectHandler.java:138)) - MySQLConnection [id=5, lastTime=1522045354847, user=test, schema=db1, old schema=db1, borrowed=true, fromSlaveDB=false, threadId=1247,character_set_client=latin1,character_set_results=latin1,collation_connection=latin1_swedish_ci, txIsolation=3, autocommit=true, attachment=null, respHandler=com.actiontech.dble.backend.mysql.nio.handler.query.impl.BaseSelectHandler@3b24fc4b, host=172.100.9.5, port=3306, statusSync=com.actiontech.dble.backend.mysql.nio.MySQLConnection$StatusSync@1af4e0b2, writeQueue=0, modifiedSQLExecuted=false]|connectionError()|Invalid ordinal:245
```

**Comment by yanhuqing666** [comment]
select any_value(a), max(b) from global_table1 group by(b) ;
ERROR 1003 (HY000): Invalid ordinal:245

**Comment by yexiaoli88** [comment]
**version: 5.6.29-dble-2.18.06.0-20180605085901**

    mysql> SELECT a, JSON_EXTRACT(a, "$.id"), b FROM global_table1 WHERE JSON_EXTRACT(a, "$.id") > 
                 1 ORDER BY JSON_EXTRACT(a, "$.name");
    +-------------------------------+-------------------------+------+
    | a                             | JSON_EXTRACT(a, '$.id') | b    |
    +-------------------------------+-------------------------+------+
    | {"id": "3", "name": "Barney"} | "3"                     |    3 |
    | {"id": "4", "name": "Betty"}  | "4"                     |    3 |
    | {"id": "4", "name": "Wilma"}  | "4"                     |    2 |
    +-------------------------------+-------------------------+------+
    3 rows in set (0.06 sec)
