### ISSUE TITLE
parser Error when index contains comment

### ISSUE THREAD

**Issue by sbwfnhn** [actiontech/dble#495]
sql   "  UNIQUE KEY `USER_ID` (`USER_ID`) COMMENT '收款账户对应userId唯一性'  "

2018-04-03 12:01:38.993  INFO [complexQueryExecutor21] (com.actiontech.dble.backend.mysql.nio.MySQLConnectionHandler.handleDataError(MySQLConnectionHandler.java:212)) - MySQLConnection [id=8, lastTime=1522728097924, user=root, schema=aa1, old schema=aa1, borrowed=false, fromSlaveDB=false, threadId=119,character_set_client=utf8,character_set_results=utf8,collation_connection=utf8_general_ci, txIsolation=-1, autocommit=true, attachment=null, respHandler=null, host=192.168.10.153, port=3306, statusSync=null, writeQueue=0, modifiedSQLExecuted=false] handle data error:
com.alibaba.druid.sql.parser.ParserException: syntax error, error in :'ID`) COMMENT '收款账户对应userId唯一性'
) EN',expect RPAREN, actual COMMENT COMMENT
        at com.alibaba.druid.sql.parser.SQLParser.printError(SQLParser.java:261) ~[druid-1.0.31.jar:1.0.31]
        at com.alibaba.druid.sql.parser.SQLParser.accept(SQLParser.java:269) ~[druid-1.0.31.jar:1.0.31]
        at com.alibaba.druid.sql.dialect.mysql.parser.MySqlCreateTableParser.parseCrateTable(MySqlCreateTableParser.java:182) ~[druid-1.0.31.jar:1.0.31]
        at com.alibaba.druid.sql.dialect.mysql.parser.MySqlCreateTableParser.parseCrateTable(MySqlCreateTableParser.java:67) ~[druid-1.0.31.jar:1.0.31]
        at com.alibaba.druid.sql.dialect.mysql.parser.MySqlStatementParser.parseCreateTable(MySqlStatementParser.java:252) ~[druid-1.0.31.jar:1.0.31]
        at com.actiontech.dble.meta.table.AbstractTableMetaHandler$MySQLTableStructureListener.initTableMeta(AbstractTableMetaHandler.java:138) ~[dble-2.17.11.0.jar:?]
        at com.actiontech.dble.meta.table.AbstractTableMetaHandler$MySQLTableStructureListener.onResult(AbstractTableMetaHandler.java:116) ~[dble-2.17.11.0.jar:?]
        at com.actiontech.dble.meta.table.AbstractTableMetaHandler$MySQLTableStructureListener.onResult(AbstractTableMetaHandler.java:70) ~[dble-2.17.11.0.jar:?]
        at com.actiontech.dble.sqlengine.OneRawSQLQueryResultHandler.finished(OneRawSQLQueryResultHandler.java:90) ~[dble-2.17.11.0.jar:?]
        at com.actiontech.dble.sqlengine.SQLJob.doFinished(SQLJob.java:94) ~[dble-2.17.11.0.jar:?]
        at com.actiontech.dble.sqlengine.SQLJob.rowEofResponse(SQLJob.java:155) ~[dble-2.17.11.0.jar:?]
        at com.actiontech.dble.backend.mysql.nio.MySQLConnectionHandler.handleRowEofPacket(MySQLConnectionHandler.java:204) ~[dble-2.17.11.0.jar:?]
        at com.actiontech.dble.backend.mysql.nio.MySQLConnectionHandler.handleData(MySQLConnectionHandler.java:113) [dble-2.17.11.0.jar:?]
        at com.actiontech.dble.net.handler.BackendAsyncHandler$1.run(BackendAsyncHandler.java:37) [dble-2.17.11.0.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_161]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_161]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]

**Comment by sunsun314** [comment]
the fix only support the dble wouldn't throw error when init the table meta,but create table with index contains comment still not supported

**Comment by FlyingMao** [comment]
**verified version:**
5.6.29-dble-9.9.9.9-359645c-20181029082136

**Comment by FlyingMao** [comment]
**for tester:**
suggest autotest position: sqls/select/create_table_definition.sql (reference line 602)
