### ISSUE TITLE
some manager commands got error with MySQLdb driver

### ISSUE THREAD

**Issue by irene-coming** [actiontech/dble#569]
* **dble version：**  
5.6.29-dble-2.18.06.0-20180619072937
* **preconditions ：**  
use MySQLdb driver, mysql client can success
* **steps：**    
    step1.  
```python
[root@10-186-23-68 dble]# python
Python 2.7.5 (default, Aug  4 2017, 00:39:18)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-16)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import MySQLdb
>>> conn=MySQLdb.connect('172.100.9.1', 'root','111111','', 9066, autocommit=True)
>>> cur=conn.cursor()
>>> cur.execute("show @@cache")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/MySQL_python-1.2.5-py2.7-linux-x86_64.egg/MySQLdb/cursors.py", line 205, in execute
  File "/usr/lib/python2.7/site-packages/MySQL_python-1.2.5-py2.7-linux-x86_64.egg/MySQLdb/connections.py", line 36, in defaulterrorhandler
ValueError: invalid literal for long() with base 10: ''
>>> cur.execute("show @@version")
1L
>>> cur.execute("show @@connection.sql")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/MySQL_python-1.2.5-py2.7-linux-x86_64.egg/MySQLdb/cursors.py", line 205, in execute
  File "/usr/lib/python2.7/site-packages/MySQL_python-1.2.5-py2.7-linux-x86_64.egg/MySQLdb/connections.py", line 36, in defaulterrorhandler
ValueError: invalid literal for long() with base 10: '2018/06/20 15:03:45'
```
* **expect result：**  
    1. manager command query success
* **real result：**  
    1. some of them seems result type error
* **supplements：**  
    1. more manager commands test will cover in future
    2. to tester: uncomment /schema.feature/ no.3 scenario/ execute manager.sql step/ when fixed

/label ~BUG

**Comment by irene-coming** [comment]
failure possible commands:
![image](https://user-images.githubusercontent.com/6801133/41643169-16c10c48-749d-11e8-84af-056117c7c20f.png)
