### ISSUE TITLE
union & concat & join can't work together

### ISSUE THREAD

**Issue by cntechpower** [actiontech/dble#581]
* **dble version：**  
`5.6.23-dble-9.9.9.9-20180629104837`
* **preconditions ：**  
no
* **configs：** 

**schema.xml**  

```xml
<?xml version="1.0"?>
<!DOCTYPE dble:schema SYSTEM "schema.dtd">
<dble:schema xmlns:dble="http://dble.cloud/">
    <schema name="logic_schema" sqlMaxLimit="100">
        <table name="t1" type="default" primaryKey="id" needAddLimit="true" rule="logic_schema__t1" dataNode="DataNode1"></table>
        <table name="t2" type="default" primaryKey="id" needAddLimit="true" rule="logic_schema__t2" dataNode="DataNode1"></table>
        <table name="t3" type="default" primaryKey="id" needAddLimit="true" rule="logic_schema__t3" dataNode="DataNode1"></table>
    </schema>
    <dataNode name="DataNode1" dataHost="DataHost1" database="node1"></dataNode>
    <dataHost name="DataHost1" maxCon="100" minCon="10" balance="0" switchType="-1" slaveThreshold="-1">
        <heartbeat>show slave status</heartbeat>
        <writeHost host="mysql-j5cfd7" url="10.186.31.16:3306" user="admin" password="izUD5EkKjuSyCkrY9dkrkPdCH2kgvBb+W1xMihfXuaNqGE2CC6aIYP+J3Qdwxwr68ufdbTFIDpv+lHVZkDq0Kg==" id="mysql-j5cfd7" usingDecrypt="1"></writeHost>
    </dataHost>
</dble:schema>

```

**rule.xml**  

```xml
<?xml version="1.0"?>
<!DOCTYPE dble:rule SYSTEM "rule.dtd">
<dble:rule xmlns:dble="http://dble.cloud/">
    <tableRule name="logic_schema__t1">
        <rule>
            <columns>id</columns>
            <algorithm>logic_schema__t1</algorithm>
        </rule>
    </tableRule>
    <tableRule name="logic_schema__t2">
        <rule>
            <columns>id</columns>
            <algorithm>logic_schema__t2</algorithm>
        </rule>
    </tableRule>
    <tableRule name="logic_schema__t3">
        <rule>
            <columns>id</columns>
            <algorithm>logic_schema__t2</algorithm>
        </rule>
    </tableRule>
    <function name="logic_schema__t1" class="NumberRange">
        <property name="mapFile">logic_schema__t1.rule.auto</property>
        <property name="defaultNode">0</property>
    </function>
    <function name="logic_schema__t2" class="NumberRange">
        <property name="mapFile">logic_schema__t2.rule.auto</property>
        <property name="defaultNode">0</property>
    </function>
</dble:rule>

```
**rule.txt**
```
0-200=0
```
**server.xml**  

```xml
<?xml version="1.0"?>
<!DOCTYPE dble:server SYSTEM "server.dtd">
<dble:server xmlns:dble="http://dble.cloud/">
    <system>
        <property name="serverPort">3306</property>
        <property name="managerPort">3310</property>
        <property name="charset">utf8</property>
        <property name="lowerCaseTableNames">false</property>
        <property name="fakeMySQLVersion">5.6.23</property>
        <property name="useOffHeapForMerge">0</property>
        <property name="processors">1</property>
        <property name="sequnceHandlerType">2</property>
        <property name="txIsolation">2</property>
        <property name="sqlExecuteTimeout">3600</property>
    </system>
    <user name="root">
        <property name="password">GK56FpVYZefmx+GUcy9Fm18MGeXRIfwpGrNYCn9GhaqeSbDonfNmKQcL/ex+B3XJ1D/Kfut5FehOQGRymx/9Wg==</property>
        <property name="manager">true</property>
        <property name="readOnly">true</property>
        <property name="usingDecrypt">1</property>
    </user>
    <user name="admin">
        <property name="password">QxpyJIVf6e9bgSeF5dBQkgZBZyH9FgaOqRhdJRyxGNufD+rBLG83HiIRx5tQOZ+pCfLVz57tCUkBFA5xfECOPg==</property>
        <property name="readOnly">false</property>
        <property name="schemas">logic_schema</property>
        <property name="benchmark">100</property>
        <property name="usingDecrypt">1</property>
    </user>
</dble:server>

```

* **steps：**    
 ```sql
/*Pre Data*/
create table t1(id int primary key,name varchar(10));
create table t2(id int primary key,name varchar(10));
create table t3(id int primary key,name varchar(10));
insert into t1 values(1,'actiontech');
insert into t2 values(1,'actiontech');
insert into t3 values(1,'actiontech');

/*Stmt 1*/
select a.id,a.name from t1 a join t2 b where a.id=b.id union  select id,name from t3;

/*Stmt 2*/
select id,concat(id,'_',name)from t1 union all select id,concat(id,'_',name)from t1;

/*Stmt 3*/
select a.id,concat(a.id,'_',a.name) from t1 a join t2 b where a.id=b.id union  select id,concat(id,'_',name)from t3;


```
* **expect result：**  
    1.`Stmt 1 & 2 & 3`  Can all succeed 
* **real result：**  
    1.`Stmt 1 & 2` succeed ,Stmt 3 faild with `ERROR 1003 (HY000): Union field merge error, null`
* **supplements：**  
**dble.log**
```
2018-07-02 16:45:39.569  INFO [complexQueryExecutor3] (com.actiontech.dble.backend.mysql.nio.handler.query.impl.UnionHandler.fieldEofResponse(UnionHandler.java:78)) - Union field merge error, null
java.lang.NullPointerException: null
        at com.actiontech.dble.backend.mysql.nio.handler.query.impl.UnionHandler.checkFieldPackets(UnionHandler.java:92) ~[dble-9.9.9.9.jar:?]
        at com.actiontech.dble.backend.mysql.nio.handler.query.impl.UnionHandler.fieldEofResponse(UnionHandler.java:68) [dble-9.9.9.9.jar:?]
        at com.actiontech.dble.backend.mysql.nio.handler.query.impl.SendMakeHandler.fieldEofResponse(SendMakeHandler.java:84) [dble-9.9.9.9.jar:?]
        at com.actiontech.dble.backend.mysql.nio.handler.query.impl.join.JoinHandler.fieldEofResponse(JoinHandler.java:103) [dble-9.9.9.9.jar:?]
        at com.actiontech.dble.backend.mysql.nio.handler.query.impl.SendMakeHandler.fieldEofResponse(SendMakeHandler.java:84) [dble-9.9.9.9.jar:?]
        at com.actiontech.dble.backend.mysql.nio.handler.query.impl.MultiNodeMergeHandler.fieldEofResponse(MultiNodeMergeHandler.java:106) [dble-9.9.9.9.jar:?]
        at com.actiontech.dble.backend.mysql.nio.handler.query.impl.BaseSelectHandler.fieldEofResponse(BaseSelectHandler.java:107) [dble-9.9.9.9.jar:?]
        at com.actiontech.dble.backend.mysql.nio.MySQLConnectionHandler.handleFieldEofPacket(MySQLConnectionHandler.java:188) [dble-9.9.9.9.jar:?]
        at com.actiontech.dble.backend.mysql.nio.MySQLConnectionHandler.handleData(MySQLConnectionHandler.java:110) [dble-9.9.9.9.jar:?]
        at com.actiontech.dble.net.handler.BackendAsyncHandler.handleInnerData(BackendAsyncHandler.java:102) [dble-9.9.9.9.jar:?]
        at com.actiontech.dble.net.handler.BackendAsyncHandler.access$000(BackendAsyncHandler.java:19) [dble-9.9.9.9.jar:?]
        at com.actiontech.dble.net.handler.BackendAsyncHandler$1.run(BackendAsyncHandler.java:51) [dble-9.9.9.9.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_111]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_111]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]

```

/label ~BUG

**Comment by yanhuqing666** [comment]
need Regression Test #116 #359 f5873b69c874a8e62003f43b8d86867262e11595
