### ISSUE TITLE
send ddl query after maxConn was reached, then ddl lock is added, but expect not

### ISSUE THREAD

**Issue by irene-coming** [actiontech/dble#583]
* **dble version：**  
5.6.23-dble-2.18.07.0-20180704103721

* **preconditions ：**  

* **configs：** 

**schema.xml**  

```
<?xml version='1.0' encoding='utf-8'?>
<!DOCTYPE dble:schema SYSTEM "schema.dtd">
    <schema name="mytest">
        <table name="test" rule="hash" dataNode="dn1,dn2"></table>
        <table name="test2" rule="hash" dataNode="dn1,dn2"></table>
    </schema>
    <dataNode name="dn1" dataHost="dh1" database="db1"></dataNode>
    <dataNode name="dn2" dataHost="dh1" database="db2"></dataNode>
    <dataHost name="dh1" maxCon="10" minCon="6" balance="1" switchType="-1" slaveThreshold="100" tempReadHostAvailable="1">
        <heartbeat>select user()</heartbeat>
        <writeHost host="hostS1" url="10.186.30.86:19388" user="test" password="iL6aRQPepyK5St5GKaSf/CmbB57tFftEeG0oDOtkQSgCno8lDP9/UHkkYpRw2G/biCmeL7W+cF5RsdHoLNW3fg==" id="mysql-wdidsx" usingDecrypt="1">
            <readHost host="hostM1" url="10.186.30.101:19288" user="test" password="EZGuPOlq+lyYvtnAHPYN7NOido4idWDJfdH0aAWsXzfPhxDw0FWIDoYtxy0LL45slFFtLXl9NukyJujadQEoUA==" id="mysql-c7ltz5" usingDecrypt="1"></readHost>
            <readHost host="hostS2" url="10.186.30.102:19388" user="test" password="AQbe8FigOzVHNWerielX8iB+WvxpMY+0EwQEV1Q/IgVdaask3O+u8w3BBzbSa58lJ32O4qCMbE+VpFpVg9gAZw==" id="mysql-v5m5y2" usingDecrypt="1"></readHost>
        </writeHost>
    </dataHost>
<dble:schema xmlns:dble="http://dble.cloud/">

```

**rule.xml**  

```
<?xml version='1.0' encoding='utf-8'?>
<!DOCTYPE dble:rule SYSTEM "rule.dtd">
       <tableRule name="hash">
        <rule>
            <columns>id</columns>
            <algorithm>two-long</algorithm>
        </rule>
    </tableRule>
    <function class="Hash" name="two-long">
        <property name="partitionCount">2</property>
        <property name="partitionLength">1</property>
    </function>
<dble:rule xmlns:dble="http://dble.cloud/">

```

**server.xml**  

```
<?xml version='1.0' encoding='utf-8'?>
<!DOCTYPE dble:server SYSTEM "server.dtd"><dble:server xmlns:dble="http://dble.cloud/">

```

* **steps：**    
    step1.  make the maxConn all occupied
```python
conns = []
def create_conns(conns, num, ip='10.186.30.101', port=8066):
    for i in range(0,num):
        # conn =  MySQLdb.connect(ip, 'uproxy', '111111','mytest', port, autocommit=True, charset = "utf8", use_unicode = True)
        conn =  MySQLdb.connect(ip, 'test', '111111','mytest', port, autocommit=True)
        conns.insert(0, conn)
    print "made %s conns"%num

def exec_sql(conns, type='r'):
    i = 0
    for conn in conns:
        cur = conn.cursor()
        if type=='r':
            cur.execute('start transaction read only')
        else:
            i = i+1
            cur.execute('start transaction')
            cur.execute('select 1')
        cur.fetchall()

def close_conns(conns):
    for conn in conns:
        conn.close()

>>> create_conns(conns, 30)
made 30 conns
>>> exec_sql(conns, 'www')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 10, in exec_sql
  File "/usr/lib64/python2.7/site-packages/MySQLdb/cursors.py", line 205, in execute
    self.errorhandler(self, exc, value)
  File "/usr/lib64/python2.7/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
_mysql_exceptions.InterfaceError: (-1, 'error totally whack')
```

step2. open a new dble session A and query:
mysql> alter table test add column col2 int;
ERROR 3009 (HY000): java.io.IOException: the max active Connections size can not be max than maxCon for data host[dh1.hostS1]

step3. release the occupied connections
```python
close_conns(conns)
```
step4. open a new dble session B and query:
mysql> alter table test add column col2 int;
ERROR 4006 (HY000): SCHEMA[mytest], TABLE[test] is doing DDL

* **expect result：**  
    1. if ddl query got err feedback, then the ddl should not be locked
* **real result：**  
    1.ddl query got err feedback, but the ddl lock is in work
* **supplements：**  
    1.

/label ~BUG

**Comment by yexiaoli88** [comment]
verified on version: 5.6.29-dble-2.18.07.0-20180706034436
