### ISSUE TITLE
Client get lost connection when try to load data local for a empty file

### ISSUE THREAD

**Issue by sunsun314** [actiontech/dble#683]
* **dble version：**  lastest
* **preconditions ：**  

* **configs：** 

**schema.xml**  
default

**rule.xml**  
default

**server.xml**  
default

* **steps：**    
execute sql 
load data local infile  "C:/workspace/test.txt" into table table_a fields terminated by',' lines terminated by '/n';
* **expect result：**  
Query OK, 0 rows affected (2.95 sec)
Records: 0  Deleted: 0  Skipped: 0  Warnings: 0
* **real result：**  
ERROR 2013 (HY000): Lost connection to MySQL server during query

/label ~BUG

**Comment by irene-coming** [comment]
bug found on version:5.6.29-dble-9.9.9.9-18e8b31-20180903030245

**Comment by irene-coming** [comment]
dble commit version:5.6.29-dble-2.18.09.1-2b298cd-20180904021034
**case1. with no lines in test.txt:**
dble:
```mysql
mysql> load data local infile "/opt/dble/test.txt" into table table_a fields terminated by ',' lines terminated by '\n';
Query OK, 0 rows affected (0.00 sec)
Records: 0  Deleted: 0  Skipped: 0  Warnings: 0
mysql> load data infile "/opt/dble/test.txt" into table table_a fields terminated by ',' lines terminated by '/n';
ERROR 1046 (HY000): No dataNode found ,please check tables defined in schema:mytest
mysql> use mytest
Database changed
mysql> load data infile "/opt/dble/test.txt" into table table_a fields terminated by ',' lines terminated by '/n';
ERROR 1046 (HY000): No dataNode found ,please check tables defined in schema:mytest
```

**case2. with 1 empty line in test.txt (echo> test.txt)**
dble:
```mysql
mysql> load data local infile "/opt/dble/test.txt" into table table_a fields terminated by ',' lines terminated by '/n';
ERROR 2013 (HY000): Lost connection to MySQL server during query
```
mysql:
```mysql
mysql> select * from table_a;
Empty set (0.01 sec)
mysql> load data local infile "/opt/test.txt" into table table_a fields terminated by ','lines terminated by '\n';
Query OK, 1 row affected, 2 warnings (0.00 sec)
Records: 1  Deleted: 0  Skipped: 0  Warnings: 2
mysql> show warnings;
+---------+------+------------------------------------------------------+
| Level   | Code | Message                                              |
+---------+------+------------------------------------------------------+
| Warning | 1366 | Incorrect integer value: '' for column 'id' at row 1 |
| Warning | 1261 | Row 1 doesn't contain data for all columns           |
+---------+------+------------------------------------------------------+
2 rows in set (0.00 sec)
mysql> select * from table_a;
+------+------+
| id   | aa   |
+------+------+
|    0 | NULL |
+------+------+
1 row in set (0.00 sec)
```

**case3. with 2 lines data in test.txt**
```
3,333
4,444
```
dble:
```mysql
mysql> truncate table table_a;
Query OK, 0 rows affected (0.04 sec)
mysql> load data local infile "/opt/dble/test.txt" into table table_a fields terminated by ',' lines terminated by '\n';
ERROR 2013 (HY000): Lost connection to MySQL server during query
```
mysql:
```mysql
mysql> truncate table table_a;
Query OK, 0 rows affected (0.04 sec)
mysql> load data local infile "/opt/test.txt" into table table_a fields terminated by ',' lines terminated by '\n'; Query OK, 2 rows affected (0.00 sec)
Records: 2  Deleted: 0  Skipped: 0  Warnings: 0
mysql> select * from table_a;
+------+------+
| id   | aa   |
+------+------+
|    3 |  333 |
|    4 |  444 |
+------+------+
2 rows in set (0.00 sec)
```

**Comment by irene-coming** [comment]
dble commit version:5.6.29-dble-2.18.09.1-2b298cd-20180904021034
with multi-times operation as above, other queries( not "load data ...") are affected:

![image](https://user-images.githubusercontent.com/6801133/45016387-0eb22780-b057-11e8-9e68-ed144334d06c.png)

**Comment by irene-coming** [comment]
dble version: 5.6.29-dble-2.18.09.1-0752712-20180905032631
preconditions: table sharding_two_node has two sharding by hash
steps:
step1: CREATE TABLE `sharding_two_node` (
  `id` int(11) NOT NULL,
  `c_flag` char(255) DEFAULT NULL,
  `c_decimal` decimal(16,4) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8
step2: create test.txt, and fill contents:1,abc$%'";:@#^&*_+-=|\<.>/?`~,2.35
step3:
```mysql
mysql> load data local infile "/opt/dble/test.txt" into table sharding_two_node fields terminated by',' lines terminated by '\n';
ERROR 2013 (HY000): Lost connection to MySQL server during query
```
with mysql, step3 success

dble log:
```log
2018-09-05 05:41:01.086 DEBUG [BusinessExecutor7] (com.actiontech.dble.server.ServerQueryHandler.query(ServerQueryHandler.java:44)) - ServerConnection [id=1, schema=mytest, host=127.0.0.1, user=test,txIsolation=3, autocommit=true, schema=mytest]load data local infile "/opt/dble/test.txt" into table sharding_two_node fields terminated by',' lines terminated by '\n'
2018-09-05 05:41:01.246  INFO [$_NIO_REACTOR_FRONT-1-RW] (com.actiontech.dble.route.impl.DefaultRouteStrategy.parserSQL(DefaultRouteStrategy.java:37)) - routeNormalSqlWithAST
com.alibaba.druid.sql.parser.ParserException: syntax error, token: ERROR abc$%, pos : 91
        at com.alibaba.druid.sql.dialect.mysql.parser.MySqlExprParser.primaryRest(MySqlExprParser.java:488) ~[druid-1.0.31.jar:1.0.31]
        at com.alibaba.druid.sql.dialect.mysql.parser.MySqlStatementParser.parseValueClause(MySqlStatementParser.java:2240) ~[druid-1.0.31.jar:1.0.31]
        at com.alibaba.druid.sql.dialect.mysql.parser.MySqlStatementParser.parseInsert(MySqlStatementParser.java:2153) ~[druid-1.0.31.jar:1.0.31]
        at com.alibaba.druid.sql.dialect.mysql.parser.MySqlStatementParser.parseInsert(MySqlStatementParser.java:194) ~[druid-1.0.31.jar:1.0.31]
        at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:135) ~[druid-1.0.31.jar:1.0.31]
        at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:84) ~[druid-1.0.31.jar:1.0.31]
        at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatement(SQLStatementParser.java:2094) ~[druid-1.0.31.jar:1.0.31]
        at com.actiontech.dble.route.impl.DefaultRouteStrategy.parserSQL(DefaultRouteStrategy.java:35) [dble-2.18.09.1.jar:?]
        at com.actiontech.dble.route.impl.DefaultRouteStrategy.routeNormalSqlWithAST(DefaultRouteStrategy.java:73) [dble-2.18.09.1.jar:?]
        at com.actiontech.dble.route.impl.AbstractRouteStrategy.route(AbstractRouteStrategy.java:60) [dble-2.18.09.1.jar:?]
        at com.actiontech.dble.route.RouteService.route(RouteService.java:112) [dble-2.18.09.1.jar:?]
        at com.actiontech.dble.server.ServerConnection.routeSQL(ServerConnection.java:277) [dble-2.18.09.1.jar:?]
        at com.actiontech.dble.server.handler.ServerLoadDataInfileHandler.parseOneLine(ServerLoadDataInfileHandler.java:325) [dble-2.18.09.1.jar:?]
        at com.actiontech.dble.server.handler.ServerLoadDataInfileHandler.end(ServerLoadDataInfileHandler.java:586) [dble-2.18.09.1.jar:?]
        at com.actiontech.dble.net.FrontendConnection.loadDataInfileEnd(FrontendConnection.java:283) [dble-2.18.09.1.jar:?]
        at com.actiontech.dble.net.FrontendConnection.rawHandle(FrontendConnection.java:464) [dble-2.18.09.1.jar:?]
        at com.actiontech.dble.net.FrontendConnection.handle(FrontendConnection.java:455) [dble-2.18.09.1.jar:?]
        at com.actiontech.dble.net.AbstractConnection.onReadData(AbstractConnection.java:313) [dble-2.18.09.1.jar:?]
        at com.actiontech.dble.net.NIOSocketWR.asyncRead(NIOSocketWR.java:171) [dble-2.18.09.1.jar:?]
        at com.actiontech.dble.net.AbstractConnection.asyncRead(AbstractConnection.java:264) [dble-2.18.09.1.jar:?]
        at com.actiontech.dble.net.NIOReactor$RW.executeKeys(NIOReactor.java:119) [dble-2.18.09.1.jar:?]
        at com.actiontech.dble.net.NIOReactor$RW.run(NIOReactor.java:90) [dble-2.18.09.1.jar:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
```

**Comment by irene-coming** [comment]
dble version: 5.6.29-dble-2.18.09.1-f2daf46-20180905070057
does not support set character set in "load data ... statement", so the Chinese character is not supported

![image](https://user-images.githubusercontent.com/6801133/45135397-b6ebfb80-b1d1-11e8-9f87-09b778ac6331.png)

**Comment by sunsun314** [comment]
druid parser can only analysis  the character  set  'charset_name'
