### ISSUE TITLE
some special character in file may make query "load data ... " fail

### ISSUE THREAD

**Issue by irene-coming** [actiontech/dble#703]
dble version: 5.6.29-dble-2.18.09.1-0752712-20180905032631
preconditions: table sharding_two_node has two sharding by hash
steps:
step1: CREATE TABLE `sharding_two_node` (
  `id` int(11) NOT NULL,
  `c_flag` char(255) DEFAULT NULL,
  `c_decimal` decimal(16,4) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8
step2: create test.txt, and fill contents:1,abc$%'";:@#^&*_+-=|\<.>/?`~,2.35
step3:
```mysql
mysql> load data local infile "/opt/dble/test.txt" into table sharding_two_node fields terminated by',' lines terminated by '\n';
ERROR 2013 (HY000): Lost connection to MySQL server during query
```
with mysql, step3 success

dble log:
```log
2018-09-05 05:41:01.086 DEBUG [BusinessExecutor7] (com.actiontech.dble.server.ServerQueryHandler.query(ServerQueryHandler.java:44)) - ServerConnection [id=1, schema=mytest, host=127.0.0.1, user=test,txIsolation=3, autocommit=true, schema=mytest]load data local infile "/opt/dble/test.txt" into table sharding_two_node fields terminated by',' lines terminated by '\n'
2018-09-05 05:41:01.246  INFO [$_NIO_REACTOR_FRONT-1-RW] (com.actiontech.dble.route.impl.DefaultRouteStrategy.parserSQL(DefaultRouteStrategy.java:37)) - routeNormalSqlWithAST
com.alibaba.druid.sql.parser.ParserException: syntax error, token: ERROR abc$%, pos : 91
        at com.alibaba.druid.sql.dialect.mysql.parser.MySqlExprParser.primaryRest(MySqlExprParser.java:488) ~[druid-1.0.31.jar:1.0.31]
        at com.alibaba.druid.sql.dialect.mysql.parser.MySqlStatementParser.parseValueClause(MySqlStatementParser.java:2240) ~[druid-1.0.31.jar:1.0.31]
        at com.alibaba.druid.sql.dialect.mysql.parser.MySqlStatementParser.parseInsert(MySqlStatementParser.java:2153) ~[druid-1.0.31.jar:1.0.31]
        at com.alibaba.druid.sql.dialect.mysql.parser.MySqlStatementParser.parseInsert(MySqlStatementParser.java:194) ~[druid-1.0.31.jar:1.0.31]
        at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:135) ~[druid-1.0.31.jar:1.0.31]
        at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:84) ~[druid-1.0.31.jar:1.0.31]
        at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatement(SQLStatementParser.java:2094) ~[druid-1.0.31.jar:1.0.31]
        at com.actiontech.dble.route.impl.DefaultRouteStrategy.parserSQL(DefaultRouteStrategy.java:35) [dble-2.18.09.1.jar:?]
        at com.actiontech.dble.route.impl.DefaultRouteStrategy.routeNormalSqlWithAST(DefaultRouteStrategy.java:73) [dble-2.18.09.1.jar:?]
        at com.actiontech.dble.route.impl.AbstractRouteStrategy.route(AbstractRouteStrategy.java:60) [dble-2.18.09.1.jar:?]
        at com.actiontech.dble.route.RouteService.route(RouteService.java:112) [dble-2.18.09.1.jar:?]
        at com.actiontech.dble.server.ServerConnection.routeSQL(ServerConnection.java:277) [dble-2.18.09.1.jar:?]
        at com.actiontech.dble.server.handler.ServerLoadDataInfileHandler.parseOneLine(ServerLoadDataInfileHandler.java:325) [dble-2.18.09.1.jar:?]
        at com.actiontech.dble.server.handler.ServerLoadDataInfileHandler.end(ServerLoadDataInfileHandler.java:586) [dble-2.18.09.1.jar:?]
        at com.actiontech.dble.net.FrontendConnection.loadDataInfileEnd(FrontendConnection.java:283) [dble-2.18.09.1.jar:?]
        at com.actiontech.dble.net.FrontendConnection.rawHandle(FrontendConnection.java:464) [dble-2.18.09.1.jar:?]
        at com.actiontech.dble.net.FrontendConnection.handle(FrontendConnection.java:455) [dble-2.18.09.1.jar:?]
        at com.actiontech.dble.net.AbstractConnection.onReadData(AbstractConnection.java:313) [dble-2.18.09.1.jar:?]
        at com.actiontech.dble.net.NIOSocketWR.asyncRead(NIOSocketWR.java:171) [dble-2.18.09.1.jar:?]
        at com.actiontech.dble.net.AbstractConnection.asyncRead(AbstractConnection.java:264) [dble-2.18.09.1.jar:?]
        at com.actiontech.dble.net.NIOReactor$RW.executeKeys(NIOReactor.java:119) [dble-2.18.09.1.jar:?]
        at com.actiontech.dble.net.NIOReactor$RW.run(NIOReactor.java:90) [dble-2.18.09.1.jar:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
```

_Originally posted by @irene-coming in https://github.com/actiontech/dble/issues/683#issuecomment-418607429_

**Comment by yexiaoli88** [comment]
verified on version: 5.6.29-dble-9.9.9.9-ea3eaeb-20180929033800
