### ISSUE TITLE
query "select * from test_shard where id>(SELECT ABS(2)) order by id;" got error

### ISSUE THREAD

**Issue by yexiaoli88** [actiontech/dble#725]
* **dble version：5.6.29-dble-9.9.9.9-21b7b82-20180925034029**  
* **preconditions ：**  
no
* **configs：** 

**schema.xml**  

```
<table name="test_shard" dataNode="dn1,dn2,dn3,dn4" rule="mod-long"/>

```

**rule.xml**  

```
<function name="hashmod" class="Hash">
        <property name="partitionCount">4</property>
        <property name="partitionLength">1</property>
    </function>

```

* **steps：**    
    step1.  
```
mysql> select * from test_shard where id>(SELECT ABS(2)) order by id;
ERROR 1105 (HY000): field not found:ABS(2)
```
2.check log
```
2018-09-26 09:13:30.337  INFO [complexQueryExecutor5] (com.actiontech.dble.backend.mysql.nio.MySQLConnectionHandler.handleDataError(MySQLConnectionHandler.java:230)) - MySQLConnection [id=11, lastTime=1537953210320, user=test, schema=db3, old schema=db3, borrowed=true, fromSlaveDB=false, threadId=6860,character_set_client=utf8,character_set_results=utf8,collation_connection=utf8_general_ci, txIsolation=3, autocommit=true, attachment=dn5{SELECT ABS(2)}.0, respHandler=com.actiontech.dble.backend.mysql.nio.handler.query.impl.BaseSelectHandler@5e904ffb, host=172.100.9.5, port=3306, statusSync=null, writeQueue=0, modifiedSQLExecuted=false] handle data error:
com.actiontech.dble.plan.common.exception.MySQLOutPutException: field not found:ABS(2)
        at com.actiontech.dble.backend.mysql.nio.handler.util.HandlerTool.createFieldItem(HandlerTool.java:253) ~[dble-9.9.9.9.jar:?]
        at com.actiontech.dble.backend.mysql.nio.handler.util.HandlerTool.createItem(HandlerTool.java:94) ~[dble-9.9.9.9.jar:?]
        at com.actiontech.dble.backend.mysql.nio.handler.query.impl.subquery.SingleRowSubQueryHandler.setSubQueryFiled(SingleRowSubQueryHandler.java:92) ~[dble-9.9.9.9.jar:?]
        at com.actiontech.dble.backend.mysql.nio.handler.query.impl.subquery.SingleRowSubQueryHandler.rowResponse(SingleRowSubQueryHandler.java:74) ~[dble-9.9.9.9.jar:?]
        at com.actiontech.dble.backend.mysql.nio.handler.query.impl.MultiNodeMergeHandler.rowResponse(MultiNodeMergeHandler.java:130) ~[dble-9.9.9.9.jar:?]
        at com.actiontech.dble.backend.mysql.nio.handler.query.impl.BaseSelectHandler.rowResponse(BaseSelectHandler.java:119) ~[dble-9.9.9.9.jar:?]
        at com.actiontech.dble.backend.mysql.nio.MySQLConnectionHandler.handleRowPacket(MySQLConnectionHandler.java:203) ~[dble-9.9.9.9.jar:?]
        at com.actiontech.dble.backend.mysql.nio.MySQLConnectionHandler.handleData(MySQLConnectionHandler.java:130) [dble-9.9.9.9.jar:?]
        at com.actiontech.dble.net.handler.BackendAsyncHandler.handleInnerData(BackendAsyncHandler.java:102) ~[dble-9.9.9.9.jar:?]
        at com.actiontech.dble.net.handler.BackendAsyncHandler.access$000(BackendAsyncHandler.java:19) ~[dble-9.9.9.9.jar:?]
        at com.actiontech.dble.net.handler.BackendAsyncHandler$1.run(BackendAsyncHandler.java:51) [dble-9.9.9.9.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_121]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_121]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]

```

/label ~BUG

**Comment by yexiaoli88** [comment]
verified on  version: 5.6.29-dble-9.9.9.9-edff869-20180928061234
