### ISSUE TITLE
"insert" error even "create .." return ok

### ISSUE THREAD

**Issue by yexiaoli88** [actiontech/dble#734]
* **dble version：5.6.29-dble-9.9.9.9-2a86e17-20180927083226**  
* **preconditions ：**  
no
* **configs：** 

**schema.xml**  

```
		<table name="aly_test" dataNode="dn1,dn2,dn3,dn4" rule="mod-long" />
```

* **steps：**    
    step1.  query in dble client port :
```
mysql> CREATE TABLE aly_test(id int, data1 varchar(10),data2 varchar(10),data3 varchar(20) as (concat(data1,' ',data2)));
Query OK, 0 rows affected (0.02 sec)

mysql> INSERT INTO aly_test (id,data1,data2)  VALUES (1,'aaa1','aaa2');
ERROR 3009 (HY000): Table meta 'mytest.aly_test' is lost,PLEASE reload @@metadata
```
step2 check metadata in dble manager port:
```
mysql> check full @@metadata where schema='mytest' and table='aly_test';
+--------+----------+-------------+-----------------+--------------------------+----------------------+
| schema | table    | reload_time | table_structure | consistent_in_data_nodes | consistent_in_memory |
+--------+----------+-------------+-----------------+--------------------------+----------------------+
| mytest | aly_test | null        | null            |                        0 |                    0 |
+--------+----------+-------------+-----------------+--------------------------+----------------------+
1 row in set (0.00 sec)
```
step3 check log:
```
2018-09-27 09:43:28.597  WARN [complexQueryExecutor5] (com.actiontech.dble.meta.table.MetaHelper.initTableMeta(MetaHelper.java:47)) - sql[CREATE TABLE `aly_test` (
  `id` int(11) DEFAULT NULL,
  `data1` varchar(10) DEFAULT NULL,
  `data2` varchar(10) DEFAULT NULL,
  `data3` varchar(20) GENERATED ALWAYS AS (concat(`data1`,' ',`data2`)) VIRTUAL
) ENGINE=InnoDB DEFAULT CHARSET=latin1] parser error:
com.alibaba.druid.sql.parser.ParserException: syntax error, error in :'(20) GENERATED ALWAYS AS (concat(`d',expect RPAREN, actual IDENTIFIER GENERATED
        at com.alibaba.druid.sql.parser.SQLParser.printError(SQLParser.java:261) ~[druid-1.0.31.jar:1.0.31]
        at com.alibaba.druid.sql.parser.SQLParser.accept(SQLParser.java:269) ~[druid-1.0.31.jar:1.0.31]
        at com.actiontech.dble.meta.table.CreateTableParserImp.parseCrateTable(CreateTableParserImp.java:75) ~[dble-9.9.9.9.jar:?]
        at com.actiontech.dble.meta.table.CreateTableParserImp.parseCreateTable(CreateTableParserImp.java:31) ~[dble-9.9.9.9.jar:?]
        at com.actiontech.dble.meta.table.MetaHelper.initTableMeta(MetaHelper.java:44) [dble-9.9.9.9.jar:?]
        at com.actiontech.dble.meta.table.old.AbstractTableMetaHandler$MySQLTableStructureListener.genTableMeta(AbstractTableMetaHandler.java:164) [dble-9.9.9.9.jar:?]
        at com.actiontech.dble.meta.table.old.AbstractTableMetaHandler$MySQLTableStructureListener.onResult(AbstractTableMetaHandler.java:134) [dble-9.9.9.9.jar:?]
        at com.actiontech.dble.meta.table.old.AbstractTableMetaHandler$MySQLTableStructureListener.onResult(AbstractTableMetaHandler.java:81) [dble-9.9.9.9.jar:?]
        at com.actiontech.dble.sqlengine.OneRawSQLQueryResultHandler.finished(OneRawSQLQueryResultHandler.java:88) [dble-9.9.9.9.jar:?]
        at com.actiontech.dble.sqlengine.SQLJob.doFinished(SQLJob.java:107) [dble-9.9.9.9.jar:?]
        at com.actiontech.dble.sqlengine.SQLJob.rowEofResponse(SQLJob.java:172) [dble-9.9.9.9.jar:?]
        at com.actiontech.dble.backend.mysql.nio.MySQLConnectionHandler.handleRowEofPacket(MySQLConnectionHandler.java:222) [dble-9.9.9.9.jar:?]
        at com.actiontech.dble.backend.mysql.nio.MySQLConnectionHandler.handleData(MySQLConnectionHandler.java:127) [dble-9.9.9.9.jar:?]
        at com.actiontech.dble.net.handler.BackendAsyncHandler.handleInnerData(BackendAsyncHandler.java:102) [dble-9.9.9.9.jar:?]
        at com.actiontech.dble.net.handler.BackendAsyncHandler.access$000(BackendAsyncHandler.java:19) [dble-9.9.9.9.jar:?]
        at com.actiontech.dble.net.handler.BackendAsyncHandler$1.run(BackendAsyncHandler.java:51) [dble-9.9.9.9.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_121]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_121]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]

```
* **expect result：**  
    "insert" should return ok 

/label ~BUG

**Comment by yanhuqing666** [comment]
If parsersupport ddl sql but not support "show create table"  
dble will create table and return error:  
ERROR 5316 (HY000): CREATE TABLE OK,BUT GENERATE METADATA FAILED

**Comment by yanhuqing666** [comment]
2cc3005a9230394ce04157dac89d177e31924ad7

**Comment by yexiaoli88** [comment]
related sql:

mysql> ALTER TABLE aly_test ADD PRIMARY KEY USING HASH (code);
ERROR 5316 (HY000): CREATE TABLE OK, BUT GENERATE METADATA FAILED

**Comment by FlyingMao** [comment]
verified version：5.6.29-dble-9.9.9.9-5fef501dbaaa747cb78bc6590921455254643965-20190322093714
