### ISSUE TITLE
If slow query log size larger than 64M,log file roll over failed

### ISSUE THREAD

**Issue by yanhuqing666** [actiontech/dble#751]
* **dble version：2.18.09.0-release**  
* **preconditions ：**  
no
* **configs：** 

**schema.xml**  

```
~

```

**rule.xml**  

```
~

```

**server.xml**  

```
<property name="enableSlowLog ">1</property>
<property name="flushSlowLogPeriod ">1</property>
<property name="flushSlowLogSize ">1000</property>
<property name="sqlSlowTime ">10</property>

```

* **steps：**    
    step1. If slow query log size large than 64M
* **expect result：**  
    1. file roll over to new log file
* **real result：**  
    1. file roll over failed,left lots of empty slow log files,and stackoverflow in wrapper.log

```
Exception in thread "SlowQueryLogProcessor" 
INFO   | jvm 1    | 2018/10/09 10:43:13 | java.lang.StackOverflowError
INFO   | jvm 1    | 2018/10/09 10:43:13 | 	at java.io.RandomAccessFile.open0(Native Method)
INFO   | jvm 1    | 2018/10/09 10:43:13 | 	at java.io.RandomAccessFile.open(RandomAccessFile.java:316)
INFO   | jvm 1    | 2018/10/09 10:43:13 | 	at java.io.RandomAccessFile.<init>(RandomAccessFile.java:243)
INFO   | jvm 1    | 2018/10/09 10:43:13 | 	at java.io.RandomAccessFile.<init>(RandomAccessFile.java:124)
INFO   | jvm 1    | 2018/10/09 10:43:13 | 	at com.actiontech.dble.log.DailyRotateLogStore.indexRollOver(DailyRotateLogStore.java:154)
INFO   | jvm 1    | 2018/10/09 10:43:13 | 	at com.actiontech.dble.log.DailyRotateLogStore.write(DailyRotateLogStore.java:111)
INFO   | jvm 1    | 2018/10/09 10:43:13 | 	at com.actiontech.dble.log.DailyRotateLogStore.writeFileHeader(DailyRotateLogStore.java:189)
INFO   | jvm 1    | 2018/10/09 10:43:13 | 	at com.actiontech.dble.log.DailyRotateLogStore.indexRollOver(DailyRotateLogStore.java:155)
INFO   | jvm 1    | 2018/10/09 10:43:13 | 	at com.actiontech.dble.log.DailyRotateLogStore.write(DailyRotateLogStore.java:111)
```

/label ~BUG

**Comment by yexiaoli88** [comment]
verified on version: 5.6.29-dble-9.9.9.9-80a984d-20181012031417
