### ISSUE TITLE
dble query [load data...] to global table got npe

### ISSUE THREAD

**Issue by irene-coming** [actiontech/dble#772]
* **dble version：**  
5.6.29-dble-2.18.10.0-c683b99-20181015051308

* **preconditions ：**  
no
* **configs：** 

**schema.xml**  
```
<table dataNode="dn1,dn2,dn3,dn4" name="test" type="global" />
```
* **steps：**    
    step1.  create file 'file1.txt' and fill contents in both dble and mysql seperately:
```
1,a,1,
```
    step2. execute sqls in both dble and mysql seperately
```mysql
create table test(id int, c1 char(5), c2 int, c3 int);
load data local infile './file1.txt' into table test fields terminated by ',' lines terminated by '\n';
select * from test order by id;
```
    step3.dble and mysql results : 
dble resultsets:
```mysql
mysql> load data local infile "./file1.txt" into table test fields terminated by',' lines terminated by '\n';
ERROR 4006 (HY000):  table is doing DDL
mysql> load data local infile "./file1.txt" into table test fields terminated by',' lines terminated by '\n';
ERROR 3009 (HY000):
mysql> load data local infile "./file1.txt" into table test fields terminated by',' lines terminated by '\n';
ERROR 4006 (HY000):  table is doing DDL
```
mysql resultsets:
```mysql
mysql> load data local infile "./file1.txt" into table test fields terminated by',' lines terminated by '\n';
Query OK, 1 row affected (0.00 sec)
Records: 1  Deleted: 0  Skipped: 0  Warnings: 0

mysql> select * from test;
+------+------+------+------+
| id   | c1   | c2   | c3   |
+------+------+------+------+
|    1 | a    |    5 |      |
+------+------+------+------+
1 row in set (0.00 sec)
```

* **expect result：**  
    1. step3 dble get same result with mysql
* **real result：**  
    1. step3 dble get different result with mysql as marked in above pictures
* **supplements：**  
    1. dble error log:
```logs
2018-10-19 03:28:40.210 DEBUG [BusinessExecutor0] (com.actiontech.dble.server.ServerQueryHandler.query(ServerQueryHandler.java:44)) - ServerConnection [id=1, schema=mytest, host=127.0.0.1, user=test,txIsolation=3, autocommit=true, schema=mytest]load data local infile "./file3.txt" into table test fields terminated by',' lines terminated by '\n'
2018-10-19 03:28:40.212  INFO [BusinessExecutor0] (com.actiontech.dble.net.FrontendConnection.loadDataInfileStart(FrontendConnection.java:256)) - load data error
java.lang.NullPointerException: null
        at com.actiontech.dble.server.handler.ServerLoadDataInfileHandler.parseLoadDataPram(ServerLoadDataInfileHandler.java:110) ~[dble-2.18.10.0.jar:?]
        at com.actiontech.dble.server.handler.ServerLoadDataInfileHandler.start(ServerLoadDataInfileHandler.java:170) ~[dble-2.18.10.0.jar:?]
        at com.actiontech.dble.net.FrontendConnection.loadDataInfileStart(FrontendConnection.java:254) [dble-2.18.10.0.jar:?]
        at com.actiontech.dble.server.ServerQueryHandler.query(ServerQueryHandler.java:134) [dble-2.18.10.0.jar:?]
        at com.actiontech.dble.net.FrontendConnection.query(FrontendConnection.java:319) [dble-2.18.10.0.jar:?]
        at com.actiontech.dble.net.FrontendConnection.query(FrontendConnection.java:335) [dble-2.18.10.0.jar:?]
        at com.actiontech.dble.net.handler.FrontendCommandHandler.handleData(FrontendCommandHandler.java:77) [dble-2.18.10.0.jar:?]
        at com.actiontech.dble.net.handler.FrontendCommandHandler.handle(FrontendCommandHandler.java:55) [dble-2.18.10.0.jar:?]
        at com.actiontech.dble.net.handler.FrontEndHandlerRunnable.run(FrontEndHandlerRunnable.java:44) [dble-2.18.10.0.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_121]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_121]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
```

/label ~BUG

**Comment by irene-coming** [comment]
verified on dble version: 5.6.29-dble-2.18.10.0-6cbccd3-20181020142155
append to autotest plan 10.0 on confluence

**Comment by irene-coming** [comment]
verified on dble version: 5.6.29-dble-2.18.10.0-6cbccd3-20181020142155
append to autotest plan 10.0 on confluence
