### ISSUE TITLE
NPE when the data of the insert exceeds the character length in the case of opening the slow log 

### ISSUE THREAD

**Issue by FlyingMao** [actiontech/dble#783]
* **dble version：**  
5.6.29-dble-9.9.9.9-8cad04d-20181025015852
* **preconditions ：**  
no
* **configs：** 

**schema.xml**  

```
<!DOCTYPE dble:schema SYSTEM "schema.dtd">
<dble:schema xmlns:dble="http://dble.cloud/">
    <schema name="mytest" sqlMaxLimit="100" dataNode="dn1">
        <table name="test_shard" dataNode="dn1,dn2,dn3,dn4" rule="mod-long"/>
    </schema>
    <dataNode name="dn1" dataHost="10.186.24.45" database="db1"/>
    <dataNode name="dn2" dataHost="10.186.24.46" database="db1"/>
    <dataNode name="dn3" dataHost="10.186.24.45" database="db2"/>
    <dataNode name="dn4" dataHost="10.186.24.46" database="db2"/>
    <dataHost balance="0" maxCon="1000" minCon="10" name="10.186.24.45" switchType="2" slaveThreshold="100">
        <heartbeat>show slave status</heartbeat>
        <writeHost host="hostM1" url="10.186.24.45:3306" password="test" user="test">
<!--            <readHost host="hostS1" url="10.186.24.44:3306" password="test" user="test"/> -->
        </writeHost>
    </dataHost>
    <dataHost balance="0" maxCon="1000" minCon="10" name="10.186.24.46" switchType="2" slaveThreshold="100">
        <heartbeat>show slave status</heartbeat>
        <writeHost host="hostW1" url="10.186.24.46:3306" password="test" user="test"/>
    </dataHost>
</dble:schema>


```

**rule.xml**  

```
<!DOCTYPE dble:rule SYSTEM "rule.dtd">
<dble:rule xmlns:dble="http://dble.cloud/">
    <tableRule name="mod-long">
        <rule>
            <columns>id</columns>
            <algorithm>sharding</algorithm>
        </rule>
    </tableRule>
    <tableRule name="orderID">
        <rule>
            <columns>id</columns>
            <algorithm>sharding</algorithm>
        </rule>
    </tableRule>
    <tableRule name="hash-two">
        <rule>
            <columns>id</columns>
            <algorithm>two-long</algorithm>
        </rule>
    </tableRule>
    <tableRule name="hash-three">
        <rule>
            <columns>id</columns>
            <algorithm>three-long</algorithm>
        </rule>
    </tableRule>
    <function name="sharding" class="Hash">
        <property name="partitionCount">4</property>
        <property name="partitionLength">1</property>
    </function>
    <function name="two-long" class="Hash">
        <property name="partitionCount">2</property>
        <property name="partitionLength">1</property>
    </function>
    <function name="three-long" class="Hash">
        <property name="partitionCount">3</property>
        <property name="partitionLength">1</property>
    </function>
</dble:rule>


```

**server.xml**  

```
<!DOCTYPE dble:server SYSTEM "server.dtd">
<dble:server xmlns:dble="http://dble.cloud/">
    <system>
        <property name="useGlobleTableCheck">1</property>
        <property name="dataNodeHeartbeatPeriod">60000</property>
        <property name="sqlExecuteTimeout">1000</property>
        <property name="recordTxn">1</property>
        <property name="xaRecoveryLogBaseDir">/opt/dble/tmlogs/</property>
        <property name="xaRecoveryLogBaseName">xalog</property>
        <property name="xaSessionCheckPeriod">2000</property>
        <property name="xaLogCleanPeriod">100000</property>
        <property name="processors">1</property>
        <property name="processorExecutor">4</property>
        <property name="sequnceHandlerType">2</property>
	<property name="enableSlowLog">1</property>
	<property name="sqlSlowTime">1</property>
    </system>
    <firewall/>
    <user name="test">
        <property name="password">test</property>
        <property name="schemas">mytest</property>
         <property name="maxCon">0</property>
    </user>
    <user name="root">
        <property name="password">123456</property>
        <property name="manager">true</property>
    </user>
</dble:server>

```

* **steps：**    
    step1.  prepare data
```
mysql> drop table if exists test_shard;                                                                                                             
Query OK, 0 rows affected (0.02 sec)

mysql>  CREATE TABLE test_shard(`id` int(10) unsigned NOT NULL,`t_id` int(10) unsigned NOT NULL DEFAULT '0',`name` char(1) NOT NULL DEFAULT '',`pad` int(11) NOT NULL,PRIMARY KEY (`id`),KEY `k_1` (`t_id`));
```
  step2.  the data of the insert exceeds the character length
```
mysql> insert into test_shard values(1,1,1,1),(2,2,'test_2',2),(3,3,'test中id为3',4),(4,4,4,3),(5,5,'test...5',1),(6,6,'test6',6);  
ERROR 1406 (22001): Data too long for column 'name' at row 1
```
  step3. check dble's log
  step4. execute insert in dble
```
mysql> insert into test_shard values(1,1,1,1);
Query OK, 1 row affected (0.01 sec)
```
  step5. check dble's slow log

* **expect result：**  
    1. step3: no error in dble's log
    2. step5: query:‘ insert into test_shard values(1,1,1,1); ’ in slow log
* **real result：**  
    1. step3: NPE error in wrapper.log
```
INFO   | jvm 1    | 2018/10/24 16:00:51 | Exception in thread "SlowQueryLogProcessor" java.lang.NullPointerException
INFO   | jvm 1    | 2018/10/24 16:00:51 | 	at com.actiontech.dble.server.trace.TraceResult.genSimpleLogs(TraceResult.java:412)
INFO   | jvm 1    | 2018/10/24 16:00:51 | 	at com.actiontech.dble.server.trace.TraceResult.genLogResult(TraceResult.java:329)
INFO   | jvm 1    | 2018/10/24 16:00:51 | 	at com.actiontech.dble.log.slow.SlowQueryLogEntry.toString(SlowQueryLogEntry.java:54)
INFO   | jvm 1    | 2018/10/24 16:00:51 | 	at com.actiontech.dble.log.slow.SlowQueryLogProcessor.writeLog(SlowQueryLogProcessor.java:85)
INFO   | jvm 1    | 2018/10/24 16:00:51 | 	at com.actiontech.dble.log.slow.SlowQueryLogProcessor.run(SlowQueryLogProcessor.java:58)
``` 

2. step5:query:'insert into test_shard values(1,1,1,1); 'not in slow log
* **supplements：**  
    1.

/label ~BUG

**Comment by FlyingMao** [comment]
verified version：5.6.29-dble-9.9.9.9-ca1044d-20181102102558

**Comment by FlyingMao** [comment]
**for tester**
the case of testlink : http://10.186.18.20:888/testlink/linkto.php?tprojectPrefix=dble&item=testcase&id=dble-749
