### ISSUE TITLE
some config error log can't tell which property make it

### ISSUE THREAD

**Issue by irene-coming** [actiontech/dble#905]
* **dble version：**  
5.6.24-dble-9.9.9.9-d1c7afe4a7ccb1176df3129c4e01ae46452221b7-20181220074232

* **preconditions ：**  
no
* **configs：** 

**schema.xml**  

```


```

**rule.xml**  

```


```

**server.xml**  

```
<system>
<property name="fakeMySQLVersion">5.6</property>
</system>
```

* **steps：**    
    step1.  start dble with above config
* **expect result：**  
    1. logs/wrapper.log can tell which property make start failed
* **real result：**  
    1.wrapper.log can 't tell which property make start dble failed
* **supplements：**  
    1.
wrapper.log segment
```xml
INFO   | jvm 1    | 2018/12/21 10:45:31 | com.actiontech.dble.config.util.ConfigException: java.lang.StringIndexOutOfBoundsException: String index out of range: -1
INFO   | jvm 1    | 2018/12/21 10:45:31 |       at com.actiontech.dble.config.loader.xml.XMLServerLoader.load(XMLServerLoader.java:97)
INFO   | jvm 1    | 2018/12/21 10:45:31 |       at com.actiontech.dble.config.loader.xml.XMLServerLoader.<init>(XMLServerLoader.java:42)
INFO   | jvm 1    | 2018/12/21 10:45:31 |       at com.actiontech.dble.config.ConfigInitializer.<init>(ConfigInitializer.java:51)
INFO   | jvm 1    | 2018/12/21 10:45:31 |       at com.actiontech.dble.config.ServerConfig.<init>(ServerConfig.java:67)
INFO   | jvm 1    | 2018/12/21 10:45:31 |       at com.actiontech.dble.DbleServer.startup(DbleServer.java:276)
INFO   | jvm 1    | 2018/12/21 10:45:31 |       at com.actiontech.dble.DbleStartup.main(DbleStartup.java:30)
INFO   | jvm 1    | 2018/12/21 10:45:31 |       at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
INFO   | jvm 1    | 2018/12/21 10:45:31 |       at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
INFO   | jvm 1    | 2018/12/21 10:45:31 |       at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
INFO   | jvm 1    | 2018/12/21 10:45:31 |       at java.lang.reflect.Method.invoke(Method.java:498)
INFO   | jvm 1    | 2018/12/21 10:45:31 |       at org.tanukisoftware.wrapper.WrapperSimpleApp.run(WrapperSimpleApp.java:240)
INFO   | jvm 1    | 2018/12/21 10:45:31 |       at java.lang.Thread.run(Thread.java:745)
INFO   | jvm 1    | 2018/12/21 10:45:31 | Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: -1
INFO   | jvm 1    | 2018/12/21 10:45:31 |       at java.lang.String.substring(String.java:1967)
INFO   | jvm 1    | 2018/12/21 10:45:31 |       at com.actiontech.dble.config.loader.xml.SystemConfigLoader.load(SystemConfigLoader.java:43)
INFO   | jvm 1    | 2018/12/21 10:45:31 |       at com.actiontech.dble.config.loader.xml.SystemConfigLoader.load(SystemConfigLoader.java:21)
INFO   | jvm 1    | 2018/12/21 10:45:31 |       at com.actiontech.dble.config.loader.xml.XMLServerLoader.load(XMLServerLoader.java:93)
INFO   | jvm 1    | 2018/12/21 10:45:31 |       ... 11 more
STATUS | wrapper  | 2018/12/21 10:45:33 | <-- Wrapper Stopped
```

/label ~BUG

**Comment by FlyingMao** [comment]
**The value of `processors` is an illegal value**

1. the value is `0`：startup succeeded but connection could not be established
the error when establishing a connection：
```
mysql: [Warning] Using a password on the command line interface can be insecure.
ERROR 2013 (HY000): Lost connection to MySQL server at 'reading initial communication packet', system error: 2
```
dble log:
```
2018-12-27 03:43:46.220  INFO [$_Dble_Manager] (com.actiontech.dble.net.NIOAcceptor.accept(NIOAcceptor.java:97)) - $_Dble_Manager
java.lang.ArrayIndexOutOfBoundsException: 0
	at com.actiontech.dble.DbleServer.nextFrontProcessor(DbleServer.java:725) ~[dble-9.9.9.9.jar:?]
	at com.actiontech.dble.net.NIOAcceptor.accept(NIOAcceptor.java:90) [dble-9.9.9.9.jar:?]
	at com.actiontech.dble.net.NIOAcceptor.run(NIOAcceptor.java:66) [dble-9.9.9.9.jar:?]
```

2. the value is `1`: startup failed
```
INFO   | jvm 1    | 2018/12/27 03:46:27 | java.lang.NegativeArraySizeException
INFO   | jvm 1    | 2018/12/27 03:46:27 | 	at com.actiontech.dble.DbleServer.startup(DbleServer.java:321)
INFO   | jvm 1    | 2018/12/27 03:46:27 | 	at com.actiontech.dble.DbleStartup.main(DbleStartup.java:30)
INFO   | jvm 1    | 2018/12/27 03:46:27 | 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
INFO   | jvm 1    | 2018/12/27 03:46:27 | 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
INFO   | jvm 1    | 2018/12/27 03:46:27 | 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
INFO   | jvm 1    | 2018/12/27 03:46:27 | 	at java.lang.reflect.Method.invoke(Method.java:498)
INFO   | jvm 1    | 2018/12/27 03:46:27 | 	at org.tanukisoftware.wrapper.WrapperSimpleApp.run(WrapperSimpleApp.java:240)
INFO   | jvm 1    | 2018/12/27 03:46:27 | 	at java.lang.Thread.run(Thread.java:748)
STATUS | wrapper  | 2018/12/27 03:46:29 | <-- Wrapper Stopped
```

**Comment by FlyingMao** [comment]
**verified version:** 5.6.29-dble-9.9.9.9-c60b90b31aad56503ff71ae8ffd8e6e271a207f1-20190103085956
