### ISSUE TITLE
 When testing the stability of dble + lvs, Dble returns to NPE

### ISSUE THREAD

**Issue by FlyingMao** [actiontech/dble#954]
* **dble version：**  
5.6.29-dble-2.18.12.0-9fdecff1efb443a4dbdcd1f642be1141431965ea-20190108042852
* **preconditions ：**  
no
* **configs：** 

**schema.xml**  

```

```

**rule.xml**  

```

```

**server.xml**  

```
```
**wrapper.conf**
```

```
* **steps：**    
    step1.  Set the environment according to the default configuration of lvs，and make it associated with 2 dble
    step2.  Use sysbench to connect lvs vip to prepare data
```
./sysbench --mysql-db=lvs_test --db-driver=mysql --mysql-host=10.186.17.150 --mysql-port=8066 --mysql-table-engine=innodb --mysql-user=action --oltp_auto_inc=off --mysql-password=action --test=../db/insert.lua --oltp_tables_count=1 --oltp-table-size=1000000 prepare
```
    
step3.  Use sysbench to connect lvs vip to execute test query
```
./sysbench --mysql-db=lvs_test --mysql-host=10.186.17.150 --mysql-port=8066 --mysql-table-engine=innodb --mysql-user=action --mysql-password=action --test=../db/select.lua --oltp_tables_count=1 --oltp-table-size=1000000 --num-threads=1024 --oltp-read-only=off --report-interval=1 --default-charset=utf8 --max-time=604800 --max-requests=0 --percentile=95 run
```

* **expect result：**  
    1. executed successed
* **real result：**  
    1. dble return error
```
INFO   | jvm 1    | 2019/01/23 12:41:45 | Exception in thread "complexQueryExecutor616" java.lang.NullPointerException
INFO   | jvm 1    | 2019/01/23 12:41:45 | 	at java.util.concurrent.ConcurrentHashMap.replaceNode(ConcurrentHashMap.java:1106)
INFO   | jvm 1    | 2019/01/23 12:41:45 | 	at java.util.concurrent.ConcurrentHashMap.remove(ConcurrentHashMap.java:1097)
INFO   | jvm 1    | 2019/01/23 12:41:45 | 	at com.actiontech.dble.server.NonBlockingSession.releaseConnection(NonBlockingSession.java:736)
INFO   | jvm 1    | 2019/01/23 12:41:45 | 	at com.actiontech.dble.server.NonBlockingSession.releaseConnectionIfSafe(NonBlockingSession.java:729)
INFO   | jvm 1    | 2019/01/23 12:41:45 | 	at com.actiontech.dble.backend.mysql.nio.handler.SingleNodeHandler.backConnectionErr(SingleNodeHandler.java:143)
INFO   | jvm 1    | 2019/01/23 12:41:45 | 	at com.actiontech.dble.backend.mysql.nio.handler.SingleNodeHandler.connectionClose(SingleNodeHandler.java:393)
INFO   | jvm 1    | 2019/01/23 12:41:45 | 	at com.actiontech.dble.backend.mysql.nio.MySQLConnection$1.run(MySQLConnection.java:656)
INFO   | jvm 1    | 2019/01/23 12:41:45 | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
INFO   | jvm 1    | 2019/01/23 12:41:45 | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
INFO   | jvm 1    | 2019/01/23 12:41:45 | 	at java.lang.Thread.run(Thread.java:748)
INFO   | jvm 1    | 2019/01/25 16:05:41 | Exception in thread "Timer0" 
INFO   | jvm 1    | 2019/01/25 16:05:41 | java.lang.NullPointerException
INFO   | jvm 1    | 2019/01/25 16:05:41 | 	at com.actiontech.dble.backend.datasource.PhysicalDatasource.longIdleHeartBeat(PhysicalDatasource.java:217)
INFO   | jvm 1    | 2019/01/25 16:05:41 | 	at com.actiontech.dble.backend.datasource.PhysicalDatasource.connectionHeatBeatCheck(PhysicalDatasource.java:181)
INFO   | jvm 1    | 2019/01/25 16:05:41 | 	at com.actiontech.dble.backend.datasource.PhysicalDBPool.heartbeatCheck(PhysicalDBPool.java:455)
INFO   | jvm 1    | 2019/01/25 16:05:41 | 	at com.actiontech.dble.DbleServer$9$1.run(DbleServer.java:889)
INFO   | jvm 1    | 2019/01/25 16:05:41 | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
INFO   | jvm 1    | 2019/01/25 16:05:41 | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
INFO   | jvm 1    | 2019/01/25 16:05:41 | 	at java.lang.Thread.run(Thread.java:748)
```
* **supplements：**  
    1.

/label ~BUG

**Comment by sunsun314** [comment]
use Btrace bellow to verify the fix
```
package com.actiontech.dble.btrace.script;

import com.sun.btrace.BTraceUtils;
import com.sun.btrace.annotations.*;

/**
 * Created by szf on 2019/1/28.
 */
@BTrace(unsafe = true)
public class BtraceLineIdle {

    @OnMethod(clazz = "com.actiontech.dble.backend.datasource.PhysicalDatasource", method = "field",
            location = @Location(value = Kind.LINE, line = 216))
    public static void args(@Self Object self, @ProbeMethodName String pmn, int line) throws Exception {
        BTraceUtils.print("delay for NP test");
        BTraceUtils.print("for print order ...................");
        Thread.sleep(100000L);
    }
}
```

**Comment by sunsun314** [comment]
This issue contents 2 main error point
+ double release in single node query.(Only can verified by stability check)
+ Connection idle check cause NP Execption.(Can be verified by btrace above)

**Comment by FlyingMao** [comment]
**verified version:** 5.6.29-dble-9.9.9.9-e921fc54b28a8963b260c6b470ca95310ae4434f-20190222044624
