### ISSUE TITLE
reload @@config_all gets odds err "java.util.ConcurrentModificationException"

### ISSUE THREAD

**Issue by irene-coming** [actiontech/dble#984]
* **dble version：**  
5.6.29-dble-9.9.9.9-77ac73eb405ba6933bc967e0bdbbfd70fdcf9f1e-20190201043948

* **preconditions ：**  
no
* **configs：** 

**schema.xml**  

```
	<schema dataNode="dn5" name="mytest" sqlMaxLimit="100">
		<table dataNode="dn1,dn2,dn3,dn4" name="test" type="global" />
	</schema>
         <dataNode dataHost="172.100.9.5" database="da11" name="dn1" />
        <dataNode dataHost="172.100.9.6" database="da11" name="dn2" />
        <dataNode dataHost="172.100.9.5" database="da21" name="dn3" />
        <dataNode dataHost="172.100.9.6" database="da21" name="dn4" />
        <dataNode dataHost="172.100.9.5" database="da31" name="dn5" />

```

**rule.xml**  

```


```

**server.xml**  

```


```

* **steps：**    
    step1.  info: mysql-master1 is 172.100.9.5, mysql-master2 is 172.100.9.6, execute following steps:
```
    Then execute sql in "mysql-master1"
        | user | passwd | conn   | toClose  | sql                          | expect   | db      |
        | test | 111111 | conn_0 | True     | drop database if exists da11 | success  |         |
        | test | 111111 | conn_0 | True     | drop database if exists da21 | success  |         |
        | test | 111111 | conn_0 | True     | drop database if exists da31 | success  |         |
    Then execute sql in "mysql-master2"
        | user | passwd | conn   | toClose  | sql                          | expect   | db      |
        | test | 111111 | conn_0 | True     | drop database if exists da11 | success  |         |
        | test | 111111 | conn_0 | True     | drop database if exists da21 | success  |         |
    Then execute admin cmd "reload @@config_all"
```
* **expect result：**  
    1. reload @@config_all success
* **real result：**  
    1.reload @@config_all gets error: "java.util.ConcurrentModificationException" occasionally
* **supplements：**  
    1.autotest position:
  features/func_test/managercmd/create_database.feature:45  "create database @@..." for part of used datanode #2
![image](https://user-images.githubusercontent.com/6801133/52692839-fe0bc300-2f9f-11e9-84ca-8ba57b17e8fc.png)
2. dble.log
```log4j
2019-02-09 00:19:43.853  WARN [complexQueryExecutor0] (com.actiontech.dble.meta.table.GetSpecialNodeTablesHandler.handleFinished(GetSpecialNodeTablesHandler.java:46)) - Can't get table test's config from DataNode:dn4! Maybe the table is not initialized!
2019-02-09 00:19:43.853  INFO [BusinessExecutor0] (com.actiontech.dble.manager.response.ReloadConfig.execute(ReloadConfig.java:130)) - reload error
java.util.ConcurrentModificationException: null
	at java.util.LinkedList$ListItr.checkForComodification(LinkedList.java:966) ~[?:1.8.0_121]
	at java.util.LinkedList$ListItr.next(LinkedList.java:888) ~[?:1.8.0_121]
	at java.util.AbstractCollection.toString(AbstractCollection.java:461) ~[?:1.8.0_121]
	at java.lang.String.valueOf(String.java:2994) ~[?:1.8.0_121]
	at java.lang.StringBuilder.append(StringBuilder.java:131) ~[?:1.8.0_121]
	at com.actiontech.dble.meta.table.MultiTablesMetaHandler.countDownShardTable(MultiTablesMetaHandler.java:167) ~[dble-9.9.9.9.jar:?]
	at com.actiontech.dble.meta.table.TablesMetaInitHandler.countdown(TablesMetaInitHandler.java:21) ~[dble-9.9.9.9.jar:?]
	at com.actiontech.dble.meta.table.AbstractTablesMetaHandler.execute(AbstractTablesMetaHandler.java:55) ~[dble-9.9.9.9.jar:?]
	at com.actiontech.dble.meta.table.MultiTablesMetaHandler.execute(MultiTablesMetaHandler.java:83) ~[dble-9.9.9.9.jar:?]
	at com.actiontech.dble.meta.table.SchemaMetaHandler.execute(SchemaMetaHandler.java:77) ~[dble-9.9.9.9.jar:?]
	at com.actiontech.dble.meta.ProxyMetaManager.initMeta(ProxyMetaManager.java:407) ~[dble-9.9.9.9.jar:?]
	at com.actiontech.dble.DbleServer.reloadMetaData(DbleServer.java:532) ~[dble-9.9.9.9.jar:?]
	at com.actiontech.dble.DbleServer.reloadMetaData(DbleServer.java:523) ~[dble-9.9.9.9.jar:?]
	at com.actiontech.dble.config.ServerConfig.apply(ServerConfig.java:305) ~[dble-9.9.9.9.jar:?]
	at com.actiontech.dble.config.ServerConfig.reload(ServerConfig.java:214) ~[dble-9.9.9.9.jar:?]
	at com.actiontech.dble.manager.response.ReloadConfig.reloadAll(ReloadConfig.java:373) ~[dble-9.9.9.9.jar:?]
	at com.actiontech.dble.manager.response.ReloadConfig.load(ReloadConfig.java:239) ~[dble-9.9.9.9.jar:?]
	at com.actiontech.dble.manager.response.ReloadConfig.execute(ReloadConfig.java:127) [dble-9.9.9.9.jar:?]
	at com.actiontech.dble.manager.response.ReloadConfig.execute(ReloadConfig.java:73) [dble-9.9.9.9.jar:?]
	at com.actiontech.dble.manager.handler.ReloadHandler.handle(ReloadHandler.java:27) [dble-9.9.9.9.jar:?]
	at com.actiontech.dble.manager.ManagerQueryHandler.query(ManagerQueryHandler.java:83) [dble-9.9.9.9.jar:?]
	at com.actiontech.dble.net.FrontendConnection.query(FrontendConnection.java:330) [dble-9.9.9.9.jar:?]
	at com.actiontech.dble.net.FrontendConnection.query(FrontendConnection.java:346) [dble-9.9.9.9.jar:?]
	at com.actiontech.dble.net.handler.ManagerCommandHandler.handleData(ManagerCommandHandler.java:27) [dble-9.9.9.9.jar:?]
	at com.actiontech.dble.net.handler.FrontendCommandHandler.handle(FrontendCommandHandler.java:66) [dble-9.9.9.9.jar:?]
	at com.actiontech.dble.net.handler.FrontEndHandlerRunnable.run(FrontEndHandlerRunnable.java:44) [dble-9.9.9.9.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_121]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
2019-02-09 00:19:43.856  WARN [BusinessExecutor0] (com.actiontech.dble.manager.response.ReloadConfig.writeErrorResult(ReloadConfig.java:266)) - Reload config failure.The reason is java.util.ConcurrentModificationException
2019-02-09 00:19:44.067 DEBUG [Timer0] (com.actiontech.dble.server.util.GlobalTableUtil.consistencyCheck(GlobalTableUtil.java:172)) - isColumnCountCheckFinished:1
```

/label ~BUG

**Comment by yanhuqing666** [comment]
If a physical datanode has no tables.
This may happen:
AbstractTablesMetaHandler ->listExistTables
thread 1:
before lock,
switch to thread 2.
thread 2:
GetNodeTablesHandler->onResult 
finished = true;
switch to thread 1.
thread 1:
listExistTables return &countdown()
multiTablesMetaHandler.countDownShardTable()

and at the same time,thread 2:
handleFinished->GetSpecialNodeTablesHandler->handleFinished()
handlerTable->multiTablesMetaHandler.checkTableConsistent()

so thread1 and thread2 will may modify a same list

**Comment by yexiaoli88** [comment]
verified on version: 5.6.29-dble-9.9.9.9-cf09b8706dd2d80d773da907642241feb75d1900-20190219105209
