### ISSUE TITLE
clean dble registered keys in zk make file dnindex.properties under conf dir deleted

### ISSUE THREAD

**Issue by irene-coming** [actiontech/dble#991]
* **dble version：**  
5.6.29-dble-9.9.9.9-4e4bce50ec3a4b25ed7e3844dabdf31568da50f0-20190214070851

* **preconditions ：**  
dnindex.properties file exist under conf dir
* **configs：** 

**schema.xml**  

```


```

**rule.xml**  

```


```

**server.xml**  

```


```

* **steps：**    
    step1.  start dble in zk mode
    step2. ./zkCli.sh
```shell
[zk: localhost:2181(CONNECTED) 2] ls /
[dble, zookeeper]
[zk: localhost:2181(CONNECTED) 3] rmr /dble
[zk: localhost:2181(CONNECTED) 4]
```
    step3. check dble/conf dir, dnindex.properties disappeared
    step4. restart dble failed for:
```log4j
INFO   | jvm 1    | 2019/02/14 15:40:45 |
INFO   | jvm 1    | 2019/02/14 15:40:48 | java.lang.RuntimeException: java.io.FileNotFoundException: ./conf/dnindex.properties (No such file or directory)
INFO   | jvm 1    | 2019/02/14 15:40:48 |       at com.actiontech.dble.DbleServer.initZkDnindex(DbleServer.java:514)
INFO   | jvm 1    | 2019/02/14 15:40:48 |       at com.actiontech.dble.DbleServer.startup(DbleServer.java:480)
INFO   | jvm 1    | 2019/02/14 15:40:48 |       at com.actiontech.dble.DbleStartup.main(DbleStartup.java:30)
INFO   | jvm 1    | 2019/02/14 15:40:48 |       at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
INFO   | jvm 1    | 2019/02/14 15:40:48 |       at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
INFO   | jvm 1    | 2019/02/14 15:40:48 |       at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
INFO   | jvm 1    | 2019/02/14 15:40:48 |       at java.lang.reflect.Method.invoke(Method.java:498)
INFO   | jvm 1    | 2019/02/14 15:40:48 |       at org.tanukisoftware.wrapper.WrapperSimpleApp.run(WrapperSimpleApp.java:240)
INFO   | jvm 1    | 2019/02/14 15:40:48 |       at java.lang.Thread.run(Thread.java:745)
INFO   | jvm 1    | 2019/02/14 15:40:48 | Caused by: java.io.FileNotFoundException: ./conf/dnindex.properties (No such file or directory)
INFO   | jvm 1    | 2019/02/14 15:40:48 |       at java.io.FileInputStream.open0(Native Method)
INFO   | jvm 1    | 2019/02/14 15:40:48 |       at java.io.FileInputStream.open(FileInputStream.java:195)
INFO   | jvm 1    | 2019/02/14 15:40:48 |       at java.io.FileInputStream.<init>(FileInputStream.java:138)
INFO   | jvm 1    | 2019/02/14 15:40:48 |       at com.google.common.io.Files$FileByteSource.openStream(Files.java:126)
INFO   | jvm 1    | 2019/02/14 15:40:48 |       at com.google.common.io.Files$FileByteSource.read(Files.java:150)
INFO   | jvm 1    | 2019/02/14 15:40:48 |       at com.google.common.io.Files.toByteArray(Files.java:260)
INFO   | jvm 1    | 2019/02/14 15:40:48 |       at com.actiontech.dble.DbleServer.initZkDnindex(DbleServer.java:507)
INFO   | jvm 1    | 2019/02/14 15:40:48 |       ... 8 more
STATUS | wrapper  | 2019/02/14 15:40:50 | <-- Wrapper Stopped
```
* **expect result：**  
- [x] step4 start dble should success even without dnindex.properties

* **real result：**  
    1.
* **supplements：**  
    1. after rmr /dble, (none master dble) dble.log:
```log4j
2019-02-14 07:50:10.399 ERROR [WrapperSimpleAppMain-EventThread] (org.apache.curator.framework.recipes.cache.NodeCache$4.apply(NodeCache.java:315)) - Calling listener
java.lang.NullPointerException: null
        at com.actiontech.dble.config.loader.zkprocess.zktoxml.ZktoXmlMain$1.nodeChanged(ZktoXmlMain.java:146) ~[dble-9.9.9.9.jar:?]
        at org.apache.curator.framework.recipes.cache.NodeCache$4.apply(NodeCache.java:310) [curator-recipes-2.11.0.jar:?]
        at org.apache.curator.framework.recipes.cache.NodeCache$4.apply(NodeCache.java:304) [curator-recipes-2.11.0.jar:?]
        at org.apache.curator.framework.listen.ListenerContainer$1.run(ListenerContainer.java:93) [curator-framework-2.11.0.jar:?]
        at com.google.common.util.concurrent.MoreExecutors$DirectExecutorService.execute(MoreExecutors.java:310) [guava-19.0.jar:?]
        at org.apache.curator.framework.listen.ListenerContainer.forEach(ListenerContainer.java:84) [curator-framework-2.11.0.jar:?]
        at org.apache.curator.framework.recipes.cache.NodeCache.setNewData(NodeCache.java:301) [curator-recipes-2.11.0.jar:?]
        at org.apache.curator.framework.recipes.cache.NodeCache.processBackgroundResult(NodeCache.java:278) [curator-recipes-2.11.0.jar:?]
        at org.apache.curator.framework.recipes.cache.NodeCache.access$300(NodeCache.java:56) [curator-recipes-2.11.0.jar:?]
        at org.apache.curator.framework.recipes.cache.NodeCache$3.processResult(NodeCache.java:122) [curator-recipes-2.11.0.jar:?]
        at org.apache.curator.framework.imps.CuratorFrameworkImpl.sendToBackgroundCallback(CuratorFrameworkImpl.java:749) [curator-framework-2.11.0.jar:?]
        at org.apache.curator.framework.imps.CuratorFrameworkImpl.processBackgroundOperation(CuratorFrameworkImpl.java:522) [curator-framework-2.11.0.jar:?]
        at org.apache.curator.framework.imps.ExistsBuilderImpl$1.processResult(ExistsBuilderImpl.java:137) [curator-framework-2.11.0.jar:?]
        at org.apache.zookeeper.ClientCnxn$EventThread.processEvent(ClientCnxn.java:555) [zookeeper-3.4.6.jar:3.4.6-1569965]
        at org.apache.zookeeper.ClientCnxn$EventThread.run(ClientCnxn.java:498) [zookeeper-3.4.6.jar:3.4.6-1569965]
2019-02-14 07:50:23.322  INFO [WrapperSimpleAppMain-EventThread] (com.actiontech.dble.config.loader.zkprocess.zktoxml.ZktoXmlMain$1.nodeChanged(ZktoXmlMain.java:145)) - ZktoxmlMain runWatch  process path  event start
2019-02-14 07:50:23.322  INFO [WrapperSimpleAppMain-EventThread] (com.actiontech.dble.config.loader.zkprocess.zktoxml.ZktoXmlMain$1.nodeChanged(ZktoXmlMain.java:147)) - NodeCache changed, path is: /dble/cluster-1/binlog_pause/status
2019-02-14 07:50:23.324  INFO [WrapperSimpleAppMain-EventThread] (com.actiontech.dble.config.loader.zkprocess.zktoxml.listen.BinlogPauseStatusListener.notifyProcess(BinlogPauseStatusListener.java:47)) - BinlogPauseStatusListener notifyProcess zk to object  :{}
2019-02-14 07:50:23.324  WARN [WrapperSimpleAppMain-EventThread] (com.actiontech.dble.config.loader.zkprocess.comm.ZookeeperProcessListen.notify(ZookeeperProcessListen.java:51)) - ZookeeperProcessListen notify key :/dble/cluster-1/binlog_pause/status error:Exception info:
java.lang.ArrayIndexOutOfBoundsException: 1
        at com.actiontech.dble.config.loader.zkprocess.zookeeper.process.BinlogPause.<init>(BinlogPause.java:28) ~[dble-9.9.9.9.jar:?]
        at com.actiontech.dble.config.loader.zkprocess.zktoxml.listen.BinlogPauseStatusListener.notifyProcess(BinlogPauseStatusListener.java:49) ~[dble-9.9.9.9.jar:?]
        at com.actiontech.dble.config.loader.zkprocess.comm.ZookeeperProcessListen.notify(ZookeeperProcessListen.java:49) [dble-9.9.9.9.jar:?]
        at com.actiontech.dble.config.loader.zkprocess.zktoxml.ZktoXmlMain$1.nodeChanged(ZktoXmlMain.java:149) [dble-9.9.9.9.jar:?]
        at org.apache.curator.framework.recipes.cache.NodeCache$4.apply(NodeCache.java:310) [curator-recipes-2.11.0.jar:?]
        at org.apache.curator.framework.recipes.cache.NodeCache$4.apply(NodeCache.java:304) [curator-recipes-2.11.0.jar:?]
        at org.apache.curator.framework.listen.ListenerContainer$1.run(ListenerContainer.java:93) [curator-framework-2.11.0.jar:?]
        at com.google.common.util.concurrent.MoreExecutors$DirectExecutorService.execute(MoreExecutors.java:310) [guava-19.0.jar:?]
        at org.apache.curator.framework.listen.ListenerContainer.forEach(ListenerContainer.java:84) [curator-framework-2.11.0.jar:?]
        at org.apache.curator.framework.recipes.cache.NodeCache.setNewData(NodeCache.java:301) [curator-recipes-2.11.0.jar:?]
        at org.apache.curator.framework.recipes.cache.NodeCache.processBackgroundResult(NodeCache.java:269) [curator-recipes-2.11.0.jar:?]
        at org.apache.curator.framework.recipes.cache.NodeCache.access$300(NodeCache.java:56) [curator-recipes-2.11.0.jar:?]
        at org.apache.curator.framework.recipes.cache.NodeCache$3.processResult(NodeCache.java:122) [curator-recipes-2.11.0.jar:?]
        at org.apache.curator.framework.imps.CuratorFrameworkImpl.sendToBackgroundCallback(CuratorFrameworkImpl.java:749) [curator-framework-2.11.0.jar:?]
        at org.apache.curator.framework.imps.CuratorFrameworkImpl.processBackgroundOperation(CuratorFrameworkImpl.java:522) [curator-framework-2.11.0.jar:?]
        at org.apache.curator.framework.imps.GetDataBuilderImpl$3.processResult(GetDataBuilderImpl.java:257) [curator-framework-2.11.0.jar:?]
        at org.apache.zookeeper.ClientCnxn$EventThread.processEvent(ClientCnxn.java:561) [zookeeper-3.4.6.jar:3.4.6-1569965]
        at org.apache.zookeeper.ClientCnxn$EventThread.run(ClientCnxn.java:498) [zookeeper-3.4.6.jar:3.4.6-1569965]
2019-02-14 07:50:23.324  INFO [WrapperSimpleAppMain-EventThread] (com.actiontech.dble.config.loader.zkprocess.zktoxml.ZktoXmlMain$1.nodeChanged(ZktoXmlMain.java:150)) - ZktoxmlMain runWatch  process path  event over
```

/label ~BUG

**Comment by wjl1619** [comment]
verified on dble version: 5.6.29-dble-9.9.9.9-884fc6b612d64cc22101226536f8fd1d24580857-20190221031624
now dble restart success after rmr /dble , but the content of file dnindex.properties is empty.
