### ISSUE TITLE
Error grammar :insert query without value, NPE

### ISSUE THREAD

**Issue by FlyingMao** [actiontech/dble#994]
* **dble version：**  
5.6.29-dble-9.9.9.9-1ba0144afdc829380fc75f092bc44950b8fc78e6-20190213091745
* **preconditions ：**  
no
* **configs：** 

**schema.xml**  

```
<schema name="mytest" sqlMaxLimit="100" dataNode="dn1">  
  <table name="test_shard" dataNode="dn1,dn2,dn3,dn4" rule="hash-four" autoIncrement="true" incrementColumn="t_id"/>
</schema>

```

**rule.xml**  

```


```

**server.xml**  

```


```

* **steps：**    
    step1.  create table
```
create table test_shard(id int,t_id int);
```
   step2.  insert 
```
insert into test_shard(1);
```
* **expect result：**  
    1. return error like that syntax error
* **real result：**  
    1.
```
mysql> insert into test_shard(1);
ERROR 1064 (HY000): NullPointerException
```
* **supplements：**  
    1. dble log:
```
2019-02-15 06:07:11.167  INFO [BusinessExecutor2] (com.actiontech.dble.server.ServerConnection.executeException(ServerConnection.java:387)) - ServerConnection [id=1, schema=mytest, host=127.0.0.1, user=test,txIsolation=3, autocommit=true, schema=mytest]insert into test_shard(1) err:java.lang.NullPointerException
java.lang.NullPointerException: null
	at com.actiontech.dble.route.parser.druid.impl.DruidInsertParser.convertInsertSQL(DruidInsertParser.java:387) ~[dble-9.9.9.9.jar:?]
	at com.actiontech.dble.route.parser.druid.impl.DruidInsertParser.visitorParse(DruidInsertParser.java:85) ~[dble-9.9.9.9.jar:?]
	at com.actiontech.dble.route.parser.druid.impl.DefaultDruidParser.parser(DefaultDruidParser.java:56) ~[dble-9.9.9.9.jar:?]
	at com.actiontech.dble.route.util.RouterUtil.routeFromParser(RouterUtil.java:125) ~[dble-9.9.9.9.jar:?]
	at com.actiontech.dble.route.impl.DefaultRouteStrategy.routeNormalSqlWithAST(DefaultRouteStrategy.java:81) ~[dble-9.9.9.9.jar:?]
	at com.actiontech.dble.route.impl.AbstractRouteStrategy.route(AbstractRouteStrategy.java:50) ~[dble-9.9.9.9.jar:?]
	at com.actiontech.dble.route.RouteService.route(RouteService.java:112) ~[dble-9.9.9.9.jar:?]
	at com.actiontech.dble.server.ServerConnection.routeEndExecuteSQL(ServerConnection.java:324) [dble-9.9.9.9.jar:?]
	at com.actiontech.dble.server.ServerConnection.execute(ServerConnection.java:267) [dble-9.9.9.9.jar:?]
	at com.actiontech.dble.server.ServerQueryHandler.query(ServerQueryHandler.java:166) [dble-9.9.9.9.jar:?]
	at com.actiontech.dble.net.FrontendConnection.query(FrontendConnection.java:330) [dble-9.9.9.9.jar:?]
	at com.actiontech.dble.net.FrontendConnection.query(FrontendConnection.java:346) [dble-9.9.9.9.jar:?]
	at com.actiontech.dble.net.handler.FrontendCommandHandler.handleData(FrontendCommandHandler.java:88) [dble-9.9.9.9.jar:?]
	at com.actiontech.dble.net.handler.FrontendCommandHandler.handle(FrontendCommandHandler.java:66) [dble-9.9.9.9.jar:?]
	at com.actiontech.dble.net.handler.FrontEndHandlerRunnable.run(FrontEndHandlerRunnable.java:44) [dble-9.9.9.9.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_131]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_131]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]

```

/label ~BUG

**Comment by sunsun314** [comment]
Error message change to 'Insert syntax error,no values in sql'

**Comment by FlyingMao** [comment]
**verified version：** 5.6.29-dble-9.9.9.9-cf09b8706dd2d80d773da907642241feb75d1900-20190219105209
